// Generated from the actual disposable PostgreSQL catalog by scripts/database/generate-types.mjs.
// Do not hand-edit. Migration versions: 0001,0002,0003,0004,0005,0006,0007,0008,0009,0010,0011,0012,0013,0014,0015,0016,0017,0018,0019,0020,0021,0022,0023,0024,0025,0026,0027,0028,0029,0030,0031,0032,0033,0034,0035,0036
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: {
Tables: {
"account_entitlements": {
Row: {
"user_id": string;
"plan": string;
"status": string;
"valid_until": string | null;
"source": string;
"updated_at": string;
};
Insert: {
"user_id": string;
"plan"?: string;
"status"?: string;
"valid_until"?: string | null;
"source"?: string;
"updated_at"?: string;
};
Update: {
"user_id"?: string;
"plan"?: string;
"status"?: string;
"valid_until"?: string | null;
"source"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "account_entitlements_user_id_fkey"; columns: ["user_id"]; isOneToOne: true; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"admin_binder_summaries": {
Row: {
"binder_id": string;
"owner_id": string;
"title": string;
"subject": string;
"status": Database["public"]["Enums"]["publish_status"];
"document_count": number;
"preview_document_count": number;
"empty_document_count": number;
"total_word_count": number;
"last_updated_at": string;
"content_health_status": string;
"refreshed_at": string;
"summary_status": string;
"last_refreshed_at": string | null;
"stale_after": string | null;
"refresh_error_code": string | null;
"refresh_error_message": string | null;
"refresh_attempts": number;
"source_updated_at": string | null;
};
Insert: {
"binder_id": string;
"owner_id": string;
"title": string;
"subject"?: string;
"status": Database["public"]["Enums"]["publish_status"];
"document_count"?: number;
"preview_document_count"?: number;
"empty_document_count"?: number;
"total_word_count"?: number;
"last_updated_at"?: string;
"content_health_status"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Update: {
"binder_id"?: string;
"owner_id"?: string;
"title"?: string;
"subject"?: string;
"status"?: Database["public"]["Enums"]["publish_status"];
"document_count"?: number;
"preview_document_count"?: number;
"empty_document_count"?: number;
"total_word_count"?: number;
"last_updated_at"?: string;
"content_health_status"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Relationships: [{ foreignKeyName: "admin_binder_summaries_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: true; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "admin_binder_summaries_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"billing_accounts": {
Row: {
"user_id": string;
"customer_id": string;
"lease_token": string | null;
"lease_event_id": string | null;
"lease_expires_at": string | null;
};
Insert: {
"user_id": string;
"customer_id": string;
"lease_token"?: string | null;
"lease_event_id"?: string | null;
"lease_expires_at"?: string | null;
};
Update: {
"user_id"?: string;
"customer_id"?: string;
"lease_token"?: string | null;
"lease_event_id"?: string | null;
"lease_expires_at"?: string | null;
};
Relationships: [{ foreignKeyName: "billing_accounts_user_id_fkey"; columns: ["user_id"]; isOneToOne: true; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"billing_events": {
Row: {
"customer_id": string;
"event_id": string;
"processed_at": string | null;
};
Insert: {
"customer_id": string;
"event_id": string;
"processed_at"?: string | null;
};
Update: {
"customer_id"?: string;
"event_id"?: string;
"processed_at"?: string | null;
};
Relationships: [{ foreignKeyName: "billing_events_customer_id_fkey"; columns: ["customer_id"]; isOneToOne: false; referencedRelation: "billing_accounts"; referencedColumns: ["customer_id"] }];
};
"binder_lessons": {
Row: {
"id": string;
"binder_id": string;
"title": string;
"order_index": number;
"content": Json;
"math_blocks": Json;
"is_preview": boolean;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"binder_id": string;
"title": string;
"order_index"?: number;
"content"?: Json;
"math_blocks"?: Json;
"is_preview"?: boolean;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"binder_id"?: string;
"title"?: string;
"order_index"?: number;
"content"?: Json;
"math_blocks"?: Json;
"is_preview"?: boolean;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "binder_lessons_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] }];
};
"binders": {
Row: {
"id": string;
"owner_id": string;
"title": string;
"slug": string;
"description": string;
"subject": string;
"level": string;
"status": Database["public"]["Enums"]["publish_status"];
"price_cents": number;
"cover_url": string | null;
"pinned": boolean;
"created_at": string;
"updated_at": string;
"suite_template_id": string | null;
"dashboard_sort_order": number | null;
};
Insert: {
"id"?: string;
"owner_id": string;
"title": string;
"slug": string;
"description"?: string;
"subject"?: string;
"level"?: string;
"status"?: Database["public"]["Enums"]["publish_status"];
"price_cents"?: number;
"cover_url"?: string | null;
"pinned"?: boolean;
"created_at"?: string;
"updated_at"?: string;
"suite_template_id"?: string | null;
"dashboard_sort_order"?: number | null;
};
Update: {
"id"?: string;
"owner_id"?: string;
"title"?: string;
"slug"?: string;
"description"?: string;
"subject"?: string;
"level"?: string;
"status"?: Database["public"]["Enums"]["publish_status"];
"price_cents"?: number;
"cover_url"?: string | null;
"pinned"?: boolean;
"created_at"?: string;
"updated_at"?: string;
"suite_template_id"?: string | null;
"dashboard_sort_order"?: number | null;
};
Relationships: [{ foreignKeyName: "binders_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "binders_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
"chem_concepts": {
Row: {
"id": string;
"slug": string;
"title": string;
"description": string;
"parent_id": string | null;
"status": string;
"created_by": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id": string;
"slug": string;
"title": string;
"description"?: string;
"parent_id"?: string | null;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"title"?: string;
"description"?: string;
"parent_id"?: string | null;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "chem_concepts_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "chem_concepts_parent_id_fkey"; columns: ["parent_id"]; isOneToOne: false; referencedRelation: "chem_concepts"; referencedColumns: ["id"] }];
};
"chem_lab_templates": {
Row: {
"id": string;
"concept_id": string | null;
"title": string;
"objective": string;
"safety_notes": (string)[];
"reagents": Json;
"simulation_kind": string;
"default_state": Json;
"status": string;
"created_by": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id": string;
"concept_id"?: string | null;
"title": string;
"objective"?: string;
"safety_notes"?: (string)[];
"reagents"?: Json;
"simulation_kind"?: string;
"default_state"?: Json;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"concept_id"?: string | null;
"title"?: string;
"objective"?: string;
"safety_notes"?: (string)[];
"reagents"?: Json;
"simulation_kind"?: string;
"default_state"?: Json;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "chem_lab_templates_concept_id_fkey"; columns: ["concept_id"]; isOneToOne: false; referencedRelation: "chem_concepts"; referencedColumns: ["id"] },{ foreignKeyName: "chem_lab_templates_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"chem_problem_templates": {
Row: {
"id": string;
"concept_id": string | null;
"title": string;
"prompt": string;
"equation": string;
"given": Json;
"target": Json;
"concept_tags": (string)[];
"expected_answer": Json;
"status": string;
"created_by": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id": string;
"concept_id"?: string | null;
"title": string;
"prompt"?: string;
"equation"?: string;
"given"?: Json;
"target"?: Json;
"concept_tags"?: (string)[];
"expected_answer"?: Json;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"concept_id"?: string | null;
"title"?: string;
"prompt"?: string;
"equation"?: string;
"given"?: Json;
"target"?: Json;
"concept_tags"?: (string)[];
"expected_answer"?: Json;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "chem_problem_templates_concept_id_fkey"; columns: ["concept_id"]; isOneToOne: false; referencedRelation: "chem_concepts"; referencedColumns: ["id"] },{ foreignKeyName: "chem_problem_templates_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"comments": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string;
"anchor_text": string | null;
"body": string;
"parent_id": string | null;
"resolved_at": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id": string;
"anchor_text"?: string | null;
"body": string;
"parent_id"?: string | null;
"resolved_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string;
"anchor_text"?: string | null;
"body"?: string;
"parent_id"?: string | null;
"resolved_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "comments_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "comments_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "comments_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "comments_parent_id_fkey"; columns: ["parent_id"]; isOneToOne: false; referencedRelation: "comments"; referencedColumns: ["id"] }];
};
"concept_edges": {
Row: {
"id": string;
"binder_id": string;
"source_id": string;
"target_id": string;
"label": string | null;
"created_at": string;
};
Insert: {
"id"?: string;
"binder_id": string;
"source_id": string;
"target_id": string;
"label"?: string | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"binder_id"?: string;
"source_id"?: string;
"target_id"?: string;
"label"?: string | null;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "concept_edges_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "concept_edges_source_id_fkey"; columns: ["source_id"]; isOneToOne: false; referencedRelation: "concept_nodes"; referencedColumns: ["id"] },{ foreignKeyName: "concept_edges_target_id_fkey"; columns: ["target_id"]; isOneToOne: false; referencedRelation: "concept_nodes"; referencedColumns: ["id"] }];
};
"concept_nodes": {
Row: {
"id": string;
"binder_id": string;
"label": string;
"description": string | null;
"created_at": string;
};
Insert: {
"id"?: string;
"binder_id": string;
"label": string;
"description"?: string | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"binder_id"?: string;
"label"?: string;
"description"?: string | null;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "concept_nodes_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] }];
};
"dashboard_binder_summaries": {
Row: {
"binder_id": string;
"owner_id": string;
"folder_id": string | null;
"title": string;
"subject": string;
"description_excerpt": string;
"status": Database["public"]["Enums"]["publish_status"];
"cover_url": string | null;
"document_count": number;
"note_count": number;
"last_document_title": string | null;
"updated_at": string;
"refreshed_at": string;
"summary_status": string;
"last_refreshed_at": string | null;
"stale_after": string | null;
"refresh_error_code": string | null;
"refresh_error_message": string | null;
"refresh_attempts": number;
"source_updated_at": string | null;
};
Insert: {
"binder_id": string;
"owner_id": string;
"folder_id"?: string | null;
"title": string;
"subject"?: string;
"description_excerpt"?: string;
"status": Database["public"]["Enums"]["publish_status"];
"cover_url"?: string | null;
"document_count"?: number;
"note_count"?: number;
"last_document_title"?: string | null;
"updated_at"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Update: {
"binder_id"?: string;
"owner_id"?: string;
"folder_id"?: string | null;
"title"?: string;
"subject"?: string;
"description_excerpt"?: string;
"status"?: Database["public"]["Enums"]["publish_status"];
"cover_url"?: string | null;
"document_count"?: number;
"note_count"?: number;
"last_document_title"?: string | null;
"updated_at"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Relationships: [{ foreignKeyName: "dashboard_binder_summaries_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: true; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "dashboard_binder_summaries_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: false; referencedRelation: "folders"; referencedColumns: ["id"] },{ foreignKeyName: "dashboard_binder_summaries_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"dashboard_folder_summaries": {
Row: {
"folder_id": string;
"owner_id": string;
"folder_name": string;
"folder_color": string;
"binder_count": number;
"document_count": number;
"note_count": number;
"updated_at": string;
"refreshed_at": string;
"summary_status": string;
"last_refreshed_at": string | null;
"stale_after": string | null;
"refresh_error_code": string | null;
"refresh_error_message": string | null;
"refresh_attempts": number;
"source_updated_at": string | null;
};
Insert: {
"folder_id": string;
"owner_id": string;
"folder_name": string;
"folder_color"?: string;
"binder_count"?: number;
"document_count"?: number;
"note_count"?: number;
"updated_at"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Update: {
"folder_id"?: string;
"owner_id"?: string;
"folder_name"?: string;
"folder_color"?: string;
"binder_count"?: number;
"document_count"?: number;
"note_count"?: number;
"updated_at"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Relationships: [{ foreignKeyName: "dashboard_folder_summaries_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: true; referencedRelation: "folders"; referencedColumns: ["id"] },{ foreignKeyName: "dashboard_folder_summaries_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"dashboard_lesson_summaries": {
Row: {
"lesson_id": string;
"binder_id": string;
"title": string;
"order_index": number;
"is_preview": boolean;
"plain_text_excerpt": string;
"word_count": number;
"created_at": string;
"updated_at": string;
"refreshed_at": string;
"summary_status": string;
"last_refreshed_at": string | null;
"stale_after": string | null;
"refresh_error_code": string | null;
"refresh_error_message": string | null;
"refresh_attempts": number;
"source_updated_at": string | null;
};
Insert: {
"lesson_id": string;
"binder_id": string;
"title": string;
"order_index"?: number;
"is_preview"?: boolean;
"plain_text_excerpt"?: string;
"word_count"?: number;
"created_at"?: string;
"updated_at"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Update: {
"lesson_id"?: string;
"binder_id"?: string;
"title"?: string;
"order_index"?: number;
"is_preview"?: boolean;
"plain_text_excerpt"?: string;
"word_count"?: number;
"created_at"?: string;
"updated_at"?: string;
"refreshed_at"?: string;
"summary_status"?: string;
"last_refreshed_at"?: string | null;
"stale_after"?: string | null;
"refresh_error_code"?: string | null;
"refresh_error_message"?: string | null;
"refresh_attempts"?: number;
"source_updated_at"?: string | null;
};
Relationships: [{ foreignKeyName: "dashboard_lesson_summaries_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "dashboard_lesson_summaries_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: true; referencedRelation: "binder_lessons"; referencedColumns: ["id"] }];
};
"enrollments": {
Row: {
"id": string;
"user_id": string;
"binder_id": string;
"created_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id": string;
"created_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "enrollments_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "enrollments_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"folder_binders": {
Row: {
"id": string;
"owner_id": string;
"folder_id": string;
"binder_id": string;
"created_at": string;
"updated_at": string;
"sort_order": number | null;
};
Insert: {
"id"?: string;
"owner_id": string;
"folder_id": string;
"binder_id": string;
"created_at"?: string;
"updated_at"?: string;
"sort_order"?: number | null;
};
Update: {
"id"?: string;
"owner_id"?: string;
"folder_id"?: string;
"binder_id"?: string;
"created_at"?: string;
"updated_at"?: string;
"sort_order"?: number | null;
};
Relationships: [{ foreignKeyName: "folder_binders_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "folder_binders_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: false; referencedRelation: "folders"; referencedColumns: ["id"] },{ foreignKeyName: "folder_binders_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"folders": {
Row: {
"id": string;
"owner_id": string;
"name": string;
"color": string;
"created_at": string;
"updated_at": string;
"source": string;
"suite_template_id": string | null;
"sort_order": number | null;
};
Insert: {
"id"?: string;
"owner_id": string;
"name": string;
"color"?: string;
"created_at"?: string;
"updated_at"?: string;
"source"?: string;
"suite_template_id"?: string | null;
"sort_order"?: number | null;
};
Update: {
"id"?: string;
"owner_id"?: string;
"name"?: string;
"color"?: string;
"created_at"?: string;
"updated_at"?: string;
"source"?: string;
"suite_template_id"?: string | null;
"sort_order"?: number | null;
};
Relationships: [{ foreignKeyName: "folders_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "folders_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
"highlights": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string;
"anchor_text": string;
"color": string;
"note_id": string | null;
"start_offset": number | null;
"end_offset": number | null;
"created_at": string;
"document_id": string | null;
"source_version_id": string | null;
"selected_text": string | null;
"prefix_text": string | null;
"suffix_text": string | null;
"selector_json": Json | null;
"status": string;
"reanchor_confidence": number | null;
"updated_at": string;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id": string;
"anchor_text": string;
"color"?: string;
"note_id"?: string | null;
"start_offset"?: number | null;
"end_offset"?: number | null;
"created_at"?: string;
"document_id"?: string | null;
"source_version_id"?: string | null;
"selected_text"?: string | null;
"prefix_text"?: string | null;
"suffix_text"?: string | null;
"selector_json"?: Json | null;
"status"?: string;
"reanchor_confidence"?: number | null;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string;
"anchor_text"?: string;
"color"?: string;
"note_id"?: string | null;
"start_offset"?: number | null;
"end_offset"?: number | null;
"created_at"?: string;
"document_id"?: string | null;
"source_version_id"?: string | null;
"selected_text"?: string | null;
"prefix_text"?: string | null;
"suffix_text"?: string | null;
"selector_json"?: Json | null;
"status"?: string;
"reanchor_confidence"?: number | null;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "highlights_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "highlights_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "highlights_note_id_fkey"; columns: ["note_id"]; isOneToOne: false; referencedRelation: "learner_notes"; referencedColumns: ["id"] },{ foreignKeyName: "highlights_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"history_argument_chains": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string | null;
"prompt": string;
"thesis": string;
"context": string;
"counterargument": string;
"conclusion": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"prompt"?: string;
"thesis"?: string;
"context"?: string;
"counterargument"?: string;
"conclusion"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"prompt"?: string;
"thesis"?: string;
"context"?: string;
"counterargument"?: string;
"conclusion"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_argument_chains_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_chains_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_chains_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"history_argument_edges": {
Row: {
"id": string;
"chain_id": string;
"owner_id": string;
"from_node_id": string;
"to_node_id": string;
"relation_type": string;
"strength": number;
"explanation": string;
"source_id": string | null;
"evidence_id": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"chain_id": string;
"owner_id": string;
"from_node_id": string;
"to_node_id": string;
"relation_type": string;
"strength"?: number;
"explanation"?: string;
"source_id"?: string | null;
"evidence_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"chain_id"?: string;
"owner_id"?: string;
"from_node_id"?: string;
"to_node_id"?: string;
"relation_type"?: string;
"strength"?: number;
"explanation"?: string;
"source_id"?: string | null;
"evidence_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_argument_edges_chain_id_fkey"; columns: ["chain_id"]; isOneToOne: false; referencedRelation: "history_argument_chains"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_edges_evidence_id_fkey"; columns: ["evidence_id"]; isOneToOne: false; referencedRelation: "history_evidence_cards"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_edges_from_node_id_fkey"; columns: ["from_node_id"]; isOneToOne: false; referencedRelation: "history_argument_nodes"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_edges_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_edges_source_id_fkey"; columns: ["source_id"]; isOneToOne: false; referencedRelation: "history_sources"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_edges_to_node_id_fkey"; columns: ["to_node_id"]; isOneToOne: false; referencedRelation: "history_argument_nodes"; referencedColumns: ["id"] }];
};
"history_argument_nodes": {
Row: {
"id": string;
"chain_id": string;
"owner_id": string;
"node_type": string;
"title": string;
"body": string;
"sort_order": number;
"event_id": string | null;
"source_id": string | null;
"evidence_id": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"chain_id": string;
"owner_id": string;
"node_type": string;
"title"?: string;
"body"?: string;
"sort_order"?: number;
"event_id"?: string | null;
"source_id"?: string | null;
"evidence_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"chain_id"?: string;
"owner_id"?: string;
"node_type"?: string;
"title"?: string;
"body"?: string;
"sort_order"?: number;
"event_id"?: string | null;
"source_id"?: string | null;
"evidence_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_argument_nodes_chain_id_fkey"; columns: ["chain_id"]; isOneToOne: false; referencedRelation: "history_argument_chains"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_nodes_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "history_events"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_nodes_evidence_id_fkey"; columns: ["evidence_id"]; isOneToOne: false; referencedRelation: "history_evidence_cards"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_nodes_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "history_argument_nodes_source_id_fkey"; columns: ["source_id"]; isOneToOne: false; referencedRelation: "history_sources"; referencedColumns: ["id"] }];
};
"history_event_templates": {
Row: {
"id": string;
"suite_template_id": string;
"binder_id": string;
"lesson_id": string | null;
"title": string;
"summary": string;
"significance": string;
"location_label": string | null;
"location_lat": number | null;
"location_lng": number | null;
"date_label": string;
"sort_year": number;
"sort_month": number | null;
"sort_day": number | null;
"era": string;
"precision": string;
"approximate": boolean;
"themes": (string)[];
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"suite_template_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"title": string;
"summary"?: string;
"significance"?: string;
"location_label"?: string | null;
"location_lat"?: number | null;
"location_lng"?: number | null;
"date_label": string;
"sort_year": number;
"sort_month"?: number | null;
"sort_day"?: number | null;
"era"?: string;
"precision"?: string;
"approximate"?: boolean;
"themes"?: (string)[];
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"suite_template_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"title"?: string;
"summary"?: string;
"significance"?: string;
"location_label"?: string | null;
"location_lat"?: number | null;
"location_lng"?: number | null;
"date_label"?: string;
"sort_year"?: number;
"sort_month"?: number | null;
"sort_day"?: number | null;
"era"?: string;
"precision"?: string;
"approximate"?: boolean;
"themes"?: (string)[];
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_event_templates_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_event_templates_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_event_templates_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
"history_events": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string | null;
"template_event_id": string | null;
"title": string;
"summary": string;
"significance": string;
"location_label": string | null;
"location_lat": number | null;
"location_lng": number | null;
"date_label": string;
"sort_year": number;
"sort_month": number | null;
"sort_day": number | null;
"era": string;
"precision": string;
"approximate": boolean;
"themes": (string)[];
"status": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"template_event_id"?: string | null;
"title": string;
"summary"?: string;
"significance"?: string;
"location_label"?: string | null;
"location_lat"?: number | null;
"location_lng"?: number | null;
"date_label": string;
"sort_year": number;
"sort_month"?: number | null;
"sort_day"?: number | null;
"era"?: string;
"precision"?: string;
"approximate"?: boolean;
"themes"?: (string)[];
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"template_event_id"?: string | null;
"title"?: string;
"summary"?: string;
"significance"?: string;
"location_label"?: string | null;
"location_lat"?: number | null;
"location_lng"?: number | null;
"date_label"?: string;
"sort_year"?: number;
"sort_month"?: number | null;
"sort_day"?: number | null;
"era"?: string;
"precision"?: string;
"approximate"?: boolean;
"themes"?: (string)[];
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_events_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_events_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_events_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "history_events_template_event_id_fkey"; columns: ["template_event_id"]; isOneToOne: false; referencedRelation: "history_event_templates"; referencedColumns: ["id"] }];
};
"history_evidence_cards": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string | null;
"source_id": string | null;
"highlight_id": string | null;
"quote_text": string | null;
"paraphrase": string | null;
"claim_supports": string | null;
"claim_challenges": string | null;
"evidence_strength": string;
"source_snapshot_json": Json | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"source_id"?: string | null;
"highlight_id"?: string | null;
"quote_text"?: string | null;
"paraphrase"?: string | null;
"claim_supports"?: string | null;
"claim_challenges"?: string | null;
"evidence_strength"?: string;
"source_snapshot_json"?: Json | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"source_id"?: string | null;
"highlight_id"?: string | null;
"quote_text"?: string | null;
"paraphrase"?: string | null;
"claim_supports"?: string | null;
"claim_challenges"?: string | null;
"evidence_strength"?: string;
"source_snapshot_json"?: Json | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_evidence_cards_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_evidence_cards_highlight_id_fkey"; columns: ["highlight_id"]; isOneToOne: false; referencedRelation: "highlights"; referencedColumns: ["id"] },{ foreignKeyName: "history_evidence_cards_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_evidence_cards_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "history_evidence_cards_source_id_fkey"; columns: ["source_id"]; isOneToOne: false; referencedRelation: "history_sources"; referencedColumns: ["id"] }];
};
"history_myth_check_templates": {
Row: {
"id": string;
"suite_template_id": string;
"binder_id": string;
"lesson_id": string | null;
"myth_text": string;
"corrected_claim": string;
"status": string;
"explanation": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"suite_template_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"myth_text": string;
"corrected_claim": string;
"status": string;
"explanation"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"suite_template_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"myth_text"?: string;
"corrected_claim"?: string;
"status"?: string;
"explanation"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_myth_check_templates_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_myth_check_templates_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_myth_check_templates_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
"history_myth_checks": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string | null;
"template_myth_check_id": string | null;
"myth_text": string;
"corrected_claim": string;
"status": string;
"explanation": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"template_myth_check_id"?: string | null;
"myth_text": string;
"corrected_claim": string;
"status": string;
"explanation"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"template_myth_check_id"?: string | null;
"myth_text"?: string;
"corrected_claim"?: string;
"status"?: string;
"explanation"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_myth_checks_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_myth_checks_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_myth_checks_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "history_myth_checks_template_myth_check_id_fkey"; columns: ["template_myth_check_id"]; isOneToOne: false; referencedRelation: "history_myth_check_templates"; referencedColumns: ["id"] }];
};
"history_source_templates": {
Row: {
"id": string;
"suite_template_id": string;
"binder_id": string;
"lesson_id": string | null;
"title": string;
"source_type": string;
"author": string | null;
"date_label": string;
"audience": string | null;
"purpose": string | null;
"point_of_view": string | null;
"context_note": string | null;
"reliability_note": string | null;
"citation_url": string | null;
"quote_text": string | null;
"claim_supports": string | null;
"claim_challenges": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"suite_template_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"title": string;
"source_type": string;
"author"?: string | null;
"date_label": string;
"audience"?: string | null;
"purpose"?: string | null;
"point_of_view"?: string | null;
"context_note"?: string | null;
"reliability_note"?: string | null;
"citation_url"?: string | null;
"quote_text"?: string | null;
"claim_supports"?: string | null;
"claim_challenges"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"suite_template_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"title"?: string;
"source_type"?: string;
"author"?: string | null;
"date_label"?: string;
"audience"?: string | null;
"purpose"?: string | null;
"point_of_view"?: string | null;
"context_note"?: string | null;
"reliability_note"?: string | null;
"citation_url"?: string | null;
"quote_text"?: string | null;
"claim_supports"?: string | null;
"claim_challenges"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "history_source_templates_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_source_templates_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_source_templates_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
"history_sources": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string | null;
"template_source_id": string | null;
"title": string;
"source_type": string;
"author": string | null;
"date_label": string;
"audience": string | null;
"purpose": string | null;
"point_of_view": string | null;
"context_note": string | null;
"reliability_note": string | null;
"citation_url": string | null;
"created_at": string;
"updated_at": string;
"quote_text": string | null;
"claim_supports": string | null;
"claim_challenges": string | null;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id"?: string | null;
"template_source_id"?: string | null;
"title": string;
"source_type": string;
"author"?: string | null;
"date_label": string;
"audience"?: string | null;
"purpose"?: string | null;
"point_of_view"?: string | null;
"context_note"?: string | null;
"reliability_note"?: string | null;
"citation_url"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"quote_text"?: string | null;
"claim_supports"?: string | null;
"claim_challenges"?: string | null;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string | null;
"template_source_id"?: string | null;
"title"?: string;
"source_type"?: string;
"author"?: string | null;
"date_label"?: string;
"audience"?: string | null;
"purpose"?: string | null;
"point_of_view"?: string | null;
"context_note"?: string | null;
"reliability_note"?: string | null;
"citation_url"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"quote_text"?: string | null;
"claim_supports"?: string | null;
"claim_challenges"?: string | null;
};
Relationships: [{ foreignKeyName: "history_sources_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "history_sources_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "history_sources_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "history_sources_template_source_id_fkey"; columns: ["template_source_id"]; isOneToOne: false; referencedRelation: "history_source_templates"; referencedColumns: ["id"] }];
};
"learner_notes": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"lesson_id": string;
"folder_id": string | null;
"title": string;
"content": Json;
"math_blocks": Json;
"pinned": boolean;
"created_at": string;
"updated_at": string;
"revision": number;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"lesson_id": string;
"folder_id"?: string | null;
"title"?: string;
"content"?: Json;
"math_blocks"?: Json;
"pinned"?: boolean;
"created_at"?: string;
"updated_at"?: string;
"revision"?: number;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"lesson_id"?: string;
"folder_id"?: string | null;
"title"?: string;
"content"?: Json;
"math_blocks"?: Json;
"pinned"?: boolean;
"created_at"?: string;
"updated_at"?: string;
"revision"?: number;
};
Relationships: [{ foreignKeyName: "learner_notes_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "learner_notes_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: false; referencedRelation: "folders"; referencedColumns: ["id"] },{ foreignKeyName: "learner_notes_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "learner_notes_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"math_courses": {
Row: {
"id": string;
"slug": string;
"title": string;
"description": string | null;
"order_index": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"slug": string;
"title": string;
"description"?: string | null;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"title"?: string;
"description"?: string | null;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"math_graph_states": {
Row: {
"id": string;
"user_id": string | null;
"module_id": string | null;
"note_id": string | null;
"calculator_mode": string;
"title": string;
"desmos_state": Json;
"expressions": Json | null;
"thumbnail_url": string | null;
"created_at": string;
"updated_at": string;
"question_id": string | null;
};
Insert: {
"id"?: string;
"user_id"?: string | null;
"module_id"?: string | null;
"note_id"?: string | null;
"calculator_mode": string;
"title": string;
"desmos_state": Json;
"expressions"?: Json | null;
"thumbnail_url"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"question_id"?: string | null;
};
Update: {
"id"?: string;
"user_id"?: string | null;
"module_id"?: string | null;
"note_id"?: string | null;
"calculator_mode"?: string;
"title"?: string;
"desmos_state"?: Json;
"expressions"?: Json | null;
"thumbnail_url"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"question_id"?: string | null;
};
Relationships: [{ foreignKeyName: "math_graph_states_module_id_fkey"; columns: ["module_id"]; isOneToOne: false; referencedRelation: "math_modules"; referencedColumns: ["id"] },{ foreignKeyName: "math_graph_states_note_id_fkey"; columns: ["note_id"]; isOneToOne: false; referencedRelation: "learner_notes"; referencedColumns: ["id"] },{ foreignKeyName: "math_graph_states_question_id_fkey"; columns: ["question_id"]; isOneToOne: false; referencedRelation: "question_bank"; referencedColumns: ["id"] },{ foreignKeyName: "math_graph_states_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"math_modules": {
Row: {
"id": string;
"course_id": string;
"topic_id": string | null;
"slug": string;
"title": string;
"description": string | null;
"difficulty": string;
"calculator_mode": string;
"module_json": Json;
"visibility": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"course_id": string;
"topic_id"?: string | null;
"slug": string;
"title": string;
"description"?: string | null;
"difficulty"?: string;
"calculator_mode"?: string;
"module_json"?: Json;
"visibility"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"course_id"?: string;
"topic_id"?: string | null;
"slug"?: string;
"title"?: string;
"description"?: string | null;
"difficulty"?: string;
"calculator_mode"?: string;
"module_json"?: Json;
"visibility"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "math_modules_course_id_fkey"; columns: ["course_id"]; isOneToOne: false; referencedRelation: "math_courses"; referencedColumns: ["id"] },{ foreignKeyName: "math_modules_topic_id_fkey"; columns: ["topic_id"]; isOneToOne: false; referencedRelation: "math_topics"; referencedColumns: ["id"] }];
};
"math_topics": {
Row: {
"id": string;
"course_id": string;
"parent_topic_id": string | null;
"slug": string;
"title": string;
"description": string | null;
"order_index": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"course_id": string;
"parent_topic_id"?: string | null;
"slug": string;
"title": string;
"description"?: string | null;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"course_id"?: string;
"parent_topic_id"?: string | null;
"slug"?: string;
"title"?: string;
"description"?: string | null;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "math_topics_course_id_fkey"; columns: ["course_id"]; isOneToOne: false; referencedRelation: "math_courses"; referencedColumns: ["id"] },{ foreignKeyName: "math_topics_parent_topic_id_fkey"; columns: ["parent_topic_id"]; isOneToOne: false; referencedRelation: "math_topics"; referencedColumns: ["id"] }];
};
"personal_note_binders": {
Row: {
"id": string;
"owner_id": string;
"folder_id": string | null;
"title": string;
"description": string | null;
"color": string | null;
"pinned": boolean;
"sort_order": number | null;
"created_at": string;
"updated_at": string;
"archived_at": string | null;
};
Insert: {
"id"?: string;
"owner_id": string;
"folder_id"?: string | null;
"title": string;
"description"?: string | null;
"color"?: string | null;
"pinned"?: boolean;
"sort_order"?: number | null;
"created_at"?: string;
"updated_at"?: string;
"archived_at"?: string | null;
};
Update: {
"id"?: string;
"owner_id"?: string;
"folder_id"?: string | null;
"title"?: string;
"description"?: string | null;
"color"?: string | null;
"pinned"?: boolean;
"sort_order"?: number | null;
"created_at"?: string;
"updated_at"?: string;
"archived_at"?: string | null;
};
Relationships: [{ foreignKeyName: "personal_note_binders_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: false; referencedRelation: "personal_note_folders"; referencedColumns: ["id"] },{ foreignKeyName: "personal_note_binders_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"personal_note_documents": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string;
"title": string;
"content": Json;
"math_blocks": Json;
"tags": (string)[];
"pinned": boolean;
"archived_at": string | null;
"created_at": string;
"updated_at": string;
"revision": number;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id": string;
"title": string;
"content"?: Json;
"math_blocks"?: Json;
"tags"?: (string)[];
"pinned"?: boolean;
"archived_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"revision"?: number;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string;
"title"?: string;
"content"?: Json;
"math_blocks"?: Json;
"tags"?: (string)[];
"pinned"?: boolean;
"archived_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"revision"?: number;
};
Relationships: [{ foreignKeyName: "personal_note_documents_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "personal_note_binders"; referencedColumns: ["id"] },{ foreignKeyName: "personal_note_documents_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"personal_note_folders": {
Row: {
"id": string;
"owner_id": string;
"name": string;
"color": string;
"sort_order": number | null;
"created_at": string;
"updated_at": string;
"archived_at": string | null;
};
Insert: {
"id"?: string;
"owner_id": string;
"name": string;
"color"?: string;
"sort_order"?: number | null;
"created_at"?: string;
"updated_at"?: string;
"archived_at"?: string | null;
};
Update: {
"id"?: string;
"owner_id"?: string;
"name"?: string;
"color"?: string;
"sort_order"?: number | null;
"created_at"?: string;
"updated_at"?: string;
"archived_at"?: string | null;
};
Relationships: [{ foreignKeyName: "personal_note_folders_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"personal_notes": {
Row: {
"id": string;
"owner_id": string;
"folder_id": string | null;
"binder_id": string | null;
"document_id": string | null;
"title": string;
"content": Json;
"math_blocks": Json;
"tags": (string)[];
"pinned": boolean;
"archived_at": string | null;
"created_at": string;
"updated_at": string;
"revision": number;
};
Insert: {
"id"?: string;
"owner_id": string;
"folder_id"?: string | null;
"binder_id"?: string | null;
"document_id"?: string | null;
"title": string;
"content"?: Json;
"math_blocks"?: Json;
"tags"?: (string)[];
"pinned"?: boolean;
"archived_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"revision"?: number;
};
Update: {
"id"?: string;
"owner_id"?: string;
"folder_id"?: string | null;
"binder_id"?: string | null;
"document_id"?: string | null;
"title"?: string;
"content"?: Json;
"math_blocks"?: Json;
"tags"?: (string)[];
"pinned"?: boolean;
"archived_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"revision"?: number;
};
Relationships: [{ foreignKeyName: "personal_notes_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "personal_note_binders"; referencedColumns: ["id"] },{ foreignKeyName: "personal_notes_document_id_fkey"; columns: ["document_id"]; isOneToOne: false; referencedRelation: "personal_note_documents"; referencedColumns: ["id"] },{ foreignKeyName: "personal_notes_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: false; referencedRelation: "personal_note_folders"; referencedColumns: ["id"] },{ foreignKeyName: "personal_notes_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"profiles": {
Row: {
"id": string;
"email": string;
"full_name": string;
"role": Database["public"]["Enums"]["app_role"];
"created_at": string;
"updated_at": string;
"appearance_settings": Json | null;
};
Insert: {
"id": string;
"email": string;
"full_name"?: string;
"role"?: Database["public"]["Enums"]["app_role"];
"created_at"?: string;
"updated_at"?: string;
"appearance_settings"?: Json | null;
};
Update: {
"id"?: string;
"email"?: string;
"full_name"?: string;
"role"?: Database["public"]["Enums"]["app_role"];
"created_at"?: string;
"updated_at"?: string;
"appearance_settings"?: Json | null;
};
Relationships: [{ foreignKeyName: "profiles_id_fkey"; columns: ["id"]; isOneToOne: true; referencedRelation: "users"; referencedColumns: ["id"] }];
};
"purchases": {
Row: {
"id": string;
"user_id": string;
"binder_id": string | null;
"stripe_checkout_session_id": string | null;
"stripe_customer_id": string | null;
"amount_cents": number;
"status": Database["public"]["Enums"]["purchase_status"];
"created_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id"?: string | null;
"stripe_checkout_session_id"?: string | null;
"stripe_customer_id"?: string | null;
"amount_cents"?: number;
"status"?: Database["public"]["Enums"]["purchase_status"];
"created_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string | null;
"stripe_checkout_session_id"?: string | null;
"stripe_customer_id"?: string | null;
"amount_cents"?: number;
"status"?: Database["public"]["Enums"]["purchase_status"];
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "purchases_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "purchases_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"question_attempts": {
Row: {
"id": string;
"quiz_attempt_id": string;
"question_id": string;
"user_id": string | null;
"submitted_answer_json": Json;
"is_correct": boolean | null;
"points_awarded": number | null;
"feedback_json": Json | null;
"created_at": string;
};
Insert: {
"id"?: string;
"quiz_attempt_id": string;
"question_id": string;
"user_id"?: string | null;
"submitted_answer_json"?: Json;
"is_correct"?: boolean | null;
"points_awarded"?: number | null;
"feedback_json"?: Json | null;
"created_at"?: string;
};
Update: {
"id"?: string;
"quiz_attempt_id"?: string;
"question_id"?: string;
"user_id"?: string | null;
"submitted_answer_json"?: Json;
"is_correct"?: boolean | null;
"points_awarded"?: number | null;
"feedback_json"?: Json | null;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "question_attempts_question_id_fkey"; columns: ["question_id"]; isOneToOne: false; referencedRelation: "question_bank"; referencedColumns: ["id"] },{ foreignKeyName: "question_attempts_quiz_attempt_id_fkey"; columns: ["quiz_attempt_id"]; isOneToOne: false; referencedRelation: "quiz_attempts"; referencedColumns: ["id"] },{ foreignKeyName: "question_attempts_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"question_bank": {
Row: {
"id": string;
"course_id": string | null;
"topic_id": string | null;
"module_id": string | null;
"note_id": string | null;
"graph_state_id": string | null;
"type": string;
"title": string | null;
"prompt_markdown": string;
"prompt_latex": string | null;
"answer_json": Json;
"explanation_markdown": string | null;
"explanation_latex": string | null;
"difficulty": string;
"calculator_allowed": boolean;
"estimated_time_seconds": number | null;
"source_type": string;
"status": string;
"created_by": string | null;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"course_id"?: string | null;
"topic_id"?: string | null;
"module_id"?: string | null;
"note_id"?: string | null;
"graph_state_id"?: string | null;
"type": string;
"title"?: string | null;
"prompt_markdown": string;
"prompt_latex"?: string | null;
"answer_json"?: Json;
"explanation_markdown"?: string | null;
"explanation_latex"?: string | null;
"difficulty"?: string;
"calculator_allowed"?: boolean;
"estimated_time_seconds"?: number | null;
"source_type"?: string;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"course_id"?: string | null;
"topic_id"?: string | null;
"module_id"?: string | null;
"note_id"?: string | null;
"graph_state_id"?: string | null;
"type"?: string;
"title"?: string | null;
"prompt_markdown"?: string;
"prompt_latex"?: string | null;
"answer_json"?: Json;
"explanation_markdown"?: string | null;
"explanation_latex"?: string | null;
"difficulty"?: string;
"calculator_allowed"?: boolean;
"estimated_time_seconds"?: number | null;
"source_type"?: string;
"status"?: string;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "question_bank_course_id_fkey"; columns: ["course_id"]; isOneToOne: false; referencedRelation: "math_courses"; referencedColumns: ["id"] },{ foreignKeyName: "question_bank_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "question_bank_graph_state_id_fkey"; columns: ["graph_state_id"]; isOneToOne: false; referencedRelation: "math_graph_states"; referencedColumns: ["id"] },{ foreignKeyName: "question_bank_module_id_fkey"; columns: ["module_id"]; isOneToOne: false; referencedRelation: "math_modules"; referencedColumns: ["id"] },{ foreignKeyName: "question_bank_note_id_fkey"; columns: ["note_id"]; isOneToOne: false; referencedRelation: "learner_notes"; referencedColumns: ["id"] },{ foreignKeyName: "question_bank_topic_id_fkey"; columns: ["topic_id"]; isOneToOne: false; referencedRelation: "math_topics"; referencedColumns: ["id"] }];
};
"question_choices": {
Row: {
"id": string;
"question_id": string;
"choice_text": string;
"choice_latex": string | null;
"is_correct": boolean;
"order_index": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"question_id": string;
"choice_text": string;
"choice_latex"?: string | null;
"is_correct"?: boolean;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"question_id"?: string;
"choice_text"?: string;
"choice_latex"?: string | null;
"is_correct"?: boolean;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "question_choices_question_id_fkey"; columns: ["question_id"]; isOneToOne: false; referencedRelation: "question_bank"; referencedColumns: ["id"] }];
};
"quiz_attempts": {
Row: {
"id": string;
"quiz_set_id": string;
"user_id": string | null;
"started_at": string;
"completed_at": string | null;
"score": number | null;
"total_points": number | null;
"metadata_json": Json | null;
};
Insert: {
"id"?: string;
"quiz_set_id": string;
"user_id"?: string | null;
"started_at"?: string;
"completed_at"?: string | null;
"score"?: number | null;
"total_points"?: number | null;
"metadata_json"?: Json | null;
};
Update: {
"id"?: string;
"quiz_set_id"?: string;
"user_id"?: string | null;
"started_at"?: string;
"completed_at"?: string | null;
"score"?: number | null;
"total_points"?: number | null;
"metadata_json"?: Json | null;
};
Relationships: [{ foreignKeyName: "quiz_attempts_quiz_set_id_fkey"; columns: ["quiz_set_id"]; isOneToOne: false; referencedRelation: "quiz_sets"; referencedColumns: ["id"] },{ foreignKeyName: "quiz_attempts_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"quiz_set_questions": {
Row: {
"id": string;
"quiz_set_id": string;
"question_id": string;
"order_index": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"quiz_set_id": string;
"question_id": string;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"quiz_set_id"?: string;
"question_id"?: string;
"order_index"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "quiz_set_questions_question_id_fkey"; columns: ["question_id"]; isOneToOne: false; referencedRelation: "question_bank"; referencedColumns: ["id"] },{ foreignKeyName: "quiz_set_questions_quiz_set_id_fkey"; columns: ["quiz_set_id"]; isOneToOne: false; referencedRelation: "quiz_sets"; referencedColumns: ["id"] }];
};
"quiz_sets": {
Row: {
"id": string;
"user_id": string | null;
"course_id": string | null;
"topic_id": string | null;
"module_id": string | null;
"title": string;
"description": string | null;
"settings_json": Json;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id"?: string | null;
"course_id"?: string | null;
"topic_id"?: string | null;
"module_id"?: string | null;
"title": string;
"description"?: string | null;
"settings_json"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string | null;
"course_id"?: string | null;
"topic_id"?: string | null;
"module_id"?: string | null;
"title"?: string;
"description"?: string | null;
"settings_json"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "quiz_sets_course_id_fkey"; columns: ["course_id"]; isOneToOne: false; referencedRelation: "math_courses"; referencedColumns: ["id"] },{ foreignKeyName: "quiz_sets_module_id_fkey"; columns: ["module_id"]; isOneToOne: false; referencedRelation: "math_modules"; referencedColumns: ["id"] },{ foreignKeyName: "quiz_sets_topic_id_fkey"; columns: ["topic_id"]; isOneToOne: false; referencedRelation: "math_topics"; referencedColumns: ["id"] },{ foreignKeyName: "quiz_sets_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"review_events": {
Row: {
"owner_id": string;
"id": string;
"item_id": string;
"payload": Json;
"created_at": string;
};
Insert: {
"owner_id": string;
"id": string;
"item_id": string;
"payload": Json;
"created_at"?: string;
};
Update: {
"owner_id"?: string;
"id"?: string;
"item_id"?: string;
"payload"?: Json;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "review_events_owner_id_item_id_fkey"; columns: ["owner_id","item_id"]; isOneToOne: false; referencedRelation: "review_items"; referencedColumns: ["owner_id","id"] }];
};
"review_items": {
Row: {
"owner_id": string;
"id": string;
"payload": Json;
"revision": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"owner_id": string;
"id": string;
"payload": Json;
"revision"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"owner_id"?: string;
"id"?: string;
"payload"?: Json;
"revision"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "review_items_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"review_sessions": {
Row: {
"owner_id": string;
"id": string;
"payload": Json;
"created_at": string;
};
Insert: {
"owner_id": string;
"id": string;
"payload": Json;
"created_at"?: string;
};
Update: {
"owner_id"?: string;
"id"?: string;
"payload"?: Json;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "review_sessions_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"seed_versions": {
Row: {
"id": string;
"suite_template_id": string;
"version": string;
"checksum": string;
"seeded_at": string;
"created_by": string | null;
"status": string;
};
Insert: {
"id"?: string;
"suite_template_id": string;
"version": string;
"checksum": string;
"seeded_at"?: string;
"created_by"?: string | null;
"status"?: string;
};
Update: {
"id"?: string;
"suite_template_id"?: string;
"version"?: string;
"checksum"?: string;
"seeded_at"?: string;
"created_by"?: string | null;
"status"?: string;
};
Relationships: [{ foreignKeyName: "seed_versions_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "seed_versions_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
"study_sessions": {
Row: {
"id": string;
"user_id": string;
"binder_id": string | null;
"lesson_id": string | null;
"started_at": string;
"ended_at": string | null;
"duration_seconds": number | null;
"source": string | null;
"metadata": Json;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"started_at"?: string;
"ended_at"?: string | null;
"duration_seconds"?: number | null;
"source"?: string | null;
"metadata"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"started_at"?: string;
"ended_at"?: string | null;
"duration_seconds"?: number | null;
"source"?: string | null;
"metadata"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "study_sessions_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "study_sessions_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "study_sessions_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"suite_templates": {
Row: {
"id": string;
"slug": string;
"title": string;
"subject": string;
"description": string;
"folder_title": string;
"history_mode": boolean;
"default_preset_id": string;
"status": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"slug": string;
"title": string;
"subject": string;
"description"?: string;
"folder_title": string;
"history_mode"?: boolean;
"default_preset_id": string;
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"slug"?: string;
"title"?: string;
"subject"?: string;
"description"?: string;
"folder_title"?: string;
"history_mode"?: boolean;
"default_preset_id"?: string;
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"summary_refresh_job_dedupe": {
Row: {
"dedupe_key": string;
"job_type": string;
"entity_type": string;
"entity_id": string | null;
"owner_id": string | null;
"payload": Json;
"priority": number;
"status": string;
"attempts": number;
"created_at": string;
"updated_at": string;
};
Insert: {
"dedupe_key": string;
"job_type": string;
"entity_type": string;
"entity_id"?: string | null;
"owner_id"?: string | null;
"payload"?: Json;
"priority"?: number;
"status"?: string;
"attempts"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"dedupe_key"?: string;
"job_type"?: string;
"entity_type"?: string;
"entity_id"?: string | null;
"owner_id"?: string | null;
"payload"?: Json;
"priority"?: number;
"status"?: string;
"attempts"?: number;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [];
};
"tutorial_entries": {
Row: {
"id": string;
"slug": string;
"title": string;
"audience": string;
"category": string;
"route_patterns": (string)[];
"prompt_route_patterns": (string)[];
"tags": (string)[];
"summary": string;
"duration_seconds": number;
"video_url": string;
"poster_url": string;
"steps": (string)[];
"transcript": string;
"related_feature_link": string;
"storage_path": string | null;
"poster_storage_path": string | null;
"status": string;
"sort_order": number;
"created_by": string | null;
"updated_by": string | null;
"created_at": string;
"updated_at": string;
"published_at": string | null;
};
Insert: {
"id": string;
"slug": string;
"title": string;
"audience"?: string;
"category": string;
"route_patterns"?: (string)[];
"prompt_route_patterns"?: (string)[];
"tags"?: (string)[];
"summary"?: string;
"duration_seconds"?: number;
"video_url"?: string;
"poster_url"?: string;
"steps"?: (string)[];
"transcript"?: string;
"related_feature_link"?: string;
"storage_path"?: string | null;
"poster_storage_path"?: string | null;
"status"?: string;
"sort_order"?: number;
"created_by"?: string | null;
"updated_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"published_at"?: string | null;
};
Update: {
"id"?: string;
"slug"?: string;
"title"?: string;
"audience"?: string;
"category"?: string;
"route_patterns"?: (string)[];
"prompt_route_patterns"?: (string)[];
"tags"?: (string)[];
"summary"?: string;
"duration_seconds"?: number;
"video_url"?: string;
"poster_url"?: string;
"steps"?: (string)[];
"transcript"?: string;
"related_feature_link"?: string;
"storage_path"?: string | null;
"poster_storage_path"?: string | null;
"status"?: string;
"sort_order"?: number;
"created_by"?: string | null;
"updated_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"published_at"?: string | null;
};
Relationships: [{ foreignKeyName: "tutorial_entries_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "tutorial_entries_updated_by_fkey"; columns: ["updated_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"tutorial_video_summaries": {
Row: {
"video_id": string;
"title": string;
"description_excerpt": string;
"thumbnail_url": string;
"duration_seconds": number;
"status": string;
"updated_at": string;
"refreshed_at": string;
};
Insert: {
"video_id": string;
"title": string;
"description_excerpt"?: string;
"thumbnail_url"?: string;
"duration_seconds"?: number;
"status"?: string;
"updated_at"?: string;
"refreshed_at"?: string;
};
Update: {
"video_id"?: string;
"title"?: string;
"description_excerpt"?: string;
"thumbnail_url"?: string;
"duration_seconds"?: number;
"status"?: string;
"updated_at"?: string;
"refreshed_at"?: string;
};
Relationships: [{ foreignKeyName: "tutorial_video_summaries_video_id_fkey"; columns: ["video_id"]; isOneToOne: true; referencedRelation: "tutorial_entries"; referencedColumns: ["id"] }];
};
"user_assets": {
Row: {
"id": string;
"owner_id": string;
"bucket_id": string;
"storage_path": string;
"name": string;
"mime_type": string;
"size_bytes": number;
"sha256": string;
"import_batch_id": string | null;
"status": string;
"created_at": string;
"updated_at": string;
};
Insert: {
"id": string;
"owner_id": string;
"bucket_id"?: string;
"storage_path": string;
"name": string;
"mime_type": string;
"size_bytes": number;
"sha256": string;
"import_batch_id"?: string | null;
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"owner_id"?: string;
"bucket_id"?: string;
"storage_path"?: string;
"name"?: string;
"mime_type"?: string;
"size_bytes"?: number;
"sha256"?: string;
"import_batch_id"?: string | null;
"status"?: string;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "user_assets_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"user_chem_attempts": {
Row: {
"id": string;
"user_id": string;
"binder_id": string | null;
"lesson_id": string | null;
"concept_id": string | null;
"problem_template_id": string | null;
"final_answer": Json;
"step_summaries": Json;
"mistake_tags": (string)[];
"concept_tags": (string)[];
"score": number | null;
"metadata": Json;
"created_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"concept_id"?: string | null;
"problem_template_id"?: string | null;
"final_answer"?: Json;
"step_summaries"?: Json;
"mistake_tags"?: (string)[];
"concept_tags"?: (string)[];
"score"?: number | null;
"metadata"?: Json;
"created_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"concept_id"?: string | null;
"problem_template_id"?: string | null;
"final_answer"?: Json;
"step_summaries"?: Json;
"mistake_tags"?: (string)[];
"concept_tags"?: (string)[];
"score"?: number | null;
"metadata"?: Json;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "user_chem_attempts_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "user_chem_attempts_concept_id_fkey"; columns: ["concept_id"]; isOneToOne: false; referencedRelation: "chem_concepts"; referencedColumns: ["id"] },{ foreignKeyName: "user_chem_attempts_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "user_chem_attempts_problem_template_id_fkey"; columns: ["problem_template_id"]; isOneToOne: false; referencedRelation: "chem_problem_templates"; referencedColumns: ["id"] },{ foreignKeyName: "user_chem_attempts_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"user_chem_mastery": {
Row: {
"id": string;
"user_id": string;
"concept_id": string;
"mastery_score": number;
"attempt_count": number;
"last_attempt_at": string | null;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"concept_id": string;
"mastery_score"?: number;
"attempt_count"?: number;
"last_attempt_at"?: string | null;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"concept_id"?: string;
"mastery_score"?: number;
"attempt_count"?: number;
"last_attempt_at"?: string | null;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "user_chem_mastery_concept_id_fkey"; columns: ["concept_id"]; isOneToOne: false; referencedRelation: "chem_concepts"; referencedColumns: ["id"] },{ foreignKeyName: "user_chem_mastery_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"user_lab_reports": {
Row: {
"id": string;
"user_id": string;
"lab_run_id": string | null;
"lab_template_id": string | null;
"binder_id": string | null;
"lesson_id": string | null;
"hypothesis": string;
"procedure": string;
"data_table": Json;
"calculations": string;
"observations": string;
"error_analysis": string;
"conclusion": string;
"teacher_notes": string | null;
"student_notes": string | null;
"final_result": Json;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"lab_run_id"?: string | null;
"lab_template_id"?: string | null;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"hypothesis"?: string;
"procedure"?: string;
"data_table"?: Json;
"calculations"?: string;
"observations"?: string;
"error_analysis"?: string;
"conclusion"?: string;
"teacher_notes"?: string | null;
"student_notes"?: string | null;
"final_result"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"lab_run_id"?: string | null;
"lab_template_id"?: string | null;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"hypothesis"?: string;
"procedure"?: string;
"data_table"?: Json;
"calculations"?: string;
"observations"?: string;
"error_analysis"?: string;
"conclusion"?: string;
"teacher_notes"?: string | null;
"student_notes"?: string | null;
"final_result"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "user_lab_reports_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_reports_lab_run_id_fkey"; columns: ["lab_run_id"]; isOneToOne: false; referencedRelation: "user_lab_runs"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_reports_lab_template_id_fkey"; columns: ["lab_template_id"]; isOneToOne: false; referencedRelation: "chem_lab_templates"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_reports_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_reports_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"user_lab_runs": {
Row: {
"id": string;
"user_id": string;
"binder_id": string | null;
"lesson_id": string | null;
"lab_template_id": string | null;
"status": string;
"checkpoint": Json;
"measurement_summary": Json;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"lab_template_id"?: string | null;
"status"?: string;
"checkpoint"?: Json;
"measurement_summary"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"lab_template_id"?: string | null;
"status"?: string;
"checkpoint"?: Json;
"measurement_summary"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "user_lab_runs_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_runs_lab_template_id_fkey"; columns: ["lab_template_id"]; isOneToOne: false; referencedRelation: "chem_lab_templates"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_runs_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "user_lab_runs_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"user_recent_items": {
Row: {
"id": string;
"user_id": string;
"item_type": string;
"item_id": string;
"binder_id": string | null;
"folder_id": string | null;
"lesson_id": string | null;
"title_snapshot": string | null;
"last_opened_at": string;
"open_count": number;
"metadata": Json;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"item_type": string;
"item_id": string;
"binder_id"?: string | null;
"folder_id"?: string | null;
"lesson_id"?: string | null;
"title_snapshot"?: string | null;
"last_opened_at"?: string;
"open_count"?: number;
"metadata"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"item_type"?: string;
"item_id"?: string;
"binder_id"?: string | null;
"folder_id"?: string | null;
"lesson_id"?: string | null;
"title_snapshot"?: string | null;
"last_opened_at"?: string;
"open_count"?: number;
"metadata"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "user_recent_items_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "user_recent_items_folder_id_fkey"; columns: ["folder_id"]; isOneToOne: false; referencedRelation: "folders"; referencedColumns: ["id"] },{ foreignKeyName: "user_recent_items_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "user_recent_items_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"whiteboard_assets": {
Row: {
"id": string;
"whiteboard_id": string;
"storage_path": string;
"mime_type": string;
"size_bytes": number;
"width": number | null;
"height": number | null;
"created_at": string;
"owner_id": string;
};
Insert: {
"id"?: string;
"whiteboard_id": string;
"storage_path": string;
"mime_type": string;
"size_bytes": number;
"width"?: number | null;
"height"?: number | null;
"created_at"?: string;
"owner_id": string;
};
Update: {
"id"?: string;
"whiteboard_id"?: string;
"storage_path"?: string;
"mime_type"?: string;
"size_bytes"?: number;
"width"?: number | null;
"height"?: number | null;
"created_at"?: string;
"owner_id"?: string;
};
Relationships: [{ foreignKeyName: "whiteboard_assets_whiteboard_id_fkey"; columns: ["whiteboard_id"]; isOneToOne: false; referencedRelation: "whiteboards"; referencedColumns: ["id"] }];
};
"whiteboard_versions": {
Row: {
"id": string;
"whiteboard_id": string;
"version": number;
"scene_json": Json;
"module_elements": Json;
"scene_size_bytes": number;
"created_at": string;
"created_by": string | null;
"owner_id": string;
"version_kind": string;
"retention_status": string;
"retained_until": string | null;
"compacted_at": string | null;
"compacted_from_version_count": number;
"approximate_payload_bytes": number;
};
Insert: {
"id"?: string;
"whiteboard_id": string;
"version": number;
"scene_json"?: Json;
"module_elements"?: Json;
"scene_size_bytes"?: number;
"created_at"?: string;
"created_by"?: string | null;
"owner_id": string;
"version_kind"?: string;
"retention_status"?: string;
"retained_until"?: string | null;
"compacted_at"?: string | null;
"compacted_from_version_count"?: number;
"approximate_payload_bytes"?: number;
};
Update: {
"id"?: string;
"whiteboard_id"?: string;
"version"?: number;
"scene_json"?: Json;
"module_elements"?: Json;
"scene_size_bytes"?: number;
"created_at"?: string;
"created_by"?: string | null;
"owner_id"?: string;
"version_kind"?: string;
"retention_status"?: string;
"retained_until"?: string | null;
"compacted_at"?: string | null;
"compacted_from_version_count"?: number;
"approximate_payload_bytes"?: number;
};
Relationships: [{ foreignKeyName: "whiteboard_versions_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },{ foreignKeyName: "whiteboard_versions_whiteboard_id_fkey"; columns: ["whiteboard_id"]; isOneToOne: false; referencedRelation: "whiteboards"; referencedColumns: ["id"] }];
};
"whiteboards": {
Row: {
"id": string;
"owner_id": string;
"binder_id": string | null;
"lesson_id": string | null;
"title": string;
"subject": string;
"module_context": string;
"scene_json": Json;
"module_elements": Json;
"thumbnail_path": string | null;
"scene_size_bytes": number;
"asset_size_bytes": number;
"object_count": number;
"created_at": string;
"updated_at": string;
"archived_at": string | null;
"latest_version_id": string | null;
"latest_version_number": number | null;
"latest_version_created_at": string | null;
"version_retention_checked_at": string | null;
"version_compaction_candidate_count": number;
"version_payload_bytes_estimate": number;
"revision": number;
};
Insert: {
"id"?: string;
"owner_id": string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"title": string;
"subject"?: string;
"module_context"?: string;
"scene_json"?: Json;
"module_elements"?: Json;
"thumbnail_path"?: string | null;
"scene_size_bytes"?: number;
"asset_size_bytes"?: number;
"object_count"?: number;
"created_at"?: string;
"updated_at"?: string;
"archived_at"?: string | null;
"latest_version_id"?: string | null;
"latest_version_number"?: number | null;
"latest_version_created_at"?: string | null;
"version_retention_checked_at"?: string | null;
"version_compaction_candidate_count"?: number;
"version_payload_bytes_estimate"?: number;
"revision"?: number;
};
Update: {
"id"?: string;
"owner_id"?: string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"title"?: string;
"subject"?: string;
"module_context"?: string;
"scene_json"?: Json;
"module_elements"?: Json;
"thumbnail_path"?: string | null;
"scene_size_bytes"?: number;
"asset_size_bytes"?: number;
"object_count"?: number;
"created_at"?: string;
"updated_at"?: string;
"archived_at"?: string | null;
"latest_version_id"?: string | null;
"latest_version_number"?: number | null;
"latest_version_created_at"?: string | null;
"version_retention_checked_at"?: string | null;
"version_compaction_candidate_count"?: number;
"version_payload_bytes_estimate"?: number;
"revision"?: number;
};
Relationships: [{ foreignKeyName: "whiteboards_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"workspace_activity_events": {
Row: {
"id": string;
"user_id": string;
"binder_id": string | null;
"lesson_id": string | null;
"module_id": string;
"event_type": string;
"created_at": string;
"metadata": Json;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"module_id": string;
"event_type": string;
"created_at"?: string;
"metadata"?: Json;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string | null;
"lesson_id"?: string | null;
"module_id"?: string;
"event_type"?: string;
"created_at"?: string;
"metadata"?: Json;
};
Relationships: [{ foreignKeyName: "workspace_activity_events_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "workspace_activity_events_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "binder_lessons"; referencedColumns: ["id"] },{ foreignKeyName: "workspace_activity_events_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"workspace_archive_imports": {
Row: {
"owner_id": string;
"batch_id": string;
"archive_digest": string;
"request_hash": string;
"counts": Json;
"recovery_data": Json;
"created_at": string;
};
Insert: {
"owner_id": string;
"batch_id": string;
"archive_digest": string;
"request_hash": string;
"counts": Json;
"recovery_data": Json;
"created_at"?: string;
};
Update: {
"owner_id"?: string;
"batch_id"?: string;
"archive_digest"?: string;
"request_hash"?: string;
"counts"?: Json;
"recovery_data"?: Json;
"created_at"?: string;
};
Relationships: [{ foreignKeyName: "workspace_archive_imports_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"workspace_preferences": {
Row: {
"id": string;
"user_id": string;
"binder_id": string;
"preferences": Json;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"user_id": string;
"binder_id": string;
"preferences": Json;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"user_id"?: string;
"binder_id"?: string;
"preferences"?: Json;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "workspace_preferences_binder_id_fkey"; columns: ["binder_id"]; isOneToOne: false; referencedRelation: "binders"; referencedColumns: ["id"] },{ foreignKeyName: "workspace_preferences_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }];
};
"workspace_presets": {
Row: {
"id": string;
"suite_template_id": string;
"preset_id": string;
"breakpoint": string;
"layout_json": Json;
"is_default": boolean;
"created_at": string;
"updated_at": string;
};
Insert: {
"id"?: string;
"suite_template_id": string;
"preset_id": string;
"breakpoint": string;
"layout_json": Json;
"is_default"?: boolean;
"created_at"?: string;
"updated_at"?: string;
};
Update: {
"id"?: string;
"suite_template_id"?: string;
"preset_id"?: string;
"breakpoint"?: string;
"layout_json"?: Json;
"is_default"?: boolean;
"created_at"?: string;
"updated_at"?: string;
};
Relationships: [{ foreignKeyName: "workspace_presets_suite_template_id_fkey"; columns: ["suite_template_id"]; isOneToOne: false; referencedRelation: "suite_templates"; referencedColumns: ["id"] }];
};
};
Views: {
};
Functions: {
"account_deletion_state": { Args: {"p_owner": string | null;}; Returns: boolean };
"apply_catalog_seed": { Args: {"p_payload": Json;}; Returns: Json };
"armor": { Args: {"arg1": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": (string)[] | null;"arg3": (string)[] | null;}; Returns: string };
"begin_account_deletion": { Args: {"p_owner": string | null;"p_operation": string | null;"p_customer": string | null;"p_lease": string | null;}; Returns: undefined };
"bind_billing_customer": { Args: {"p_owner": string | null;"p_customer": string | null;}; Returns: string };
"bn_jsonb_plain_text": { Args: {"value": Json;}; Returns: string };
"bn_word_count": { Args: {"input": string | null;}; Returns: number };
"can_read_suite_template": { Args: {"target_suite_id": string | null;}; Returns: boolean };
"claim_billing_event": { Args: {"p_customer": string | null;"p_event": string | null;"p_token": string | null;}; Returns: string };
"cleanup_stale_summary_refresh_jobs": { Args: {"retention"?: string | null;}; Returns: number };
"complete_user_asset": { Args: {"p_id": string | null;"p_owner": string | null;"p_sha256": string | null;"p_size_bytes": number | null;"p_mime_type": string | null;}; Returns: Database["public"]["Tables"]["user_assets"]["Row"] };
"crypt": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string };
"dearmor": { Args: {"arg1": string | null;}; Returns: string };
"decrypt": { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"decrypt_iv": { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;"arg4": string | null;}; Returns: string };
"digest": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string };
"encrypt": { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"encrypt_iv": { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;"arg4": string | null;}; Returns: string };
"enqueue_summary_refresh_job": { Args: {"target_job_type": string | null;"target_entity_type": string | null;"target_entity_id"?: string | null;"target_owner_id"?: string | null;"target_priority"?: number | null;}; Returns: string };
"export_portable_workspace": { Args: Record<PropertyKey, never>; Returns: Json };
"finish_billing_event": { Args: {"p_customer": string | null;"p_event": string | null;"p_token": string | null;"p_entitlement": Json;}; Returns: undefined };
"finish_user_asset_deletion": { Args: {"p_id": string | null;"p_owner": string | null;}; Returns: undefined };
"gen_random_bytes": { Args: {"arg1": number | null;}; Returns: string };
"gen_random_uuid": { Args: Record<PropertyKey, never>; Returns: string };
"gen_salt": { Args: {"arg1": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": number | null;}; Returns: string };
"hmac": { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"import_portable_workspace": { Args: {"p_archive": Json;"p_batch_id": string | null;"p_archive_digest": string | null;}; Returns: Json };
"is_admin": { Args: Record<PropertyKey, never>; Returns: boolean };
"list_personal_trash": { Args: Record<PropertyKey, never>; Returns: Json };
"mark_user_asset_deleting": { Args: {"p_id": string | null;}; Returns: Database["public"]["Tables"]["user_assets"]["Row"] };
"owns_published_or_enrolled": { Args: {"target_binder_id": string | null;}; Returns: boolean } | { Args: {"target_binder_id": string | null;}; Returns: boolean };
"pgp_armor_headers": { Args: {"": string | null;}; Returns: {"key": string;"value": string;}[] };
"pgp_key_id": { Args: {"arg1": string | null;}; Returns: string };
"pgp_pub_decrypt": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;"arg4": string | null;}; Returns: string };
"pgp_pub_decrypt_bytea": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;"arg4": string | null;}; Returns: string };
"pgp_pub_encrypt": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"pgp_pub_encrypt_bytea": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"pgp_sym_decrypt": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"pgp_sym_decrypt_bytea": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"pgp_sym_encrypt": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"pgp_sym_encrypt_bytea": { Args: {"arg1": string | null;"arg2": string | null;}; Returns: string } | { Args: {"arg1": string | null;"arg2": string | null;"arg3": string | null;}; Returns: string };
"process_summary_refresh_queue": { Args: {"max_messages"?: number | null;}; Returns: number };
"record_user_recent_item": { Args: {"p_user_id": string | null;"p_item_type": string | null;"p_item_id": string | null;"p_binder_id"?: string | null;"p_folder_id"?: string | null;"p_lesson_id"?: string | null;"p_title_snapshot"?: string | null;"p_metadata"?: Json;}; Returns: undefined };
"refresh_admin_binder_summary": { Args: {"target_binder_id": string | null;}; Returns: undefined };
"refresh_all_admin_summaries": { Args: Record<PropertyKey, never>; Returns: undefined };
"refresh_all_dashboard_summaries": { Args: Record<PropertyKey, never>; Returns: undefined };
"refresh_all_tutorial_video_summaries": { Args: Record<PropertyKey, never>; Returns: undefined };
"refresh_dashboard_binder_summary": { Args: {"target_binder_id": string | null;}; Returns: undefined };
"refresh_dashboard_folder_summary": { Args: {"target_folder_id": string | null;}; Returns: undefined };
"refresh_lesson_search_excerpt": { Args: {"target_lesson_id": string | null;}; Returns: undefined };
"refresh_tutorial_video_summary": { Args: {"target_video_id": string | null;}; Returns: undefined };
"release_billing_lease": { Args: {"p_customer": string | null;"p_token": string | null;}; Returns: undefined };
"reserve_user_asset": { Args: {"p_id": string | null;"p_name": string | null;"p_mime_type": string | null;"p_size_bytes": number | null;"p_sha256": string | null;"p_import_batch_id"?: string | null;}; Returns: Database["public"]["Tables"]["user_assets"]["Row"] };
"restore_whiteboard_version": { Args: {"p_board_id": string | null;"p_version_id": string | null;"p_expected_revision": number | null;"p_operation_id": string | null;}; Returns: Json };
"save_personal_content": { Args: {"p_kind": string | null;"p_record": Json;"p_expected_revision": number | null;"p_operation_id": string | null;}; Returns: Json };
"save_review_item": { Args: {"p_record": Json;"p_expected_revision": number | null;"p_operation_id": string | null;"p_events"?: Json;}; Returns: Json };
"save_review_session": { Args: {"p_id": string | null;"p_session": Json;}; Returns: Json };
"save_whiteboard_snapshot": { Args: {"p_board": Json;"p_expected_revision": number | null;"p_create_version": boolean | null;"p_operation_id": string | null;}; Returns: Json };
"set_personal_trash": { Args: {"p_kind": string | null;"p_id": string | null;"p_action": string | null;"p_confirmation"?: string | null;}; Returns: Json };
"whiteboard_json_array_length": { Args: {"value": Json;}; Returns: number };
};
Enums: {
"app_role": "admin" | "learner";
"publish_status": "draft" | "published" | "archived";
"purchase_status": "pending" | "paid" | "refunded" | "comped";
};
CompositeTypes: Record<PropertyKey, never>;
} };
