import type { JSONContent } from "@tiptap/react";
import type {
  Binder,
  BinderLesson,
  Folder,
  HistoryEventTemplate,
  HistoryMythCheckTemplate,
  HistorySourceTemplate,
  SuiteTemplate,
  WorkspacePresetDefinition,
} from "@/types";
import { demoLessons } from "@/lib/demo-data";

const now = new Date().toISOString();
const systemOwnerId = "system-seed-admin";

function textNode(text: string): JSONContent {
  return { type: "text", text };
}

function paragraph(text: string): JSONContent {
  return {
    type: "paragraph",
    content: [textNode(text)],
  };
}

function heading(text: string, level = 2): JSONContent {
  return {
    type: "heading",
    attrs: { level },
    content: [textNode(text)],
  };
}

function bulletList(items: string[]): JSONContent {
  return {
    type: "bulletList",
    content: items.map((item) => ({
      type: "listItem",
      content: [paragraph(item)],
    })),
  };
}

function lessonDoc(...content: JSONContent[]): JSONContent {
  return {
    type: "doc",
    content,
  };
}

export const SYSTEM_SUITE_IDS = {
  algebra: "suite-algebra-foundations",
  riseOfRome: "suite-rise-of-rome",
  historyDemo: "suite-history-demo",
} as const;

export const SYSTEM_BINDER_IDS = {
  algebra: "binder-algebra-foundations",
  riseOfRome: "binder-rise-of-rome",
  frenchRevolution: "binder-french-revolution-history-suite",
} as const;

export const SYSTEM_SEED_VERSION = "2026.04.22-history-suite-foundation";

export const systemSuiteTemplates: SuiteTemplate[] = [
  {
    id: SYSTEM_SUITE_IDS.algebra,
    slug: "algebra-1-foundations",
    title: "Algebra 1 Foundations",
    subject: "Mathematics",
    description: "A backend-native Algebra 1 demo suite for expression, function, and graph study.",
    folder_title: "Math Suite Demo",
    history_mode: false,
    default_preset_id: "split-study",
    status: "published",
    created_at: now,
    updated_at: now,
  },
  {
    id: SYSTEM_SUITE_IDS.riseOfRome,
    slug: "rise-of-rome",
    title: "Rise of Rome",
    subject: "History",
    description: "A backend-native Rome demo suite with timeline, evidence, and argument surfaces.",
    folder_title: "Rise of Rome Demo",
    history_mode: true,
    default_preset_id: "history-guided",
    status: "published",
    created_at: now,
    updated_at: now,
  },
  {
    id: SYSTEM_SUITE_IDS.historyDemo,
    slug: "history-suite-demo",
    title: "History Suite Demo",
    subject: "History",
    description: "A French Revolution showcase for timeline, evidence, argument, and myth-versus-history study.",
    folder_title: "History",
    history_mode: true,
    default_preset_id: "history-guided",
    status: "published",
    created_at: now,
    updated_at: now,
  },
];

export function buildSystemFolderFromSuite(suite: SuiteTemplate): Folder {
  return {
    id: `folder-${suite.id}`,
    owner_id: systemOwnerId,
    name: suite.folder_title,
    color: suite.history_mode ? "amber" : "rose",
    source: "system",
    suite_template_id: suite.id,
    created_at: now,
    updated_at: now,
  };
}

export const frenchRevolutionBinder: Binder = {
  id: SYSTEM_BINDER_IDS.frenchRevolution,
  owner_id: systemOwnerId,
  suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
  title: "French Revolution: Timeline, Evidence, and Argument",
  slug: "french-revolution-timeline-evidence-argument",
  description:
    "A demo-ready history binder built to show how BinderNotes handles chronology, source work, argument chains, and myth checking.",
  subject: "History",
  level: "Modern Europe",
  status: "published",
  price_cents: 0,
  cover_url:
    "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=1400&q=82",
  pinned: true,
  created_at: now,
  updated_at: now,
};

export const frenchRevolutionLessons: BinderLesson[] = [
  {
    id: "lesson-french-revolution-overview",
    binder_id: frenchRevolutionBinder.id,
    title: "Timeline and Turning Points",
    order_index: 1,
    is_preview: true,
    content: lessonDoc(
      heading("Why this binder starts with chronology"),
      paragraph(
        "The French Revolution becomes easier to understand when students can see how financial crisis, representative politics, crowd action, and war stack on top of one another over time.",
      ),
      heading("Anchor questions"),
      bulletList([
        "Why does the Estates-General meeting become a constitutional crisis?",
        "Why does the Bastille matter more symbolically than militarily?",
        "How does revolutionary momentum turn into state violence?",
        "Why does Napoleon's rise look like both an ending and a continuation?",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-french-revolution-evidence",
    binder_id: frenchRevolutionBinder.id,
    title: "Source Evidence and Competing Claims",
    order_index: 2,
    is_preview: false,
    content: lessonDoc(
      heading("How to read source evidence here"),
      paragraph(
        "Treat each source as a claim made by someone in a specific context. Ask what audience it addresses, what it tries to persuade, and what kind of evidence it can reasonably support.",
      ),
      heading("What strong evidence work looks like"),
      bulletList([
        "Quote or paraphrase the source accurately.",
        "Name the author or institution behind it.",
        "Explain which claim the source supports or weakens.",
        "Add a reliability note instead of assuming every source works the same way.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-french-revolution-argument",
    binder_id: frenchRevolutionBinder.id,
    title: "Cause and Effect Argument Builder",
    order_index: 3,
    is_preview: false,
    content: lessonDoc(
      heading("From events to arguments"),
      paragraph(
        "A strong history argument connects events instead of listing them. This binder helps students move from chronology to causation by building editable chains with evidence attached.",
      ),
      heading("Prompt"),
      paragraph("What were the most important causes of the French Revolution?"),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-french-revolution-myth-history",
    binder_id: frenchRevolutionBinder.id,
    title: "Myth, Oversimplification, and Evidence",
    order_index: 4,
    is_preview: false,
    content: lessonDoc(
      heading("Why myth checks matter"),
      paragraph(
        "History students often inherit clean one-line stories. This panel helps separate catchy claims from evidence-supported explanations without pretending every historical question has one perfect answer.",
      ),
      heading("Status guide"),
      bulletList([
        "Myth: the claim is plainly wrong.",
        "Oversimplification: the claim captures one part but hides the larger picture.",
        "Contested: historians disagree on the best interpretation.",
        "Evidence-supported history: the claim is well grounded in available evidence.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
];

export const frenchRevolutionEventTemplates: HistoryEventTemplate[] = [
  {
    id: "event-estates-general-1789",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-overview",
    title: "Estates-General convenes",
    summary: "Louis XVI calls the Estates-General in response to fiscal collapse and political deadlock.",
    significance: "The monarchy opens a representative process it cannot fully control.",
    location_label: "Versailles, France",
    location_lat: 48.8049,
    location_lng: 2.1204,
    date_label: "1789",
    sort_year: 1789,
    sort_month: 5,
    sort_day: 5,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["finance", "representation", "monarchy"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-tennis-court-oath-1789",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-overview",
    title: "Tennis Court Oath",
    summary: "Representatives of the Third Estate swear not to disperse until France has a constitution.",
    significance: "Political legitimacy starts moving away from the king and toward the nation.",
    location_label: "Versailles, France",
    location_lat: 48.8049,
    location_lng: 2.1204,
    date_label: "1789",
    sort_year: 1789,
    sort_month: 6,
    sort_day: 20,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["constitution", "representation"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-bastille-1789",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-overview",
    title: "Storming of the Bastille",
    summary: "Paris crowds seize the Bastille amid fear, rumor, and armed confrontation.",
    significance: "The revolution becomes visibly popular, urban, and difficult for the crown to contain.",
    location_label: "Paris, France",
    location_lat: 48.8566,
    location_lng: 2.3522,
    date_label: "1789",
    sort_year: 1789,
    sort_month: 7,
    sort_day: 14,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["crowd action", "violence", "symbolism"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-rights-of-man-1789",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-evidence",
    title: "Declaration of the Rights of Man and Citizen",
    summary: "The National Assembly articulates universal political principles and rights claims.",
    significance: "Revolutionary politics now has a language of citizenship and legitimacy that travels beyond one crisis.",
    location_label: "Paris, France",
    location_lat: 48.8566,
    location_lng: 2.3522,
    date_label: "1789",
    sort_year: 1789,
    sort_month: 8,
    sort_day: 26,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["rights", "citizenship", "political ideas"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-reign-of-terror-1793",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-argument",
    title: "Reign of Terror",
    summary: "The revolutionary state uses extraordinary violence to defend itself against enemies and instability.",
    significance: "Revolutionary ideals and coercive state power become tightly entangled.",
    location_label: "Paris, France",
    location_lat: 48.8566,
    location_lng: 2.3522,
    date_label: "1793-1794",
    sort_year: 1793,
    sort_month: 9,
    sort_day: 5,
    era: "ce",
    precision: "approximate",
    approximate: true,
    themes: ["war", "violence", "state power"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-napoleon-1799",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-myth-history",
    title: "Napoleon seizes power",
    summary: "Napoleon Bonaparte uses the coup of 18 Brumaire to end the Directory and create a new executive order.",
    significance: "The revolution does not simply end; it is reorganized through military and administrative power.",
    location_label: "Paris, France",
    location_lat: 48.8566,
    location_lng: 2.3522,
    date_label: "1799",
    sort_year: 1799,
    sort_month: 11,
    sort_day: 9,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["executive power", "military", "continuity"],
    created_at: now,
    updated_at: now,
  },
];

export const frenchRevolutionSourceTemplates: HistorySourceTemplate[] = [
  {
    id: "source-sieyes-third-estate",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-evidence",
    title: "What Is the Third Estate?",
    source_type: "primary",
    author: "Emmanuel-Joseph Sieyes",
    date_label: "1789",
    audience: "French political readers",
    purpose: "To argue that the Third Estate represents the nation and deserves political authority.",
    point_of_view: "Reform-minded clerical and political critic of privilege.",
    context_note: "Published during the political crisis before the Estates-General became revolutionary.",
    reliability_note: "Strong evidence for revolutionary political argument, weaker for neutral social description.",
    citation_url: null,
    quote_text: "What is the Third Estate? Everything. What has it been hitherto in the political order? Nothing.",
    claim_supports: "Political representation and social inequality were central causes of the revolution.",
    claim_challenges: "The revolution can be reduced to food shortages alone.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-rights-of-man",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-evidence",
    title: "Declaration of the Rights of Man and Citizen",
    source_type: "primary",
    author: "National Assembly",
    date_label: "1789",
    audience: "French citizens and political observers",
    purpose: "To state revolutionary principles of liberty, equality, and sovereignty.",
    point_of_view: "Assembly-driven constitutional revolutionary perspective.",
    context_note: "Written after the early revolutionary crisis had already broken royal monopoly on political legitimacy.",
    reliability_note: "Excellent for the ideals revolutionaries claimed to endorse; not proof that all citizens received those rights equally.",
    citation_url: null,
    quote_text: "Men are born and remain free and equal in rights.",
    claim_supports: "Enlightenment political ideas shaped revolutionary goals and language.",
    claim_challenges: "The revolution was only a fight over taxes and bread.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-robespierre-terror",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-argument",
    title: "Robespierre on political virtue and terror",
    source_type: "primary",
    author: "Maximilien Robespierre",
    date_label: "1794",
    audience: "National Convention and revolutionary political community",
    purpose: "To justify extraordinary coercion in defense of the revolution.",
    point_of_view: "Radical republican state-defense perspective under wartime pressure.",
    context_note: "Produced when the revolutionary government linked virtue, emergency, and punishment.",
    reliability_note: "Strong for understanding revolutionary self-justification; not a neutral description of necessity.",
    citation_url: null,
    quote_text: "Terror is nothing other than justice, prompt, severe, inflexible.",
    claim_supports: "War and internal enemies helped radicalize the revolution into state violence.",
    claim_challenges: "The revolution moved in a straight line toward liberty.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-napoleon-brumaire",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-myth-history",
    title: "Napoleon after 18 Brumaire",
    source_type: "secondary",
    author: "Modern historical synthesis",
    date_label: "Later interpretation",
    audience: "History students",
    purpose: "To explain how Napoleon both ended and preserved parts of the revolution.",
    point_of_view: "Interpretive, retrospective historical analysis.",
    context_note: "Useful for showing continuity between revolutionary instability and Napoleonic consolidation.",
    reliability_note: "Good for synthesis, but should be paired with primary evidence for close claims.",
    citation_url: null,
    quote_text: "Napoleon closed one phase of the revolution by stabilizing many of its institutional changes under new authority.",
    claim_supports: "Napoleon represented both a break with revolutionary pluralism and a continuation of revolutionary state building.",
    claim_challenges: "Napoleon simply restored the old regime.",
    created_at: now,
    updated_at: now,
  },
];

export const frenchRevolutionMythCheckTemplates: HistoryMythCheckTemplate[] = [
  {
    id: "myth-bread-prices-only",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-myth-history",
    myth_text: "The French Revolution was only caused by bread prices.",
    corrected_claim:
      "Bread prices mattered, but the revolution also grew out of fiscal crisis, social inequality, political representation disputes, and Enlightenment ideas.",
    status: "oversimplification",
    explanation:
      "Food scarcity heightened anger and urgency, but it worked alongside institutional collapse and political conflict rather than replacing them.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-napoleon-short",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-myth-history",
    myth_text: "Napoleon was extremely short.",
    corrected_claim:
      "Napoleon was likely around average height for his era; the myth grew from caricature and translation differences.",
    status: "myth",
    explanation:
      "British propaganda and confusion between French and English measurement systems helped create a much more exaggerated image than the evidence supports.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-flat-earth-middle-ages",
    suite_template_id: SYSTEM_SUITE_IDS.historyDemo,
    binder_id: frenchRevolutionBinder.id,
    lesson_id: "lesson-french-revolution-myth-history",
    myth_text: "People in the Middle Ages believed the Earth was flat.",
    corrected_claim:
      "Educated medieval Europeans generally knew the Earth was spherical; the flat-earth story became popular much later.",
    status: "evidence_supported",
    explanation:
      "The claim survives because it is memorable, not because it matches the mainstream learned tradition of medieval Europe.",
    created_at: now,
    updated_at: now,
  },
];

export const riseOfRomeEventTemplates: HistoryEventTemplate[] = [
  {
    id: "event-aeneas-trojan-origin-tradition",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-origins",
    title: "Aeneas and the Trojan origin tradition",
    summary:
      "Roman writers connect Rome's ancestry to Aeneas, Troy, and divine favor rather than treating the city as an ordinary settlement.",
    significance:
      "The story shows how Rome used myth to claim antiquity, destiny, and a place in the wider Mediterranean imagination.",
    location_label: "Troy / Latium",
    location_lat: 39.9573,
    location_lng: 26.2389,
    date_label: "Mythic age",
    sort_year: 1180,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "approximate",
    approximate: true,
    themes: ["myth", "identity", "memory"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-romulus-and-remus-legend",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-origins",
    title: "Romulus and Remus mythic origins",
    summary:
      "Roman tradition places the city's founding in a heroic legend involving the twin brothers Romulus and Remus.",
    significance:
      "The story provides a civic memory of origin, monarchy, and contested legitimacy at Rome's beginning.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "753 BCE",
    sort_year: 753,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: true,
    themes: ["founding", "myth", "memory"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-monarchy-rep-expulsion",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-foundation-kingdom",
    title: "The monarchy gives way to the republic",
    summary:
      "Roman tradition says the expulsion of the last king becomes the story of shared office and anti-monarchical identity.",
    significance:
      "This transition becomes the canonical political narrative for why Rome moved from kingship to republican offices.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "509 BCE",
    sort_year: 509,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: true,
    themes: ["monarchy", "republic", "institutions"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-gallic-sack",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-republic-italy",
    title: "Gallic sack of Rome",
    summary:
      "The sack shocks the city and reinforces the republic's commitment to military organization and strategic resilience.",
    significance:
      "A near-traumatic crisis becomes part of Roman memory and strategic thinking in the republic.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "390 BCE",
    sort_year: 390,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: true,
    themes: ["security", "republic", "foreign-war"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-roman-control-italy-265-bce",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-republic-italy",
    title: "Rome controls Italy",
    summary:
      "By 265 BCE, Rome has become the dominant power in Italy through conquest, alliances, colonies, and roads.",
    significance:
      "Italian control gives Rome the manpower and strategic base needed for overseas war against Carthage.",
    location_label: "Italian peninsula",
    location_lat: 42.5,
    location_lng: 12.5,
    date_label: "265 BCE",
    sort_year: 265,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: true,
    themes: ["expansion", "citizenship", "alliances"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-first-punic-war",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-punic-wars",
    title: "First Punic War",
    summary:
      "Rome and Carthage fight over Mediterranean power, opening a new era of long-distance war and naval rivalry.",
    significance:
      "The war marks Rome's leap into sea power and Mediterranean imperial competition.",
    location_label: "Sicily",
    location_lat: 37.5027,
    location_lng: 14.0149,
    date_label: "264 BCE",
    sort_year: 264,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: false,
    themes: ["expansion", "mediterranean", "war"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-second-punic-war",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-punic-wars",
    title: "Second Punic War",
    summary:
      "Hannibal's campaigns push Rome into one of its hardest strategic tests, but Roman adaptation keeps the war going.",
    significance:
      "The republic survives and grows by adapting through repeated loss, reform, and renewed military coordination.",
    location_label: "Carthage / Italy",
    location_lat: 34.003,
    location_lng: 9.0,
    date_label: "218 BCE",
    sort_year: 218,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: false,
    themes: ["resilience", "military", "adaptation"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-third-punic-war",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-punic-wars",
    title: "Third Punic War",
    summary:
      "Rome destroys Carthage and removes a rival for centuries of rivalry in western Mediterranean power politics.",
    significance:
      "The event closes the immediate Carthaginian challenge and confirms Rome's imperial trajectory.",
    location_label: "Carthage",
    location_lat: 36.8539,
    location_lng: 10.3251,
    date_label: "146 BCE",
    sort_year: 146,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: false,
    themes: ["rivalry", "imperial-expansion", "military-victory"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-gracchi-reforms",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Gracchi reform crisis",
    summary:
      "The reform movement of Tiberius and Gaius Gracchus deepens conflict over land, citizenship, and elite control.",
    significance:
      "The Gracchi period is an early signal that republican institutions are struggling with the pressures of expansion.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "133 BCE",
    sort_year: 133,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: true,
    themes: ["reform", "inequality", "republican-crisis"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-marius-and-sulla",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Marius and Sulla militarize politics",
    summary:
      "Military reform, personal command loyalty, and civil conflict make armed power a direct tool of Roman politics.",
    significance:
      "The late republic's institutions are weakened when armies become tied to commanders more than civic consensus.",
    location_label: "Rome and Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "107-82 BCE",
    sort_year: 107,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "approximate",
    approximate: true,
    themes: ["military-reform", "civil-war", "republican-crisis"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-caesar-rubicon",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Caesar crosses the Rubicon",
    summary:
      "Julius Caesar's move to military force inside Roman politics makes civil war the crisis of the late republic.",
    significance:
      "The republic cannot hold together military loyalty and republican institution in the same shape.",
    location_label: "Northern Italy",
    location_lat: 45.4642,
    location_lng: 9.1900,
    date_label: "49 BCE",
    sort_year: 49,
    sort_month: 1,
    sort_day: 1,
    era: "bce",
    precision: "year",
    approximate: false,
    themes: ["civil-war", "caesar", "political-order"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-assassination-julius-caesar",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Assassination of Julius Caesar",
    summary:
      "The Republic's senatorial elites respond with violence to prevent personal military leadership from controlling state power.",
    significance:
      "The killing removes one man but does not restore stability; civil war enters a new phase.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "44 BCE",
    sort_year: 44,
    sort_month: 3,
    sort_day: 15,
    era: "bce",
    precision: "day",
    approximate: false,
    themes: ["violence", "elite-conflict", "institutional-breakdown"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-actium",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Battle of Actium",
    summary:
      "Octavian defeats Antony and Cleopatra and marks the final military route toward principate governance.",
    significance:
      "The battle is the hinge between late republican civil conflict and new imperial stability.",
    location_label: "Ambracian Gulf (Actium)",
    location_lat: 38.9637,
    location_lng: 20.7649,
    date_label: "31 BCE",
    sort_year: 31,
    sort_month: 9,
    sort_day: 2,
    era: "bce",
    precision: "day",
    approximate: false,
    themes: ["civil-war", "Augustus", "transition"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-augustus-title",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Augustus receives imperial title",
    summary:
      "In 27 BCE, Octavian accepts the title Augustus and stabilizes one-man rule while preserving republican language.",
    significance:
      "This settlement marks the practical start of empire and a durable new constitutional style.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "27 BCE",
    sort_year: 27,
    sort_month: 1,
    sort_day: 16,
    era: "bce",
    precision: "day",
    approximate: false,
    themes: ["Augustus", "principate", "state-reorganization"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-pax-romana-early-empire",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-golden-age-frontiers",
    title: "Pax Romana and the early empire",
    summary:
      "The early imperial system reduces elite civil war, expands administration, and makes Roman order feel durable across provinces.",
    significance:
      "This is the period when empire becomes a lived system of roads, law, taxation, armies, cities, and status.",
    location_label: "Roman Mediterranean",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "27 BCE-180 CE",
    sort_year: 14,
    sort_month: 1,
    sort_day: 1,
    era: "ce",
    precision: "approximate",
    approximate: true,
    themes: ["empire", "administration", "stability"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-trajan-maximum-extent",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-golden-age-frontiers",
    title: "Trajan's maximum extent",
    summary:
      "Under Trajan, the empire reaches its greatest territorial extent, stretching Roman logistics and frontier management.",
    significance:
      "The high point of expansion also reveals the permanent problem of governing and defending such a large state.",
    location_label: "Roman Empire",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "117 CE",
    sort_year: 117,
    sort_month: 1,
    sort_day: 1,
    era: "ce",
    precision: "year",
    approximate: false,
    themes: ["frontiers", "empire", "overextension"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-diocletian-reforms",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-crisis-constantine",
    title: "Diocletian's reforms",
    summary:
      "Diocletian restructures imperial rule through the tetrarchy, tax reforms, military reorganization, and stronger bureaucracy.",
    significance:
      "Reform helps stabilize the empire, but also shows that the old governing model could no longer carry the whole system.",
    location_label: "Roman Empire",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "284-305 CE",
    sort_year: 284,
    sort_month: 1,
    sort_day: 1,
    era: "ce",
    precision: "approximate",
    approximate: true,
    themes: ["reform", "division", "state-power"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-edict-of-milan",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-crisis-constantine",
    title: "Edict of Milan",
    summary:
      "Constantius and Constantine's policy formally ends Christian persecution and legalizes Christian worship across the empire.",
    significance:
      "Religious policy shifts public life and imperial legitimacy for the late antique period.",
    location_label: "Milan, Northern Italy",
    location_lat: 45.4642,
    location_lng: 9.19,
    date_label: "313 CE",
    sort_year: 313,
    sort_month: 10,
    sort_day: 28,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["religion", "imperial-policy", "late-antiquity"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-founding-constantinople",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-crisis-constantine",
    title: "Constantinople founded",
    summary:
      "Constantine builds a new eastern capital and shifts the imperial center of gravity.",
    significance:
      "Power survives through institutional reinvention rather than simple continuity of the old western capital.",
    location_label: "Constantinople (Istanbul)",
    location_lat: 41.0082,
    location_lng: 28.9784,
    date_label: "330 CE",
    sort_year: 330,
    sort_month: 5,
    sort_day: 11,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["administration", "succession", "state-reform"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-sack-of-rome",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-fall-west",
    title: "Sack of Rome",
    summary:
      "Alaric's forces sack the city, signaling a symbolic and political blow to western Roman authority.",
    significance:
      "The event dramatizes imperial strain rather than a single decisive endpoint.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "410 CE",
    sort_year: 410,
    sort_month: 8,
    sort_day: 24,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["decline", "symbolic", "frontier-pressure"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-vandal-sack-455",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-fall-west",
    title: "Second sack of Rome",
    summary:
      "The Vandals sack Rome in 455, reinforcing that western imperial authority has become fragile and negotiated.",
    significance:
      "Repeated sacks matter because they show gradual loss of control rather than one clean moment of collapse.",
    location_label: "Rome, Italy",
    location_lat: 41.9028,
    location_lng: 12.4964,
    date_label: "455 CE",
    sort_year: 455,
    sort_month: 6,
    sort_day: 2,
    era: "ce",
    precision: "month",
    approximate: true,
    themes: ["western-collapse", "symbolism", "external-pressure"],
    created_at: now,
    updated_at: now,
  },
  {
    id: "event-deposition-romulus-augustulus",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-fall-west",
    title: "Deposition of Romulus Augustulus",
    summary:
      "The final western emperor is removed in 476, ending the western imperial office in Rome.",
    significance:
      "The imperial title outlives this moment in the east, showing continuity and change at once.",
    location_label: "Ravenna, Italy",
    location_lat: 44.4170,
    location_lng: 12.2019,
    date_label: "476 CE",
    sort_year: 476,
    sort_month: 9,
    sort_day: 4,
    era: "ce",
    precision: "day",
    approximate: false,
    themes: ["western-collapse", "state-transformation", "continuity"],
    created_at: now,
    updated_at: now,
  },
];

export const riseOfRomeSourceTemplates: HistorySourceTemplate[] = [
  {
    id: "source-free-use-roman-history-summary",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-origins",
    title: "Free-use Roman History summary",
    source_type: "secondary",
    author: "BinderNotes source packet",
    date_label: "Teaching summary",
    audience: "History learners",
    purpose:
      "To synthesize Rome's origin myth, republican expansion, Punic Wars, imperial transition, and western collapse in one concise narrative.",
    point_of_view: "Educational historical synthesis.",
    context_note: "Used as the backbone source for this public Rise of Rome showcase binder.",
    reliability_note:
      "Good for structured learning and chronology; pair with primary-source excerpts for close interpretation tasks.",
    citation_url: null,
    quote_text:
      "Rome's story can be traced from legendary foundations through republican expansion, imperial consolidation, and the western collapse.",
    claim_supports:
      "A timeline-plus-evidence approach helps students connect chronology, causation, and interpretation.",
    claim_challenges: "Rome is best learned as disconnected trivia facts.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-romulus-myth",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-origins",
    title: "Livy's account of Rome's origins",
    source_type: "secondary",
    author: "Livy (via Book 1 traditions)",
    date_label: "Late 1st century BCE / early 1st century CE",
    audience: "Roman readers reflecting on early city origins",
    purpose: "To preserve collective memory about legitimacy and civic identity.",
    point_of_view: "Elite Roman historical narrative.",
    context_note: "Written to explain how Rome became politically durable over time.",
    reliability_note: "Useful for civic meaning, weaker for literal fact-checking.",
    citation_url: null,
    quote_text: "The legend of Romulus and Remus tells how Rome imagined its origin in danger, exile, and renewal.",
    claim_supports:
      "The city's founding memory functioned as a moral and political guide for later Roman institutions.",
    claim_challenges: "Every detail of the legend is literal history.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-punic-wars-primary",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-punic-wars",
    title: "Polybius on Roman expansion",
    source_type: "secondary",
    author: "Polybius",
    date_label: "2nd century BCE",
    audience: "Greek and Roman political readers",
    purpose: "To explain how Roman institutions supported military and diplomatic expansion.",
    point_of_view: "Greek observer comparing states.",
    context_note: "Polybius explains Rome's broad rise through practical governance and military discipline.",
    reliability_note: "Strong macro-view, though still shaped by elite strategic priorities.",
    citation_url: null,
    quote_text: "Rome's mixed government and disciplined citizen body help sustain its long campaigns.",
    claim_supports: "Institutional structure mattered as much as battlefield luck.",
    claim_challenges: "The republic was simply a passive victim of Carthaginian choices.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-caesar-commentaries",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Caesar's commentaries",
    source_type: "primary",
    author: "Julius Caesar",
    date_label: "1st century BCE",
    audience: "Roman and political readers",
    purpose: "To justify military campaigns and command authority.",
    point_of_view: "Self-presentation of a campaigning general.",
    context_note: "Written as military reporting and political argument.",
    reliability_note: "Excellent for ambition and framing, not neutral as a public record.",
    citation_url: null,
    quote_text:
      "Caesar's Gallic campaigns became both military proof and political capital for late-republican power struggles.",
    claim_supports:
      "Military victories built personal loyalty among troops and raised questions about republican balance.",
    claim_challenges: "Caesar's writings show the republic already stable and functional in late years.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-res-gestae",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Res Gestae",
    source_type: "primary",
    author: "Augustus",
    date_label: "9 BCE",
    audience: "Roman population and political audience",
    purpose: "To present imperial legitimacy and public works as lawful restoration.",
    point_of_view: "Imperial self-presentation.",
    context_note: "Written as a formal summary of achievements and leadership.",
    reliability_note: "Critical for official claims, best paired with external evidence and criticism.",
    citation_url: null,
    quote_text: "The principate is presented as restoration after upheaval.",
    claim_supports:
      "Augustus linked central authority to stability while preserving republican language.",
    claim_challenges: "The new order was purely ceremonial with no change in real power.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-edict-milan",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-crisis-constantine",
    title: "Imperial policy after Constantine",
    source_type: "secondary",
    author: "Modern synthesis",
    date_label: "Contemporary interpretation",
    audience: "History students and civic readers",
    purpose: "To connect legal religion policy to imperial reorganization.",
    point_of_view: "Comparative late-antique analysis.",
    context_note:
      "Used to show why empire-wide religious policy changed along with administrative structure.",
    reliability_note: "A modern synthesis should be checked against legal and documentary evidence.",
    citation_url: null,
    quote_text: "Edict-level policy made Christianity central to late imperial legitimacy.",
    claim_supports: "Religion became part of statecraft in the fourth century transformation.",
    claim_challenges: "The late antique empire changed only through theology.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-ammi-city-view",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-fall-west",
    title: "Ammianus and the late empire under strain",
    source_type: "primary",
    author: "Ammianus Marcellellus",
    date_label: "Late 4th century CE",
    audience: "Military and educated elite readers",
    purpose: "To explain military and frontier strain with close attention to leadership and instability.",
    point_of_view: "Elite observer inside the Roman military-administrative world.",
    context_note: "Used to teach that decline is cumulative and contested.",
    reliability_note: "Very useful for internal pressures, though no neutral outsider account.",
    citation_url: null,
    quote_text:
      "The western state could no longer coordinate expansion, frontiers, and revenue in the same way.",
    claim_supports: "The collapse came through layered fiscal, military, and political pressures.",
    claim_challenges: "Fall happened only as one sudden military surprise.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-anti-monarchy-republic",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-foundation-kingdom",
    title: "The Republic against kingship",
    source_type: "secondary",
    author: "BinderNotes source packet",
    date_label: "Teaching synthesis",
    audience: "History learners",
    purpose: "To connect the Tarquin story to republican offices and anti-monarchical political identity.",
    point_of_view: "Educational historical synthesis.",
    context_note: "Use this card when explaining why the republic defines itself against monarchy.",
    reliability_note: "Strong for conceptual framing; primary stories about the kings remain legendary and moralized.",
    citation_url: null,
    quote_text: "The Republic formed its identity by warning Romans against the return of kings.",
    claim_supports: "The Republic formed in opposition to monarchy.",
    claim_challenges: "The move from kings to republic was only an administrative reshuffle.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-expansion-destabilizes-republic",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-caesar-augustus",
    title: "Expansion and republican strain",
    source_type: "secondary",
    author: "BinderNotes source packet",
    date_label: "Teaching synthesis",
    audience: "History learners",
    purpose: "To show how empire abroad changed wealth, landholding, military service, and elite competition at home.",
    point_of_view: "Cause-effect historical synthesis.",
    context_note: "Use this source with the Republic to Empire argument chain.",
    reliability_note: "Good for causal structure; pair with specific reform and civil-war evidence for essays.",
    citation_url: null,
    quote_text: "Overseas victory brought wealth and pressure into the same republican system.",
    claim_supports: "Overseas expansion increased wealth but destabilized Roman politics.",
    claim_challenges: "Conquest only made the republic stronger and more stable.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-eastern-roman-continuation",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-fall-west",
    title: "Eastern Roman continuation",
    source_type: "secondary",
    author: "BinderNotes source packet",
    date_label: "Late antique and Byzantine synthesis",
    audience: "History learners",
    purpose: "To prevent 476 from being mistaken for the end of all Roman state tradition.",
    point_of_view: "Continuity-and-change interpretation.",
    context_note: "Use this source when comparing the western imperial office to the continuing eastern empire.",
    reliability_note: "Strong for correcting the common 476 oversimplification.",
    citation_url: null,
    quote_text: "The western office ended, but the Roman state continued from Constantinople.",
    claim_supports: "Roman civilization did not simply vanish because the Eastern Roman Empire continued.",
    claim_challenges: "Roman civilization ended everywhere in 476.",
    created_at: now,
    updated_at: now,
  },
];

export const riseOfRomeMythCheckTemplates: HistoryMythCheckTemplate[] = [
  {
    id: "rome-myth-romulus-literal-proof",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-myth-vs-history",
    myth_text: "Romulus and Remus prove the literal details of Rome's founding.",
    corrected_claim:
      "The foundation story is a powerful origin myth; archaeological evidence supports early settlement growth, not the literal twins-and-wolf narrative.",
    status: "myth",
    explanation:
      "Use the legend to study Roman identity and values, then use material evidence to study what can be historically tested.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rome-renaissance-myth-origin",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-myth-vs-history",
    myth_text: "The Roman Republic to Empire was a smooth, peaceful transition.",
    corrected_claim:
      "The transition followed decades of civil conflict, social competition, and concentrated military power.",
    status: "myth",
    explanation:
      "The period was marked by repeated crises and power struggles, even when order eventually returned under Augustus.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rome-myth-fall",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-myth-vs-history",
    myth_text: "Rome fell in a single moment when the west collapsed in 476.",
    corrected_claim:
      "The western empire unraveled slowly through fiscal strain, frontier pressure, and political reorganization.",
    status: "oversimplification",
    explanation:
      "476 marks a symbolic end of office, not a single cause that can explain all of Roman change.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rome-myth-fall-entire-civilization",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-myth-vs-history",
    myth_text: "Roman civilization disappeared after the western collapse.",
    corrected_claim:
      "Roman law, institutions, religion, and elite culture remained alive and transformed in the east and successor states.",
    status: "myth",
    explanation:
      "Byzantium and many regional traditions continued to carry Roman administrative and legal legacies for centuries.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rome-myth-republic-naturally-became-empire",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-myth-vs-history",
    myth_text: "The Republic naturally became the Empire because Rome simply got bigger.",
    corrected_claim:
      "The imperial transition came through conflict: expansion, inequality, reform crisis, military politics, and civil war made Augustus' settlement possible.",
    status: "oversimplification",
    explanation:
      "Size mattered, but the key story is institutional strain and political violence, not automatic growth.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rome-myth-republic-benefit",
    suite_template_id: SYSTEM_SUITE_IDS.riseOfRome,
    binder_id: SYSTEM_BINDER_IDS.riseOfRome,
    lesson_id: "lesson-rome-myth-vs-history",
    myth_text: "Rome's expansion only created prosperity, never social instability.",
    corrected_claim:
      "Wider warfare and wealth created opportunities but also sharpened inequality, elite rivalry, and military dependency.",
    status: "oversimplification",
    explanation:
      "Imperial growth brought power and resources, and also deeper political friction inside the Roman elite system.",
    created_at: now,
    updated_at: now,
  },
];

export const riseOfRomeLessons = demoLessons.filter((lesson) => lesson.binder_id === SYSTEM_BINDER_IDS.riseOfRome);

export const historyPresetDefinitions: WorkspacePresetDefinition[] = [
  {
    id: "history-guided",
    suiteTemplateId: SYSTEM_SUITE_IDS.historyDemo,
    title: "History Guided",
    description: "A calm four-panel history study layout with chronology in front and evidence close behind.",
    style: "guided",
    lockMode: "locked",
    requiredPanels: ["history-timeline", "history-evidence", "history-argument", "history-myth-checks"],
    breakpoints: {
      desktop: {
        columns: 12,
        rowHeight: 84,
        gap: 16,
        items: [
          { panelId: "history-timeline", panelType: "history-timeline", x: 0, y: 0, w: 7, h: 8, minW: 4, minH: 4 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 7, y: 0, w: 5, h: 5, minW: 3, minH: 3 },
          { panelId: "history-argument", panelType: "history-argument", x: 0, y: 8, w: 8, h: 6, minW: 4, minH: 4 },
          { panelId: "history-myth-checks", panelType: "history-myth-checks", x: 8, y: 8, w: 4, h: 6, minW: 3, minH: 3 },
        ],
      },
      tablet: {
        columns: 8,
        rowHeight: 88,
        gap: 14,
        items: [
          { panelId: "history-timeline", panelType: "history-timeline", x: 0, y: 0, w: 8, h: 6, minW: 4, minH: 4 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 0, y: 6, w: 8, h: 5, minW: 4, minH: 3 },
          { panelId: "history-argument", panelType: "history-argument", x: 0, y: 11, w: 8, h: 5, minW: 4, minH: 4 },
          { panelId: "history-myth-checks", panelType: "history-myth-checks", x: 0, y: 16, w: 8, h: 4, minW: 4, minH: 3 },
        ],
      },
      mobile: {
        columns: 4,
        rowHeight: 104,
        gap: 12,
        items: [
          { panelId: "history-timeline", panelType: "history-timeline", x: 0, y: 0, w: 4, h: 5, minW: 4, minH: 3 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 0, y: 5, w: 4, h: 4, minW: 4, minH: 3 },
          { panelId: "history-argument", panelType: "history-argument", x: 0, y: 9, w: 4, h: 5, minW: 4, minH: 4 },
          { panelId: "history-myth-checks", panelType: "history-myth-checks", x: 0, y: 14, w: 4, h: 4, minW: 4, minH: 3 },
        ],
      },
    },
  },
  {
    id: "history-timeline-focus",
    suiteTemplateId: SYSTEM_SUITE_IDS.historyDemo,
    title: "History Timeline Focus",
    description: "A chronology-first preset with evidence and argument nearby.",
    style: "flexible",
    lockMode: "locked",
    requiredPanels: ["history-timeline", "history-evidence", "history-argument"],
    breakpoints: {
      desktop: {
        columns: 12,
        rowHeight: 84,
        gap: 16,
        items: [
          { panelId: "history-timeline", panelType: "history-timeline", x: 0, y: 0, w: 8, h: 10, minW: 5, minH: 5 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 8, y: 0, w: 4, h: 5, minW: 3, minH: 3 },
          { panelId: "history-argument", panelType: "history-argument", x: 8, y: 5, w: 4, h: 5, minW: 3, minH: 4 },
        ],
      },
    },
  },
  {
    id: "history-source-evidence",
    suiteTemplateId: SYSTEM_SUITE_IDS.historyDemo,
    title: "History Source Evidence",
    description: "Source-first preset for close reading, evidence storage, and claim testing.",
    style: "flexible",
    lockMode: "locked",
    requiredPanels: ["history-evidence", "history-argument", "lesson"],
    breakpoints: {
      desktop: {
        columns: 12,
        rowHeight: 84,
        gap: 16,
        items: [
          { panelId: "lesson", panelType: "lesson", x: 0, y: 0, w: 4, h: 9, minW: 4, minH: 5 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 4, y: 0, w: 4, h: 9, minW: 4, minH: 5 },
          { panelId: "history-argument", panelType: "history-argument", x: 8, y: 0, w: 4, h: 9, minW: 3, minH: 5 },
        ],
      },
    },
  },
  {
    id: "history-argument-builder",
    suiteTemplateId: SYSTEM_SUITE_IDS.historyDemo,
    title: "History Argument Builder",
    description: "A writing-heavy layout with evidence and chronology still reachable.",
    style: "flexible",
    lockMode: "locked",
    requiredPanels: ["history-argument", "history-evidence", "history-timeline"],
    breakpoints: {
      desktop: {
        columns: 12,
        rowHeight: 84,
        gap: 16,
        items: [
          { panelId: "history-argument", panelType: "history-argument", x: 0, y: 0, w: 7, h: 10, minW: 5, minH: 5 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 7, y: 0, w: 5, h: 5, minW: 4, minH: 4 },
          { panelId: "history-timeline", panelType: "history-timeline", x: 7, y: 5, w: 5, h: 5, minW: 4, minH: 4 },
        ],
      },
    },
  },
  {
    id: "history-full-studio",
    suiteTemplateId: SYSTEM_SUITE_IDS.historyDemo,
    title: "History Full Studio",
    description: "The most expansive history preset, balancing source, timeline, argument, and myth evaluation.",
    style: "full-studio",
    lockMode: "locked",
    requiredPanels: ["lesson", "history-timeline", "history-evidence", "history-argument", "history-myth-checks"],
    breakpoints: {
      desktop: {
        columns: 12,
        rowHeight: 84,
        gap: 16,
        items: [
          { panelId: "lesson", panelType: "lesson", x: 0, y: 0, w: 3, h: 6, minW: 3, minH: 4 },
          { panelId: "history-timeline", panelType: "history-timeline", x: 3, y: 0, w: 5, h: 6, minW: 4, minH: 4 },
          { panelId: "history-evidence", panelType: "history-evidence", x: 8, y: 0, w: 4, h: 6, minW: 3, minH: 4 },
          { panelId: "history-argument", panelType: "history-argument", x: 0, y: 6, w: 8, h: 6, minW: 5, minH: 5 },
          { panelId: "history-myth-checks", panelType: "history-myth-checks", x: 8, y: 6, w: 4, h: 6, minW: 3, minH: 4 },
        ],
      },
    },
  },
];

export const knownSystemBinderIds = new Set<string>(Object.values(SYSTEM_BINDER_IDS));
export const knownSystemSuiteIds = new Set<string>(Object.values(SYSTEM_SUITE_IDS));
