import type {
  Binder,
  BinderLesson,
  ConceptEdge,
  ConceptNode,
  HistoryEventTemplate,
  HistoryMythCheckTemplate,
  HistorySourceTemplate,
} from "@/types";
import type { JSONContent } from "@tiptap/react";

const now = new Date().toISOString();

export const RUSSIAN_REVOLUTION_BINDER_ID = "binder-russian-revolution";
export const RUSSIAN_REVOLUTION_SUITE_ID = "suite-history-demo";

function textNode(text: string): JSONContent {
  return { type: "text", text };
}

function paragraph(text: string): JSONContent {
  return { type: "paragraph", content: [textNode(text)] };
}

function heading(text: string, level = 2): JSONContent {
  return { type: "heading", attrs: { level }, content: [textNode(text)] };
}

function subheading(text: string): JSONContent {
  return heading(text, 3);
}

function bulletList(items: string[]): JSONContent {
  return {
    type: "bulletList",
    content: items.map((item) => ({ type: "listItem", content: [paragraph(item)] })),
  };
}

function orderedList(items: string[]): JSONContent {
  return {
    type: "orderedList",
    attrs: { start: 1 },
    content: items.map((item) => ({ type: "listItem", content: [paragraph(item)] })),
  };
}

function blockquote(text: string): JSONContent {
  return { type: "blockquote", content: [paragraph(text)] };
}

function lessonDoc(...content: JSONContent[]): JSONContent {
  return { type: "doc", content };
}

function sourceBase(): JSONContent[] {
  return [
    heading("Open source base"),
    paragraph(
      "This set uses open or publicly accessible teaching and primary-source collections for its backbone: OpenStax World History, Encyclopaedia Britannica for chronology checks, Seventeen Moments in Soviet History, Yale Avalon, Marxists Internet Archive, and 1914-1918 Online.",
    ),
  ];
}

function featureGuide(): JSONContent[] {
  return [
    heading("Use the History Suite"),
    bulletList([
      "Timeline: follow causes, flashpoints, and consequences from 1861 to 1924.",
      "Evidence: compare decrees, manifestos, and historical synthesis before making claims.",
      "Argument builder: turn a chain of events into a defensible thesis.",
      "Myth checks: separate memorable one-liners from evidence-supported history.",
      "Related concepts: use people, institutions, places, and ideas as a map of the topic.",
    ]),
  ];
}

export const russianRevolutionBinder: Binder = {
  id: RUSSIAN_REVOLUTION_BINDER_ID,
  owner_id: "demo-admin",
  suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
  title: "The Russian Revolution",
  slug: "the-russian-revolution",
  description:
    "From Imperial Collapse to Bolshevik Power, 1861-1924. A premium History Suite set with timeline, evidence, people, causes, civil war, historiography, practice, and DBQ prompts.",
  subject: "History",
  level: "Modern World History",
  status: "published",
  price_cents: 0,
  cover_url:
    "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1400&q=82",
  pinned: true,
  created_at: now,
  updated_at: now,
};

export const russianRevolutionLessons: BinderLesson[] = [
  {
    id: "lesson-russian-revolution-overview",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Overview: From Imperial Collapse to Bolshevik Power",
    order_index: 1,
    is_preview: true,
    content: lessonDoc(
      heading("What was the Russian Revolution?"),
      paragraph(
        "The Russian Revolution was not one clean moment. It was a chain of crises that broke the Romanov monarchy, produced a fragile democratic experiment, and then brought the Bolsheviks to power in the middle of war, hunger, land conflict, and collapsing authority.",
      ),
      paragraph(
        "The story matters globally because it created the first durable communist state, redefined twentieth-century politics, shaped anti-colonial and labor movements, and turned ideology into a central axis of world conflict.",
      ),
      ...featureGuide(),
      heading("Core argument"),
      blockquote(
        "Russia did not become revolutionary because one cause acted alone. Autocracy, land hunger, industrial unrest, war, weak institutions, and Bolshevik organization converged when the state lost the trust of soldiers, workers, and peasants.",
      ),
      ...sourceBase(),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-long-term-causes",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Long-Term Causes: Autocracy, Land, Labor, and Ideas",
    order_index: 2,
    is_preview: false,
    content: lessonDoc(
      heading("Romanov autocracy"),
      paragraph(
        "The tsarist state concentrated authority in the monarch, police, bureaucracy, army, and Orthodox legitimacy. Reform was possible, but it remained controlled from above and could be reversed when rulers feared disorder.",
      ),
      heading("Serfdom and the unfinished land question"),
      paragraph(
        "The emancipation of the serfs in 1861 ended legal bondage, but it did not end rural grievance. Redemption payments, communal obligations, unequal landholding, and population pressure kept land hunger central to peasant politics.",
      ),
      heading("Industrialization without political trust"),
      bulletList([
        "Sergei Witte's state-led industrialization expanded railways, factories, and urban labor.",
        "Industrial growth produced concentrated worker communities that could strike, organize, and share radical ideas quickly.",
        "Modern economic change collided with an old political system that offered few legitimate channels for opposition.",
      ]),
      heading("Nationalities and Russification"),
      paragraph(
        "The empire ruled Poles, Finns, Ukrainians, Jews, Balts, Caucasian peoples, Central Asians, and many others. Russification and uneven rights made imperial loyalty fragile, especially when war exposed the center's weakness.",
      ),
      heading("Revolutionary movements and Marxism"),
      paragraph(
        "Populists, Socialist Revolutionaries, liberals, Mensheviks, and Bolsheviks disagreed on strategy and social base. Marxism became distinctive in Russia because activists adapted a theory built around industrial capitalism to a vast peasant empire.",
      ),
      subheading("Cause map"),
      bulletList([
        "Autocracy limited peaceful reform.",
        "Land hunger kept peasant pressure alive.",
        "Industrialization created worker unrest and urban organization.",
        "Russification linked social protest to national grievance.",
        "Revolutionary parties supplied language, organization, and strategy.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-1905",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "1905 Revolution: Rehearsal, Warning, and Missed Reform",
    order_index: 3,
    is_preview: false,
    content: lessonDoc(
      heading("War defeat opens a domestic crisis"),
      paragraph(
        "The Russo-Japanese War damaged the regime's prestige and intensified discontent. Bloody Sunday transformed a loyal petition movement into a national crisis when peaceful demonstrators were met with violence.",
      ),
      heading("What 1905 introduced"),
      bulletList([
        "Soviets: councils of workers and soldiers became a flexible form of revolutionary organization.",
        "October Manifesto: the tsar promised civil liberties and a Duma under pressure.",
        "Duma politics: representative institutions appeared, but the monarchy kept decisive power.",
      ]),
      heading("Why it failed but mattered"),
      paragraph(
        "The 1905 Revolution failed to remove the monarchy because the army largely held, opposition forces remained divided, and the tsarist state recovered enough coercive power. It mattered because it revealed the repertoire of 1917: strikes, soviets, military pressure, concessions, and distrust.",
      ),
      subheading("Evidence question"),
      paragraph(
        "When reading the October Manifesto, ask whether it created constitutional rule or bought time for an autocracy under pressure.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-wwi-collapse",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "World War I and the Collapse of Tsarism",
    order_index: 4,
    is_preview: false,
    content: lessonDoc(
      heading("War turned weakness into collapse"),
      paragraph(
        "Russia entered World War I with huge manpower but major logistical, administrative, and industrial limits. Losses, shortages, inflation, and transport breakdowns made daily life political.",
      ),
      heading("Leadership failures"),
      bulletList([
        "Nicholas II took personal command at the front in 1915, tying his legitimacy to military outcomes.",
        "Alexandra's reliance on Rasputin deepened rumors and elite distrust while the tsar was absent.",
        "Food shortages and fuel problems made Petrograd especially volatile.",
        "Soldiers' morale collapsed as war aims felt less connected to survival.",
      ]),
      heading("Interpretive point"),
      paragraph(
        "World War I did not invent Russia's problems, but it compressed them. It made state failure visible to workers, peasants, soldiers, elites, and national minorities at the same time.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-february",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "February Revolution: Bread, Mutiny, Abdication, Dual Power",
    order_index: 5,
    is_preview: false,
    content: lessonDoc(
      heading("Petrograd erupts"),
      paragraph(
        "The February Revolution began with strikes and bread demonstrations, including women workers whose protest turned International Women's Day into a revolutionary opening. As soldiers refused to fire and began mutinying, the regime lost the coercive core that had saved it in 1905.",
      ),
      heading("Abdication and the Romanov end"),
      paragraph(
        "Nicholas II abdicated in March 1917. The Duma-linked Provisional Government claimed formal authority, while the Petrograd Soviet represented organized workers and soldiers. Russia now lived under dual power.",
      ),
      heading("Dual power problem"),
      bulletList([
        "The Provisional Government wanted order, legal continuity, and continued war participation.",
        "The Petrograd Soviet had street legitimacy, worker support, and soldier influence.",
        "Neither body fully controlled the revolution's social demands: peace, land, bread, and authority.",
      ]),
      subheading("Timeline lens"),
      paragraph(
        "Watch how fast authority changes: protest, mutiny, abdication, new government, and soviet power all unfold in days.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-lenin-strategy",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Lenin and Bolshevik Strategy",
    order_index: 6,
    is_preview: false,
    content: lessonDoc(
      heading("Lenin returns"),
      paragraph(
        "Lenin returned from exile in April 1917 and pushed the Bolsheviks away from cautious cooperation. His April Theses rejected support for the Provisional Government and argued that soviets, not parliamentary liberalism, should become the basis of revolutionary power.",
      ),
      heading("Why the slogans worked"),
      bulletList([
        "Peace: immediate answer to war exhaustion.",
        "Land: direct answer to peasant hunger and estate seizure.",
        "Bread: direct answer to urban scarcity.",
        "All Power to the Soviets: a political formula that seemed more democratic than ministerial reshuffling.",
      ]),
      heading("Organization and timing"),
      paragraph(
        "The Bolsheviks were not the largest force in February. Their advantage was disciplined messaging, local organization, willingness to exploit government crisis, and a strategy that treated timing as decisive.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-july-kornilov",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "July Days and Kornilov Affair: Crisis Before October",
    order_index: 7,
    is_preview: false,
    content: lessonDoc(
      heading("July Days"),
      paragraph(
        "In July 1917, armed workers and soldiers demonstrated in Petrograd, some demanding soviet power. The Bolsheviks were blamed, repressed, and temporarily weakened. Lenin fled, and the party learned that revolutionary pressure without a clear transfer plan could backfire.",
      ),
      heading("Kornilov Affair"),
      paragraph(
        "General Lavr Kornilov's attempted move against Petrograd made counterrevolution feel immediate. Kerensky relied on soviets and Bolshevik activists to resist it, which helped rehabilitate the Bolsheviks and discredit the Provisional Government.",
      ),
      heading("Why these crises matter"),
      bulletList([
        "The Provisional Government looked unable to control either left or right.",
        "The Bolsheviks gained credibility as defenders of the revolution.",
        "The phrase All Power to the Soviets became more plausible after the Kornilov scare.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-october",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "October Revolution: Coup, Revolution, or Both?",
    order_index: 8,
    is_preview: false,
    content: lessonDoc(
      heading("Seizing the key points"),
      paragraph(
        "The Military Revolutionary Committee coordinated the October seizure of bridges, rail stations, telegraph offices, and other strategic points in Petrograd. The Winter Palace became the symbolic endpoint, but much of the practical takeover had already happened around the city.",
      ),
      heading("Second Congress of Soviets"),
      paragraph(
        "The Bolsheviks presented the new government to the Congress of Soviets as soviet power. Mensheviks and many Socialist Revolutionaries walked out, turning a contested socialist movement into a Bolshevik-led state project.",
      ),
      heading("How to frame the debate"),
      bulletList([
        "Coup argument: a disciplined party used a military committee to seize power from a weak government.",
        "Mass revolution argument: Bolshevik slogans drew real support from workers, soldiers, and parts of the soviet movement.",
        "Balanced conclusion: October can be both a party-led seizure and a revolutionary moment rooted in mass wartime crisis.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-consolidation",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Bolshevik Consolidation: Peace, Land, Assembly, Cheka",
    order_index: 9,
    is_preview: false,
    content: lessonDoc(
      heading("First decrees"),
      paragraph(
        "The Decrees on Peace and Land translated the Bolsheviks' most successful promises into state action. They also revealed a tension: the new regime claimed soviet democracy while concentrating decisions in Bolshevik hands.",
      ),
      heading("Constituent Assembly and coercion"),
      bulletList([
        "The Constituent Assembly was dissolved after elections did not produce a Bolshevik majority.",
        "The Cheka became an instrument for policing opposition and defending the revolution.",
        "Censorship and party control narrowed the space for rival socialist and liberal politics.",
      ]),
      heading("Brest-Litovsk"),
      paragraph(
        "The Treaty of Brest-Litovsk delivered peace with Germany at a severe territorial and political cost. It ended Russia's war but intensified civil-war legitimacy battles.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-civil-war",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Russian Civil War: Reds, Whites, War Communism, Red Terror",
    order_index: 10,
    is_preview: false,
    content: lessonDoc(
      heading("Reds versus Whites"),
      paragraph(
        "The Civil War pitted the Bolshevik Reds against diverse White forces, nationalist movements, foreign interventions, and local armed groups. The Whites were united against Bolshevism but divided over monarchy, land, nationalism, and future politics.",
      ),
      heading("Why the Bolsheviks won"),
      orderedList([
        "They held central territory, rail hubs, and major cities.",
        "Trotsky organized the Red Army with discipline and mobility.",
        "White armies were geographically dispersed and politically divided.",
        "Bolshevik land policy and anti-White propaganda helped prevent a unified peasant turn to the Whites.",
        "War Communism and coercion extracted resources at brutal cost.",
      ]),
      heading("Consequence"),
      paragraph(
        "Civil war hardened the new regime. Emergency centralization, terror, censorship, and military discipline became habits of rule rather than temporary improvisations.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-nep-ussr",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Kronstadt, NEP, USSR, and Lenin's Death",
    order_index: 11,
    is_preview: false,
    content: lessonDoc(
      heading("Kronstadt warning"),
      paragraph(
        "The Kronstadt rebellion in 1921 showed that even groups once associated with revolutionary legitimacy could turn against Bolshevik rule. It revealed the exhaustion produced by War Communism and civil-war coercion.",
      ),
      heading("New Economic Policy"),
      paragraph(
        "The NEP retreated from the harshest requisitioning and allowed limited market activity while the Communist Party kept political monopoly. It was both pragmatic survival and ideological tension.",
      ),
      heading("USSR and succession"),
      bulletList([
        "The USSR formed in 1922 as a federal union in theory, but party power remained central.",
        "Lenin's death in 1924 turned succession into the next major political problem.",
        "Stalin's role as General Secretary positioned him to build networks of institutional power.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-key-people",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Key People Cards",
    order_index: 12,
    is_preview: false,
    content: lessonDoc(
      heading("How to use people cards"),
      paragraph(
        "Treat each figure as a point in a network. Ask what institution they controlled, what crisis exposed them, and how their choices changed the timing of events.",
      ),
      subheading("Imperial and pre-revolutionary figures"),
      bulletList([
        "Nicholas II: last tsar; his inflexibility, war leadership, and abdication mark the end of Romanov rule.",
        "Alexandra Feodorovna: empress whose wartime role and closeness to Rasputin damaged elite confidence.",
        "Rasputin: holy man and court adviser whose influence became a symbol of court dysfunction.",
        "Alexander III: conservative tsar whose repression shaped the political climate inherited by Nicholas II.",
        "Sergei Witte: modernizer tied to industrial growth, railway expansion, and the October Manifesto compromise.",
      ]),
      subheading("Revolutionary and civil-war figures"),
      bulletList([
        "Lenin: Bolshevik strategist who pushed soviet power, peace, land, and party seizure of power.",
        "Trotsky: Petrograd Soviet leader and organizer of the Red Army.",
        "Kerensky: Provisional Government leader trapped between war, reform, soviets, and the right.",
        "Kornilov: general whose failed move helped the Bolsheviks regain revolutionary credibility.",
        "Stalin: Bolshevik organizer whose postwar party office mattered for succession.",
        "Martov: Menshevik critic of Bolshevik one-party power.",
        "Plekhanov: pioneer of Russian Marxism who opposed Lenin's 1917 course.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-geography-concepts",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Maps, Geography, and Related Concepts",
    order_index: 13,
    is_preview: false,
    content: lessonDoc(
      heading("Geography of revolution"),
      bulletList([
        "Petrograd: capital city where strikes, soviets, mutiny, and the October seizure converged.",
        "Moscow: second revolutionary center and later Soviet capital.",
        "Kronstadt: naval fortress whose 1921 rebellion became a warning about revolutionary disillusion.",
        "Brest-Litovsk: treaty site that marked the cost of exiting World War I.",
        "The periphery: Ukraine, the Baltic region, Caucasus, Central Asia, and Poland show why empire and nationality mattered.",
      ]),
      heading("Related concepts map"),
      bulletList([
        "Autocracy links to weak institutions and opposition radicalization.",
        "Dual power links the Provisional Government to the Petrograd Soviet.",
        "War Communism links civil war, requisition, terror, and economic breakdown.",
        "NEP links survival, compromise, market revival, and party monopoly.",
        "Vanguard party links Leninist organization to the debate over democracy and dictatorship.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-historiography-comparisons",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Historiography and Comparison Cards",
    order_index: 14,
    is_preview: false,
    content: lessonDoc(
      heading("Major interpretations"),
      bulletList([
        "Soviet interpretation: October was a historically necessary worker-peasant revolution led by the party that understood class struggle.",
        "Liberal interpretation: February opened a possible constitutional path, while October shut down pluralism through party dictatorship.",
        "Revisionist and social-history interpretation: local workers, soldiers, peasants, women, and national groups shaped events from below, not just party leaders.",
        "October as coup: emphasizes planning, armed seizure, and minority party discipline.",
        "October as mass revolution: emphasizes war exhaustion, soviet legitimacy, Bolshevik majorities in key soviets, and popular slogans.",
      ]),
      heading("Balanced conclusion"),
      paragraph(
        "October was not a palace coup detached from society, but it was also not a simple democratic uprising. It was a party-led transfer of power made possible by mass crisis and institutional collapse.",
      ),
      heading("Comparison cards"),
      bulletList([
        "February vs October: spontaneous collapse and dual power vs organized seizure and one-party state building.",
        "Bolsheviks vs Mensheviks: centralized revolutionary party vs broader Marxist party and staged development.",
        "Provisional Government vs Petrograd Soviet: formal state authority vs street, worker, and soldier legitimacy.",
        "Tsarist autocracy vs Soviet one-party rule: personal monarchy vs party dictatorship, with different ideologies but shared centralization.",
        "1905 vs 1917: rehearsal with partial concessions vs wartime collapse and regime replacement.",
      ]),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "lesson-russian-revolution-practice",
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    title: "Vocabulary, Practice, DBQ, and Why It Matters",
    order_index: 15,
    is_preview: false,
    content: lessonDoc(
      heading("Vocabulary"),
      bulletList([
        "Autocracy: government where supreme authority is concentrated in one ruler.",
        "Soviet: council representing workers, soldiers, or peasants.",
        "Proletariat: industrial working class in Marxist analysis.",
        "Bourgeoisie: property-owning capitalist class in Marxist analysis.",
        "Bolshevik: Lenin's faction favoring a disciplined revolutionary party.",
        "Menshevik: rival socialist faction favoring broader party organization and a different revolutionary timetable.",
        "Duma: representative assembly created after 1905 but constrained by tsarist authority.",
        "Dual power: coexistence of Provisional Government authority and Soviet legitimacy in 1917.",
        "Marxism: theory of class conflict and historical change rooted in capitalist development.",
        "Socialism: broad ideology seeking social ownership or control of production.",
        "Communism: classless society as ultimate revolutionary goal; in practice, party-state rule in Soviet Russia.",
        "Cheka: Bolshevik political police created to defend the revolution.",
        "War Communism: civil-war policies of requisition, nationalization, and coercive control.",
        "NEP: New Economic Policy, allowing limited market activity after civil-war crisis.",
        "Vanguard party: disciplined revolutionary party claiming to lead class struggle.",
        "Constituent Assembly: elected body dissolved by Bolshevik force in January 1918.",
      ]),
      heading("10 multiple-choice questions"),
      orderedList([
        "Which reform ended legal serfdom in Russia? A. October Manifesto B. Emancipation of 1861 C. NEP D. Brest-Litovsk",
        "Bloody Sunday mattered because it: A. ended the Civil War B. turned loyal petition into revolutionary crisis C. created the USSR D. began NEP",
        "Dual power refers to: A. two tsars B. Provisional Government and Petrograd Soviet C. Reds and Whites D. Germany and Russia",
        "Lenin's April Theses called for: A. support for the Provisional Government B. soviet power and no support for the Provisional Government C. return to monarchy D. alliance with Kornilov",
        "The Kornilov Affair helped the Bolsheviks by: A. discrediting counterrevolution and Kerensky B. restoring Nicholas II C. ending land hunger D. abolishing soviets",
        "The October Revolution took place in November by the Gregorian calendar because: A. Russia used the Julian calendar B. it lasted one year C. Germany renamed it D. the Duma changed the date",
        "The Treaty of Brest-Litovsk did what? A. kept Russia in WWI B. ended Russia's war at heavy cost C. formed the USSR D. created the Duma",
        "War Communism was mainly associated with: A. civil-war requisition and coercion B. liberal parliamentary reform C. the 1905 Manifesto D. Stolypin's parliament",
        "The NEP represented: A. complete return to capitalism B. limited market retreat under party rule C. abolition of the Communist Party D. restoration of the tsar",
        "The USSR formed in: A. 1861 B. 1905 C. 1922 D. 1991",
      ]),
      heading("Answer key with explanations"),
      bulletList([
        "1 B: emancipation attacked serfdom but left the land question unresolved.",
        "2 B: Bloody Sunday changed trust in the tsar and helped trigger national unrest.",
        "3 B: dual power is the central political structure after February.",
        "4 B: Lenin rejected coalition with the Provisional Government.",
        "5 A: the crisis made Bolsheviks look like defenders of the revolution.",
        "6 A: Old Style and New Style calendars differ by thirteen days in 1917.",
        "7 B: peace came with major territorial and political losses.",
        "8 A: War Communism belongs to civil-war emergency rule.",
        "9 B: NEP was economic compromise without political pluralism.",
        "10 C: the USSR was created in 1922.",
      ]),
      heading("Short answer prompts"),
      orderedList([
        "Explain why 1905 mattered even though it did not overthrow the tsar.",
        "How did World War I turn long-term weakness into immediate revolution?",
        "Why did dual power make stable government difficult?",
        "How did the Bolsheviks turn slogans into strategy?",
        "Why did civil war strengthen one-party habits of rule?",
      ]),
      heading("Essay prompts"),
      bulletList([
        "Was the October Revolution a popular revolution or a Bolshevik coup?",
        "To what extent did World War I cause the collapse of Tsarism?",
        "Why were the Bolsheviks able to defeat their rivals?",
      ]),
      heading("DBQ-style prompt"),
      paragraph(
        "Using the October Manifesto, Nicholas II's abdication, Lenin's April Theses, the Decrees on Peace and Land, and Brest-Litovsk, evaluate whether the Russian Revolution should be understood primarily as a response to state failure, class conflict, war, or revolutionary organization.",
      ),
      heading("5 key takeaways"),
      bulletList([
        "The revolution grew from long-term structural problems and immediate wartime collapse.",
        "1905 mattered as a rehearsal for soviets, strikes, and limited constitutional promises.",
        "February ended monarchy but did not solve war, land, bread, or authority.",
        "October was both party-led and rooted in mass crisis.",
        "Civil war and emergency rule shaped the Soviet state that followed.",
      ]),
      heading("3 big debates"),
      bulletList([
        "Was October more coup or revolution?",
        "Could February have become a stable democracy without World War I?",
        "Did Bolshevik one-party rule grow from ideology, civil-war necessity, or both?",
      ]),
      heading("Why it changed the twentieth century"),
      paragraph(
        "The Russian Revolution changed the twentieth century because it turned socialism from a movement into a state project, inspired revolutionaries and anti-revolutionaries worldwide, helped define fascism, liberal democracy, and communism against one another, and made the struggle over economic justice, political violence, and party power a global question.",
      ),
    ),
    math_blocks: [],
    created_at: now,
    updated_at: now,
  },
];

function event(
  id: string,
  lessonId: string,
  title: string,
  dateLabel: string,
  sortYear: number,
  sortMonth: number | null,
  sortDay: number | null,
  precision: HistoryEventTemplate["precision"],
  summary: string,
  significance: string,
  themes: string[],
  locationLabel = "Russian Empire",
  locationLat: number | null = 55.7558,
  locationLng: number | null = 37.6173,
  approximate = false,
): HistoryEventTemplate {
  return {
    id,
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: lessonId,
    title,
    summary,
    significance,
    location_label: locationLabel,
    location_lat: locationLat,
    location_lng: locationLng,
    date_label: dateLabel,
    sort_year: sortYear,
    sort_month: sortMonth,
    sort_day: sortDay,
    era: "ce",
    precision,
    approximate,
    themes,
    created_at: now,
    updated_at: now,
  };
}

export const russianRevolutionEventTemplates: HistoryEventTemplate[] = [
  event(
    "event-russian-1861-emancipation",
    "lesson-russian-revolution-long-term-causes",
    "Emancipation of the serfs",
    "1861",
    1861,
    3,
    3,
    "year",
    "Alexander II ends legal serfdom, but peasants remain burdened by land hunger, payments, and uneven local power.",
    "The reform weakens old bondage without creating a stable rural settlement, leaving the land question alive.",
    ["land", "peasantry", "reform", "long-term-cause"],
    "Russian Empire",
    55.7558,
    37.6173,
    true,
  ),
  event(
    "event-russian-1881-alexander-ii-assassinated",
    "lesson-russian-revolution-long-term-causes",
    "Assassination of Alexander II",
    "1881",
    1881,
    3,
    13,
    "day",
    "Revolutionaries assassinate the reforming tsar, and the next reign moves toward repression and tightened autocracy.",
    "The event deepens the regime's fear of reform and helps shape the conservative inheritance of Nicholas II.",
    ["autocracy", "terrorism", "repression", "Alexander II"],
    "St. Petersburg",
    59.9311,
    30.3609,
  ),
  event(
    "event-russian-1894-nicholas-ii",
    "lesson-russian-revolution-long-term-causes",
    "Nicholas II becomes tsar",
    "1894",
    1894,
    11,
    1,
    "year",
    "Nicholas II inherits an expanding but brittle empire with rising labor unrest, national tensions, and reform pressures.",
    "His commitment to autocracy limits the regime's ability to absorb modern political conflict.",
    ["Nicholas II", "autocracy", "Romanovs"],
    "St. Petersburg",
    59.9311,
    30.3609,
    true,
  ),
  event(
    "event-russian-1898-rsdlp",
    "lesson-russian-revolution-long-term-causes",
    "Russian Social Democratic Labour Party founded",
    "1898",
    1898,
    3,
    1,
    "year",
    "Marxist organizers create a party framework that later splits into Bolshevik and Menshevik factions.",
    "Russian Marxism gains institutional form before becoming a decisive force in 1917.",
    ["Marxism", "Bolsheviks", "Mensheviks", "revolutionary-movements"],
    "Minsk",
    53.9006,
    27.559,
    true,
  ),
  event(
    "event-russian-1904-russo-japanese-war",
    "lesson-russian-revolution-1905",
    "Russo-Japanese War",
    "1904-1905",
    1904,
    2,
    8,
    "approximate",
    "Russia's defeat by Japan exposes military weakness and humiliates an empire that expected great-power prestige.",
    "The war accelerates unrest and helps make 1905 a national revolutionary crisis.",
    ["war", "state-failure", "1905", "Nicholas II"],
    "Manchuria and Port Arthur",
    38.8,
    121.25,
    true,
  ),
  event(
    "event-russian-1905-bloody-sunday",
    "lesson-russian-revolution-1905",
    "Bloody Sunday",
    "Jan. 22, 1905",
    1905,
    1,
    22,
    "day",
    "Peaceful petitioners in St. Petersburg are fired upon by imperial troops, shattering popular trust in the tsar.",
    "A loyal appeal becomes a revolutionary rupture and opens the 1905 crisis.",
    ["Bloody Sunday", "workers", "autocracy", "1905"],
    "St. Petersburg",
    59.9311,
    30.3609,
  ),
  event(
    "event-russian-1905-october-manifesto",
    "lesson-russian-revolution-1905",
    "October Manifesto",
    "Oct. 1905",
    1905,
    10,
    30,
    "month",
    "Nicholas II promises civil liberties and a legislative Duma under pressure from strikes and unrest.",
    "The manifesto divides opposition and creates limited institutions without ending autocratic power.",
    ["Duma", "civil-liberties", "Witte", "1905"],
    "St. Petersburg",
    59.9311,
    30.3609,
    true,
  ),
  event(
    "event-russian-1914-wwi",
    "lesson-russian-revolution-wwi-collapse",
    "Russia enters World War I",
    "1914",
    1914,
    8,
    1,
    "year",
    "Russia enters the European war and soon faces enormous casualties, supply failures, inflation, and transport stress.",
    "War transforms political weakness into daily crisis for soldiers, workers, peasants, and elites.",
    ["World War I", "military", "food-shortages", "state-failure"],
    "Eastern Front",
    50.4501,
    30.5234,
    true,
  ),
  event(
    "event-russian-1915-nicholas-front",
    "lesson-russian-revolution-wwi-collapse",
    "Nicholas II takes command at the front",
    "1915",
    1915,
    9,
    5,
    "year",
    "Nicholas leaves the capital to command the army, tying the monarchy's legitimacy more directly to battlefield failure.",
    "The move weakens political management at home and magnifies Alexandra and Rasputin as targets of suspicion.",
    ["Nicholas II", "Alexandra", "Rasputin", "leadership"],
    "Mogilev headquarters",
    53.9007,
    30.3314,
    true,
  ),
  event(
    "event-russian-1917-women-bread-protests",
    "lesson-russian-revolution-february",
    "Women workers and bread protests begin",
    "Feb./Mar. 1917",
    1917,
    3,
    8,
    "day",
    "Women textile workers and crowds in Petrograd protest bread shortages, war, and the conditions of daily survival.",
    "The demonstrations help trigger a cascade from strike to revolution.",
    ["women-workers", "bread", "Petrograd", "February Revolution"],
    "Petrograd",
    59.9311,
    30.3609,
  ),
  event(
    "event-russian-1917-february-revolution",
    "lesson-russian-revolution-february",
    "February Revolution",
    "Feb./Mar. 1917",
    1917,
    3,
    12,
    "day",
    "Strikes, demonstrations, and soldier mutinies in Petrograd break the coercive backbone of the monarchy.",
    "The revolution succeeds when soldiers refuse to defend the old order.",
    ["February Revolution", "soldiers", "workers", "mutiny"],
    "Petrograd",
    59.9311,
    30.3609,
  ),
  event(
    "event-russian-1917-nicholas-abdicates",
    "lesson-russian-revolution-february",
    "Nicholas II abdicates",
    "Mar. 15, 1917",
    1917,
    3,
    15,
    "day",
    "Nicholas II abdicates, ending more than three centuries of Romanov rule.",
    "Russia enters a new political experiment without a stable settlement of war, land, bread, or authority.",
    ["Nicholas II", "Romanovs", "abdication", "dual-power"],
    "Pskov",
    57.8136,
    28.3496,
  ),
  event(
    "event-russian-1917-lenin-april-theses",
    "lesson-russian-revolution-lenin-strategy",
    "Lenin returns and issues the April Theses",
    "Apr. 1917",
    1917,
    4,
    16,
    "month",
    "Lenin returns to Russia and argues for no support to the Provisional Government and power through soviets.",
    "The Bolsheviks gain a sharper strategy that connects peace, land, bread, and soviet authority.",
    ["Lenin", "April Theses", "Bolsheviks", "soviets"],
    "Petrograd",
    59.9311,
    30.3609,
    true,
  ),
  event(
    "event-russian-1917-july-days",
    "lesson-russian-revolution-july-kornilov",
    "July Days",
    "July 1917",
    1917,
    7,
    16,
    "month",
    "Armed demonstrations in Petrograd demand soviet power, but the Bolsheviks are blamed and temporarily repressed.",
    "The crisis shows both the strength and danger of revolutionary impatience.",
    ["July Days", "Bolsheviks", "Petrograd", "dual-power"],
    "Petrograd",
    59.9311,
    30.3609,
    true,
  ),
  event(
    "event-russian-1917-kornilov-affair",
    "lesson-russian-revolution-july-kornilov",
    "Kornilov Affair",
    "Aug. 1917",
    1917,
    8,
    27,
    "month",
    "General Kornilov's attempted move against Petrograd is defeated after Kerensky relies on revolutionary forces.",
    "The affair discredits the right, weakens Kerensky, and helps the Bolsheviks regain influence.",
    ["Kornilov", "Kerensky", "counterrevolution", "Bolshevik-recovery"],
    "Petrograd",
    59.9311,
    30.3609,
    true,
  ),
  event(
    "event-russian-1917-bolshevik-majorities",
    "lesson-russian-revolution-lenin-strategy",
    "Bolsheviks gain majorities in key soviets",
    "Sept. 1917",
    1917,
    9,
    1,
    "month",
    "Bolsheviks gain majorities in the Petrograd and Moscow soviets as war-weariness and distrust deepen.",
    "Soviet legitimacy and party strategy begin to converge before October.",
    ["Bolsheviks", "soviets", "Moscow", "Petrograd"],
    "Petrograd and Moscow",
    57.0,
    34.0,
    true,
  ),
  event(
    "event-russian-1917-october-revolution",
    "lesson-russian-revolution-october",
    "October Revolution",
    "Nov. 7, 1917",
    1917,
    11,
    7,
    "day",
    "The Military Revolutionary Committee directs the seizure of strategic points in Petrograd and topples the Provisional Government.",
    "The Bolsheviks turn a legitimacy crisis into state power.",
    ["October Revolution", "Military Revolutionary Committee", "Lenin", "Trotsky"],
    "Petrograd",
    59.9311,
    30.3609,
  ),
  event(
    "event-russian-1918-constituent-assembly-dissolved",
    "lesson-russian-revolution-consolidation",
    "Constituent Assembly dissolved",
    "Jan. 1918",
    1918,
    1,
    19,
    "month",
    "The Bolsheviks dissolve the elected Constituent Assembly after it fails to give them the majority they need.",
    "The event marks a decisive move away from multiparty electoral legitimacy.",
    ["Constituent Assembly", "one-party-rule", "democracy", "Bolsheviks"],
    "Petrograd",
    59.9311,
    30.3609,
    true,
  ),
  event(
    "event-russian-1918-brest-litovsk",
    "lesson-russian-revolution-consolidation",
    "Treaty of Brest-Litovsk",
    "Mar. 1918",
    1918,
    3,
    3,
    "day",
    "The Bolshevik government signs a separate peace with the Central Powers at severe territorial cost.",
    "Ending the war fulfills a promise but intensifies opposition and civil-war polarization.",
    ["Brest-Litovsk", "peace", "World War I", "civil-war"],
    "Brest-Litovsk",
    52.0976,
    23.7341,
  ),
  event(
    "event-russian-1918-civil-war",
    "lesson-russian-revolution-civil-war",
    "Russian Civil War",
    "1918-1921",
    1918,
    6,
    1,
    "approximate",
    "Reds, Whites, foreign forces, nationalist armies, and local movements fight across the former empire.",
    "The war hardens Bolshevik institutions and makes coercion central to state survival.",
    ["Civil War", "Reds", "Whites", "foreign-intervention"],
    "Former Russian Empire",
    55.7558,
    37.6173,
    true,
  ),
  event(
    "event-russian-1918-cheka-red-terror",
    "lesson-russian-revolution-civil-war",
    "Cheka and Red Terror expand",
    "1918",
    1918,
    9,
    5,
    "year",
    "The revolutionary state expands coercive policing and terror in response to civil-war threats and opposition.",
    "Emergency violence becomes part of the structure of Bolshevik rule.",
    ["Cheka", "Red Terror", "state-power", "civil-war"],
    "Soviet Russia",
    55.7558,
    37.6173,
    true,
  ),
  event(
    "event-russian-1921-kronstadt-nep",
    "lesson-russian-revolution-nep-ussr",
    "Kronstadt rebellion and NEP",
    "1921",
    1921,
    3,
    1,
    "year",
    "Kronstadt sailors rebel, and the regime soon introduces the New Economic Policy to ease economic breakdown.",
    "The moment exposes revolutionary discontent and prompts economic retreat without political liberalization.",
    ["Kronstadt", "NEP", "War Communism", "Lenin"],
    "Kronstadt",
    59.9915,
    29.7775,
    true,
  ),
  event(
    "event-russian-1922-ussr-formed",
    "lesson-russian-revolution-nep-ussr",
    "USSR formed",
    "1922",
    1922,
    12,
    30,
    "year",
    "The Union of Soviet Socialist Republics is created, organizing former imperial spaces under a new federal and party structure.",
    "The revolution becomes a durable state with global ideological ambitions.",
    ["USSR", "nationalities", "federalism", "party-state"],
    "Moscow",
    55.7558,
    37.6173,
    true,
  ),
  event(
    "event-russian-1924-lenin-dies",
    "lesson-russian-revolution-nep-ussr",
    "Lenin dies",
    "1924",
    1924,
    1,
    21,
    "day",
    "Lenin's death opens the succession struggle that will elevate Stalin and reshape Soviet power.",
    "The revolution's founding leadership gives way to a new party-state politics of succession and consolidation.",
    ["Lenin", "Stalin", "succession", "party-state"],
    "Gorki, near Moscow",
    55.6108,
    37.8111,
  ),
];

export const russianRevolutionSourceTemplates: HistorySourceTemplate[] = [
  {
    id: "source-russian-openstax-war-ends",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-overview",
    title: "OpenStax World History: Russia and the War's End",
    source_type: "secondary",
    author: "OpenStax",
    date_label: "Open textbook",
    audience: "World history learners",
    purpose: "To synthesize war, Petrograd unrest, abdication, and Lenin's rise.",
    point_of_view: "Open educational world-history synthesis.",
    context_note: "Useful for cross-checking the February Revolution, dual power, and Bolshevik slogans.",
    reliability_note: "Strong for learner-facing chronology; pair with primary documents for DBQ claims.",
    citation_url: "https://openstax.org/books/world-history-volume-2/pages/11-5-the-war-ends",
    quote_text: null,
    claim_supports: "World War I, Petrograd protest, soldier defection, and soviet organization formed one connected crisis.",
    claim_challenges: "The revolution can be explained by ideology alone.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-britannica-revolution",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-overview",
    title: "Encyclopaedia Britannica: Russian Revolution",
    source_type: "secondary",
    author: "Britannica Editors",
    date_label: "Reference synthesis",
    audience: "General history readers",
    purpose: "To summarize causes, February, October, civil war, and chronology.",
    point_of_view: "Fact-checked reference overview.",
    context_note: "Useful for checking the overall periodization and major turning points.",
    reliability_note: "Good for overview and chronology; not a substitute for primary-source interpretation.",
    citation_url: "https://www.britannica.com/event/Russian-Revolution",
    quote_text: null,
    claim_supports: "The revolution is best understood as two revolutions in 1917 linked to wartime collapse.",
    claim_challenges: "October can be studied without February or World War I.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-october-manifesto",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-1905",
    title: "October Manifesto",
    source_type: "primary",
    author: "Nicholas II and imperial government",
    date_label: "1905",
    audience: "Subjects of the Russian Empire",
    purpose: "To calm unrest by promising civil liberties and representative institutions.",
    point_of_view: "Autocratic concession under revolutionary pressure.",
    context_note: "Issued during the 1905 Revolution after strikes and pressure made concession necessary.",
    reliability_note: "Strong evidence for the regime's promised concessions; weak as proof those promises were honored.",
    citation_url: "https://commons.wikimedia.org/wiki/File:October_Manifesto_1.jpg",
    quote_text: null,
    claim_supports: "1905 forced the monarchy to concede representation without truly surrendering autocracy.",
    claim_challenges: "The tsarist system was politically flexible enough to avoid later revolution.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-abdication-manifesto",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-february",
    title: "Nicholas II Abdication Manifesto",
    source_type: "primary",
    author: "Nicholas II",
    date_label: "1917",
    audience: "Russian people, army, and political elites",
    purpose: "To abdicate and frame the decision as service to Russia during wartime crisis.",
    point_of_view: "Monarchical self-justification at the moment authority collapsed.",
    context_note: "Produced after Petrograd unrest and elite pressure made continued rule impossible.",
    reliability_note: "Excellent for how Nicholas framed abdication; not a complete explanation of why the regime fell.",
    citation_url:
      "https://seventeenmoments.web.illinois.edu/1917-2/february-revolution/february-revolution-texts/abdication-manifesto/",
    quote_text: "We think it best to abdicate the throne.",
    claim_supports: "The February Revolution ended Romanov rule once elite and military support failed.",
    claim_challenges: "Nicholas abdicated from strength or voluntary reformist confidence.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-april-theses",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-lenin-strategy",
    title: "Lenin's April Theses",
    source_type: "primary",
    author: "Vladimir Lenin",
    date_label: "1917",
    audience: "Bolsheviks, soviets, and revolutionary socialists",
    purpose: "To redirect Bolshevik strategy toward soviet power and opposition to the Provisional Government.",
    point_of_view: "Bolshevik revolutionary leadership.",
    context_note: "Written after Lenin returned to Russia during the dual-power crisis.",
    reliability_note: "Strong for Bolshevik strategy; not a neutral account of rival socialist positions.",
    citation_url: "https://www.marxists.org/archive/lenin/works/1917/apr/07.htm",
    quote_text: "No support for the Provisional Government.",
    claim_supports: "Lenin's strategy turned dual power into a campaign for soviet authority under Bolshevik leadership.",
    claim_challenges: "The Bolsheviks merely drifted into October without a strategic line.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-decree-peace",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-consolidation",
    title: "Decree on Peace",
    source_type: "primary",
    author: "Bolshevik government / Lenin",
    date_label: "1917",
    audience: "Russian soldiers, workers, peasants, and belligerent governments",
    purpose: "To announce a revolutionary peace policy after the Bolshevik seizure of power.",
    point_of_view: "New Soviet government seeking legitimacy through peace.",
    context_note: "Presented with the Decree on Land after October.",
    reliability_note: "Strong evidence for Bolshevik promises; compare with Brest-Litovsk to evaluate outcomes.",
    citation_url: "https://encyclopedia.1914-1918-online.net/article/decree-on-peace/",
    quote_text: "peace without annexations or indemnities",
    claim_supports: "Peace was a central source of Bolshevik legitimacy after October.",
    claim_challenges: "Bolshevik consolidation was unrelated to the war question.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-decree-land",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-consolidation",
    title: "Decree on Land",
    source_type: "primary",
    author: "Bolshevik government / Lenin",
    date_label: "1917",
    audience: "Peasants, landlords, soviets, and revolutionary committees",
    purpose: "To legalize the transfer of landed estates and answer peasant land hunger.",
    point_of_view: "Bolshevik state adapting to peasant demands and Socialist Revolutionary land ideas.",
    context_note: "Issued after October to link Bolshevik rule to village revolution.",
    reliability_note: "Strong for policy direction; compare with later War Communism for implementation tension.",
    citation_url: "https://www.marxists.org/archive/lenin/works/1917/oct/25-26/26d.htm",
    quote_text: null,
    claim_supports: "Peasant land hunger was too important for any new regime to ignore.",
    claim_challenges: "October was only an urban worker revolution.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "source-russian-brest-litovsk",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-consolidation",
    title: "Treaty of Brest-Litovsk",
    source_type: "primary",
    author: "Russia and the Central Powers",
    date_label: "1918",
    audience: "Belligerent governments and public audiences",
    purpose: "To end the state of war between Soviet Russia and the Central Powers.",
    point_of_view: "Diplomatic settlement imposed under military pressure.",
    context_note: "Signed after the Bolsheviks chose survival and peace over continued war.",
    reliability_note: "Excellent for treaty terms and territorial costs; not sufficient by itself to explain civil-war politics.",
    citation_url: "https://avalon.law.yale.edu/20th_century/brest.asp",
    quote_text: "the state of war between them has ceased",
    claim_supports: "Bolshevik peace came at heavy cost and intensified legitimacy conflict.",
    claim_challenges: "Ending the war was politically simple after October.",
    created_at: now,
    updated_at: now,
  },
];

export const russianRevolutionMythCheckTemplates: HistoryMythCheckTemplate[] = [
  {
    id: "myth-russian-one-revolution",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-historiography-comparisons",
    myth_text: "The Russian Revolution was one single event.",
    corrected_claim:
      "It was a sequence of linked crises, including 1905, February 1917, October 1917, civil war, NEP, and the creation of the USSR.",
    status: "oversimplification",
    explanation:
      "A one-event story hides the changing actors and problems: monarchy, dual power, Bolshevik seizure, civil war, and state formation.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-russian-october-only-coup",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-october",
    myth_text: "October was only a coup with no social roots.",
    corrected_claim:
      "October was party-led and coup-like in method, but it drew power from war exhaustion, soviet legitimacy, worker militancy, soldier discontent, and land hunger.",
    status: "contested",
    explanation:
      "Historians disagree on emphasis. The strongest interpretation holds both the organized seizure and the mass crisis in view.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-russian-wwi-alone",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-wwi-collapse",
    myth_text: "World War I alone caused the collapse of Tsarism.",
    corrected_claim:
      "World War I was the immediate accelerator, but it acted on older problems of autocracy, land, labor unrest, nationalities, and weak institutions.",
    status: "oversimplification",
    explanation:
      "The war compressed long-term weaknesses into a crisis that many groups experienced at once.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-russian-bolsheviks-majority-communists",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-civil-war",
    myth_text: "The Bolsheviks won because most Russians were committed communists.",
    corrected_claim:
      "They won through organization, control of central territory, Red Army discipline, opponent disunity, slogans, coercion, and survival in civil war.",
    status: "myth",
    explanation:
      "Support was uneven and often conditional. Civil-war outcomes depended on logistics and rival failures as much as ideology.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-russian-nep-capitalism",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-nep-ussr",
    myth_text: "The NEP meant the Bolsheviks abandoned Bolshevism.",
    corrected_claim:
      "The NEP allowed limited market activity but preserved Communist Party monopoly and state control of commanding heights.",
    status: "oversimplification",
    explanation:
      "NEP was a strategic retreat from War Communism, not a return to political liberalism.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "myth-russian-ussr-nationalities-solved",
    suite_template_id: RUSSIAN_REVOLUTION_SUITE_ID,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    lesson_id: "lesson-russian-revolution-nep-ussr",
    myth_text: "The formation of the USSR solved the nationalities question.",
    corrected_claim:
      "The USSR created a federal framework, but nationalities policy remained a persistent tension between local identity and centralized party power.",
    status: "contested",
    explanation:
      "The formal union structure mattered, but it did not remove disputes over sovereignty, culture, coercion, and central control.",
    created_at: now,
    updated_at: now,
  },
];

const conceptDescriptions: Array<[string, string, string]> = [
  ["autocracy", "Autocracy", "Rule concentrated in the tsar, bureaucracy, police, army, and imperial legitimacy."],
  ["serfdom", "Serfdom", "Peasant bondage ended in 1861 but left a contested rural order."],
  ["land-hunger", "Peasant land hunger", "Village demand for land redistribution and security."],
  ["industrialization", "Industrialization", "State-driven growth that concentrated workers and intensified unrest."],
  ["russification", "Russification", "Policies pressuring national minorities toward Russian language, culture, and rule."],
  ["marxism", "Marxism in Russia", "Class-struggle theory adapted to a peasant-majority empire."],
  ["soviet", "Soviet", "Council of workers, soldiers, or peasants claiming revolutionary legitimacy."],
  ["duma", "Duma", "Representative assembly created after 1905 but constrained by autocracy."],
  ["dual-power", "Dual Power", "The unstable coexistence of Provisional Government and Petrograd Soviet authority."],
  ["petrograd", "Petrograd", "Capital city and center of February and October revolutionary action."],
  ["provisional-government", "Provisional Government", "Post-February government that failed to solve war, land, bread, and authority."],
  ["bolshevik", "Bolshevik", "Lenin's faction, defined by disciplined organization and revolutionary seizure strategy."],
  ["menshevik", "Menshevik", "Marxist rivals of the Bolsheviks, often favoring broader organization and staged development."],
  ["vanguard-party", "Vanguard party", "Disciplined party model claiming to lead revolutionary class struggle."],
  ["cheka", "Cheka", "Bolshevik political police created during consolidation and civil war."],
  ["war-communism", "War Communism", "Civil-war economic system of requisition, nationalization, and coercive control."],
  ["nep", "New Economic Policy", "Limited market retreat after War Communism while party monopoly stayed intact."],
  ["ussr", "USSR", "Union state formed in 1922 from Soviet republics under Communist Party power."],
  ["kronstadt", "Kronstadt", "Naval fortress whose 1921 rebellion revealed disillusionment with Bolshevik rule."],
  ["brest-litovsk", "Brest-Litovsk", "Peace treaty that ended Russia's war with Germany at major territorial cost."],
  ["nicholas-ii", "Nicholas II", "Last Romanov tsar whose war leadership and inflexibility became fatal."],
  ["alexandra", "Alexandra Feodorovna", "Empress whose wartime influence and Rasputin connection fueled distrust."],
  ["rasputin", "Rasputin", "Court holy man turned symbol of imperial dysfunction."],
  ["lenin", "Lenin", "Bolshevik strategist of soviet power, peace, land, and one-party rule."],
  ["trotsky", "Trotsky", "Petrograd Soviet leader and Red Army organizer."],
  ["kerensky", "Kerensky", "Provisional Government leader unable to resolve war and dual power."],
  ["kornilov", "Kornilov", "General whose failed 1917 move helped revive Bolshevik credibility."],
  ["stalin", "Stalin", "Bolshevik organizer whose party position mattered after Lenin's death."],
  ["martov", "Martov", "Menshevik critic of Bolshevik dictatorship."],
  ["plekhanov", "Plekhanov", "Pioneer of Russian Marxism who opposed Lenin's 1917 line."],
  ["alexander-iii", "Alexander III", "Conservative tsar whose repression shaped late imperial politics."],
  ["sergei-witte", "Sergei Witte", "Modernizer tied to railways, industry, and the 1905 compromise."],
];

export const russianRevolutionConceptNodes: ConceptNode[] = conceptDescriptions.map(([id, label, description]) => ({
  id: `node-russian-${id}`,
  binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
  label,
  description,
  created_at: now,
}));

function edge(source: string, target: string, label: string): ConceptEdge {
  return {
    id: `edge-russian-${source}-${target}`,
    binder_id: RUSSIAN_REVOLUTION_BINDER_ID,
    source_id: `node-russian-${source}`,
    target_id: `node-russian-${target}`,
    label,
    created_at: now,
  };
}

export const russianRevolutionConceptEdges: ConceptEdge[] = [
  edge("autocracy", "duma", "resists"),
  edge("serfdom", "land-hunger", "leaves behind"),
  edge("industrialization", "marxism", "creates audience for"),
  edge("russification", "autocracy", "extends"),
  edge("soviet", "dual-power", "anchors"),
  edge("provisional-government", "dual-power", "competes inside"),
  edge("bolshevik", "vanguard-party", "organizes through"),
  edge("lenin", "bolshevik", "leads"),
  edge("lenin", "vanguard-party", "theorizes"),
  edge("trotsky", "soviet", "leads in Petrograd"),
  edge("kerensky", "provisional-government", "leads"),
  edge("kornilov", "kerensky", "undermines"),
  edge("cheka", "war-communism", "enforces"),
  edge("war-communism", "kronstadt", "provokes resistance"),
  edge("kronstadt", "nep", "precedes"),
  edge("brest-litovsk", "war-communism", "intensifies civil conflict"),
  edge("nep", "ussr", "stabilizes before"),
  edge("stalin", "ussr", "consolidates within"),
  edge("martov", "menshevik", "represents"),
  edge("plekhanov", "marxism", "pioneers"),
  edge("nicholas-ii", "autocracy", "embodies"),
  edge("alexandra", "rasputin", "relies on"),
  edge("sergei-witte", "industrialization", "accelerates"),
  edge("alexander-iii", "autocracy", "hardens"),
  edge("petrograd", "soviet", "hosts"),
];
