// Generated from lmmentel/mendeleev-data numeric and factual tables.
// License: MIT. Learning copy in periodic-table-data.ts is original BinderNotes text.
// Source tables used: elements, oxidationstates, ionizationenergies, phasetransitions.

export type RawPeriodicElementRecord = {
  atomicNumber: number;
  symbol: string;
  name: string;
  atomicMass: number | null;
  atomicMassDisplay: string;
  group: number | null;
  period: number;
  block: string;
  seriesId: number;
  electronConfiguration: string;
  electronegativity: number | null;
  atomicRadiusPm: number | null;
  electronAffinityEv: number | null;
  densityGPerCm3: number | null;
  abundanceCrustMgPerKg: number | null;
  discoveryYear: number | null;
  radioactive: boolean;
  oxidationStates: number[];
  mainOxidationStates: number[];
  firstIonizationEnergyEv: number | null;
  meltingPointK: number | null;
  boilingPointK: number | null;
  phaseNote: string | null;
};

export const rawPeriodicElementRecords = [
  {
    "atomicNumber": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "atomicMass": 1.008,
    "atomicMassDisplay": "1.008",
    "group": 1,
    "period": 1,
    "block": "s",
    "seriesId": 1,
    "electronConfiguration": "1s",
    "electronegativity": 2.2,
    "atomicRadiusPm": 25,
    "electronAffinityEv": 0.754195,
    "densityGPerCm3": 0.000082,
    "abundanceCrustMgPerKg": 1400,
    "discoveryYear": 1766,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1
    ],
    "mainOxidationStates": [
      -1,
      1
    ],
    "firstIonizationEnergyEv": 13.598435,
    "meltingPointK": 13.99,
    "boilingPointK": 20.271,
    "phaseNote": null
  },
  {
    "atomicNumber": 2,
    "symbol": "He",
    "name": "Helium",
    "atomicMass": 4.002602,
    "atomicMassDisplay": "4.002602",
    "group": 18,
    "period": 1,
    "block": "s",
    "seriesId": 2,
    "electronConfiguration": "1s2",
    "electronegativity": null,
    "atomicRadiusPm": 120,
    "electronAffinityEv": -19.7,
    "densityGPerCm3": 0.000164,
    "abundanceCrustMgPerKg": 0.008,
    "discoveryYear": 1895,
    "radioactive": false,
    "oxidationStates": [],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 24.587389,
    "meltingPointK": null,
    "boilingPointK": 4.222,
    "phaseNote": null
  },
  {
    "atomicNumber": 3,
    "symbol": "Li",
    "name": "Lithium",
    "atomicMass": 6.94,
    "atomicMassDisplay": "6.94",
    "group": 1,
    "period": 2,
    "block": "s",
    "seriesId": 3,
    "electronConfiguration": "[He] 2s",
    "electronegativity": 0.98,
    "atomicRadiusPm": 145,
    "electronAffinityEv": 0.618049,
    "densityGPerCm3": 0.534,
    "abundanceCrustMgPerKg": 20,
    "discoveryYear": 1817,
    "radioactive": false,
    "oxidationStates": [
      1
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 5.391715,
    "meltingPointK": 453.65,
    "boilingPointK": 1615.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "atomicMass": 9.012183,
    "atomicMassDisplay": "9.0121831",
    "group": 2,
    "period": 2,
    "block": "s",
    "seriesId": 4,
    "electronConfiguration": "[He] 2s2",
    "electronegativity": 1.57,
    "atomicRadiusPm": 105,
    "electronAffinityEv": -2.4,
    "densityGPerCm3": 1.85,
    "abundanceCrustMgPerKg": 2.8,
    "discoveryYear": 1798,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 9.322699,
    "meltingPointK": 1560.15,
    "boilingPointK": 2741.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 5,
    "symbol": "B",
    "name": "Boron",
    "atomicMass": 10.81,
    "atomicMassDisplay": "10.81",
    "group": 13,
    "period": 2,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[He] 2s2 2p",
    "electronegativity": 2.04,
    "atomicRadiusPm": 85,
    "electronAffinityEv": 0.279723,
    "densityGPerCm3": 2.34,
    "abundanceCrustMgPerKg": 10,
    "discoveryYear": 1808,
    "radioactive": false,
    "oxidationStates": [
      -5,
      -1,
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 8.298019,
    "meltingPointK": 2350.15,
    "boilingPointK": 4273.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 6,
    "symbol": "C",
    "name": "Carbon",
    "atomicMass": 12.011,
    "atomicMassDisplay": "12.011",
    "group": 14,
    "period": 2,
    "block": "p",
    "seriesId": 1,
    "electronConfiguration": "[He] 2s2 2p2",
    "electronegativity": 2.55,
    "atomicRadiusPm": 70,
    "electronAffinityEv": 1.262119,
    "densityGPerCm3": 2.2,
    "abundanceCrustMgPerKg": 200,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      -4,
      4
    ],
    "firstIonizationEnergyEv": 11.260288,
    "meltingPointK": null,
    "boilingPointK": 4098.15,
    "phaseNote": "graphite sublimation point"
  },
  {
    "atomicNumber": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "atomicMass": 14.007,
    "atomicMassDisplay": "14.007",
    "group": 15,
    "period": 2,
    "block": "p",
    "seriesId": 1,
    "electronConfiguration": "[He] 2s2 2p3",
    "electronegativity": 3.04,
    "atomicRadiusPm": 65,
    "electronAffinityEv": -1.4,
    "densityGPerCm3": 0.001145,
    "abundanceCrustMgPerKg": 19,
    "discoveryYear": 1772,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      -3,
      3,
      5
    ],
    "firstIonizationEnergyEv": 14.53413,
    "meltingPointK": 63.15,
    "boilingPointK": 77.355,
    "phaseNote": null
  },
  {
    "atomicNumber": 8,
    "symbol": "O",
    "name": "Oxygen",
    "atomicMass": 15.999,
    "atomicMassDisplay": "15.999",
    "group": 16,
    "period": 2,
    "block": "p",
    "seriesId": 1,
    "electronConfiguration": "[He] 2s2 2p4",
    "electronegativity": 3.44,
    "atomicRadiusPm": 60,
    "electronAffinityEv": 1.461113,
    "densityGPerCm3": 0.001308,
    "abundanceCrustMgPerKg": 461000,
    "discoveryYear": 1774,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2
    ],
    "mainOxidationStates": [
      -2
    ],
    "firstIonizationEnergyEv": 13.618055,
    "meltingPointK": 54.36,
    "boilingPointK": 90.188,
    "phaseNote": null
  },
  {
    "atomicNumber": 9,
    "symbol": "F",
    "name": "Fluorine",
    "atomicMass": 18.998403,
    "atomicMassDisplay": "18.998403163",
    "group": 17,
    "period": 2,
    "block": "p",
    "seriesId": 6,
    "electronConfiguration": "[He] 2s2 2p5",
    "electronegativity": 3.98,
    "atomicRadiusPm": 50,
    "electronAffinityEv": 3.40119,
    "densityGPerCm3": 0.001553,
    "abundanceCrustMgPerKg": 585,
    "discoveryYear": 1886,
    "radioactive": false,
    "oxidationStates": [
      -1
    ],
    "mainOxidationStates": [
      -1
    ],
    "firstIonizationEnergyEv": 17.42282,
    "meltingPointK": 53.48,
    "boilingPointK": 85.04,
    "phaseNote": null
  },
  {
    "atomicNumber": 10,
    "symbol": "Ne",
    "name": "Neon",
    "atomicMass": 20.1797,
    "atomicMassDisplay": "20.1797",
    "group": 18,
    "period": 2,
    "block": "p",
    "seriesId": 2,
    "electronConfiguration": "[He] 2s2 2p6",
    "electronegativity": null,
    "atomicRadiusPm": 160,
    "electronAffinityEv": null,
    "densityGPerCm3": 0.000825,
    "abundanceCrustMgPerKg": 0.005,
    "discoveryYear": 1898,
    "radioactive": false,
    "oxidationStates": [],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 21.564541,
    "meltingPointK": 24.56,
    "boilingPointK": 27.104,
    "phaseNote": null
  },
  {
    "atomicNumber": 11,
    "symbol": "Na",
    "name": "Sodium",
    "atomicMass": 22.989769,
    "atomicMassDisplay": "22.98976928",
    "group": 1,
    "period": 3,
    "block": "s",
    "seriesId": 3,
    "electronConfiguration": "[Ne] 3s",
    "electronegativity": 0.93,
    "atomicRadiusPm": 180,
    "electronAffinityEv": 0.547926,
    "densityGPerCm3": 0.97,
    "abundanceCrustMgPerKg": 23600,
    "discoveryYear": 1807,
    "radioactive": false,
    "oxidationStates": [
      -1,
      0,
      1
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 5.139077,
    "meltingPointK": 370.944,
    "boilingPointK": 1156.09,
    "phaseNote": null
  },
  {
    "atomicNumber": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "atomicMass": 24.305,
    "atomicMassDisplay": "24.305",
    "group": 2,
    "period": 3,
    "block": "s",
    "seriesId": 4,
    "electronConfiguration": "[Ne] 3s2",
    "electronegativity": 1.31,
    "atomicRadiusPm": 150,
    "electronAffinityEv": null,
    "densityGPerCm3": 1.74,
    "abundanceCrustMgPerKg": 23300,
    "discoveryYear": 1808,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 7.646236,
    "meltingPointK": 923.15,
    "boilingPointK": 1363.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 13,
    "symbol": "Al",
    "name": "Aluminum",
    "atomicMass": 26.981538,
    "atomicMassDisplay": "26.9815385",
    "group": 13,
    "period": 3,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Ne] 3s2 3p",
    "electronegativity": 1.61,
    "atomicRadiusPm": 125,
    "electronAffinityEv": 0.43283,
    "densityGPerCm3": 2.7,
    "abundanceCrustMgPerKg": 82300,
    "discoveryYear": 1825,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.985769,
    "meltingPointK": 933.473,
    "boilingPointK": 2792.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 14,
    "symbol": "Si",
    "name": "Silicon",
    "atomicMass": 28.085,
    "atomicMassDisplay": "28.085",
    "group": 14,
    "period": 3,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[Ne] 3s2 3p2",
    "electronegativity": 1.9,
    "atomicRadiusPm": 110,
    "electronAffinityEv": 1.389521,
    "densityGPerCm3": 2.3296,
    "abundanceCrustMgPerKg": 282000,
    "discoveryYear": 1824,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      -4,
      4
    ],
    "firstIonizationEnergyEv": 8.15168,
    "meltingPointK": 1687.15,
    "boilingPointK": 3538.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "atomicMass": 30.973762,
    "atomicMassDisplay": "30.973761998",
    "group": 15,
    "period": 3,
    "block": "p",
    "seriesId": 1,
    "electronConfiguration": "[Ne] 3s2 3p3",
    "electronegativity": 2.19,
    "atomicRadiusPm": 100,
    "electronAffinityEv": 0.746607,
    "densityGPerCm3": 1.823,
    "abundanceCrustMgPerKg": 1050,
    "discoveryYear": 1669,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      -3,
      3,
      5
    ],
    "firstIonizationEnergyEv": 10.486686,
    "meltingPointK": 317.3,
    "boilingPointK": 553.65,
    "phaseNote": "white"
  },
  {
    "atomicNumber": 16,
    "symbol": "S",
    "name": "Sulfur",
    "atomicMass": 32.06,
    "atomicMassDisplay": "32.06",
    "group": 16,
    "period": 3,
    "block": "p",
    "seriesId": 1,
    "electronConfiguration": "[Ne] 3s2 3p4",
    "electronegativity": 2.58,
    "atomicRadiusPm": 100,
    "electronAffinityEv": 2.077104,
    "densityGPerCm3": 2.07,
    "abundanceCrustMgPerKg": 350,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "firstIonizationEnergyEv": 10.36001,
    "meltingPointK": 388.36,
    "boilingPointK": 717.76,
    "phaseNote": "monoclinic"
  },
  {
    "atomicNumber": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "atomicMass": 35.45,
    "atomicMassDisplay": "35.45",
    "group": 17,
    "period": 3,
    "block": "p",
    "seriesId": 6,
    "electronConfiguration": "[Ne] 3s2 3p5",
    "electronegativity": 3.16,
    "atomicRadiusPm": 100,
    "electronAffinityEv": 3.612725,
    "densityGPerCm3": 0.002898,
    "abundanceCrustMgPerKg": 145,
    "discoveryYear": 1774,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      -1,
      1,
      3,
      5,
      7
    ],
    "firstIonizationEnergyEv": 12.967633,
    "meltingPointK": 171.65,
    "boilingPointK": 239.11,
    "phaseNote": null
  },
  {
    "atomicNumber": 18,
    "symbol": "Ar",
    "name": "Argon",
    "atomicMass": 39.948,
    "atomicMassDisplay": "39.948",
    "group": 18,
    "period": 3,
    "block": "p",
    "seriesId": 2,
    "electronConfiguration": "[Ne] 3s2 3p6",
    "electronegativity": null,
    "atomicRadiusPm": 71,
    "electronAffinityEv": -11.5,
    "densityGPerCm3": 0.001633,
    "abundanceCrustMgPerKg": 3.5,
    "discoveryYear": 1894,
    "radioactive": false,
    "oxidationStates": [],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 15.759612,
    "meltingPointK": 83.81,
    "boilingPointK": 87.302,
    "phaseNote": null
  },
  {
    "atomicNumber": 19,
    "symbol": "K",
    "name": "Potassium",
    "atomicMass": 39.0983,
    "atomicMassDisplay": "39.0983",
    "group": 1,
    "period": 4,
    "block": "s",
    "seriesId": 3,
    "electronConfiguration": "[Ar] 4s",
    "electronegativity": 0.82,
    "atomicRadiusPm": 220,
    "electronAffinityEv": 0.50147,
    "densityGPerCm3": 0.89,
    "abundanceCrustMgPerKg": 20900,
    "discoveryYear": 1807,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 4.340664,
    "meltingPointK": 336.65,
    "boilingPointK": 1032.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "atomicMass": 40.078,
    "atomicMassDisplay": "40.078",
    "group": 2,
    "period": 4,
    "block": "s",
    "seriesId": 4,
    "electronConfiguration": "[Ar] 4s2",
    "electronegativity": 1,
    "atomicRadiusPm": 180,
    "electronAffinityEv": 0.02455,
    "densityGPerCm3": 1.54,
    "abundanceCrustMgPerKg": 41500,
    "discoveryYear": 1808,
    "radioactive": false,
    "oxidationStates": [
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 6.113155,
    "meltingPointK": 1115.15,
    "boilingPointK": 1757.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "atomicMass": 44.955908,
    "atomicMassDisplay": "44.955908",
    "group": 3,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d 4s2",
    "electronegativity": 1.36,
    "atomicRadiusPm": 160,
    "electronAffinityEv": 0.188,
    "densityGPerCm3": 2.99,
    "abundanceCrustMgPerKg": 22,
    "discoveryYear": 1879,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.56149,
    "meltingPointK": 1814.15,
    "boilingPointK": 3109.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "atomicMass": 47.867,
    "atomicMassDisplay": "47.867",
    "group": 4,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d2 4s2",
    "electronegativity": 1.54,
    "atomicRadiusPm": 140,
    "electronAffinityEv": 0.079,
    "densityGPerCm3": 4.506,
    "abundanceCrustMgPerKg": 5650,
    "discoveryYear": 1791,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 6.82812,
    "meltingPointK": 1943.15,
    "boilingPointK": 3560.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 23,
    "symbol": "V",
    "name": "Vanadium",
    "atomicMass": 50.9415,
    "atomicMassDisplay": "50.9415",
    "group": 5,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d3 4s2",
    "electronegativity": 1.63,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 0.525,
    "densityGPerCm3": 6,
    "abundanceCrustMgPerKg": 120,
    "discoveryYear": 1830,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      5
    ],
    "firstIonizationEnergyEv": 6.746187,
    "meltingPointK": 2183.15,
    "boilingPointK": 3680.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "atomicMass": 51.9961,
    "atomicMassDisplay": "51.9961",
    "group": 6,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d5 4s",
    "electronegativity": 1.66,
    "atomicRadiusPm": 140,
    "electronAffinityEv": 0.666,
    "densityGPerCm3": 7.15,
    "abundanceCrustMgPerKg": 102,
    "discoveryYear": 1797,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      3,
      6
    ],
    "firstIonizationEnergyEv": 6.76651,
    "meltingPointK": 2180.15,
    "boilingPointK": 2944.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "atomicMass": 54.938044,
    "atomicMassDisplay": "54.938044",
    "group": 7,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d5 4s2",
    "electronegativity": 1.55,
    "atomicRadiusPm": 140,
    "electronAffinityEv": null,
    "densityGPerCm3": 7.3,
    "abundanceCrustMgPerKg": 950,
    "discoveryYear": 1774,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      2,
      4,
      7
    ],
    "firstIonizationEnergyEv": 7.434038,
    "meltingPointK": 1519.15,
    "boilingPointK": 2334.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 26,
    "symbol": "Fe",
    "name": "Iron",
    "atomicMass": 55.845,
    "atomicMassDisplay": "55.845",
    "group": 8,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d6 4s2",
    "electronegativity": 1.83,
    "atomicRadiusPm": 140,
    "electronAffinityEv": 0.151,
    "densityGPerCm3": 7.87,
    "abundanceCrustMgPerKg": 56300,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      2,
      3
    ],
    "firstIonizationEnergyEv": 7.902468,
    "meltingPointK": 1811.15,
    "boilingPointK": 3134.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "atomicMass": 58.933194,
    "atomicMassDisplay": "58.933194",
    "group": 9,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d7 4s2",
    "electronegativity": 1.88,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 0.662256,
    "densityGPerCm3": 8.86,
    "abundanceCrustMgPerKg": 25,
    "discoveryYear": 1739,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      2,
      3
    ],
    "firstIonizationEnergyEv": 7.88101,
    "meltingPointK": 1768.15,
    "boilingPointK": 3200.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "atomicMass": 58.6934,
    "atomicMassDisplay": "58.6934",
    "group": 10,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d8 4s2",
    "electronegativity": 1.91,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 1.156,
    "densityGPerCm3": 8.9,
    "abundanceCrustMgPerKg": 84,
    "discoveryYear": 1751,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 7.639878,
    "meltingPointK": 1728.15,
    "boilingPointK": 3186.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 29,
    "symbol": "Cu",
    "name": "Copper",
    "atomicMass": 63.546,
    "atomicMassDisplay": "63.546",
    "group": 11,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d10 4s",
    "electronegativity": 1.9,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 1.235,
    "densityGPerCm3": 8.96,
    "abundanceCrustMgPerKg": 60,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -2,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 7.72638,
    "meltingPointK": 1357.77,
    "boilingPointK": 2833.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "atomicMass": 65.38,
    "atomicMassDisplay": "65.38",
    "group": 12,
    "period": 4,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Ar] 3d10 4s2",
    "electronegativity": 1.65,
    "atomicRadiusPm": 135,
    "electronAffinityEv": null,
    "densityGPerCm3": 7.134,
    "abundanceCrustMgPerKg": 70,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -2,
      0,
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 9.394197,
    "meltingPointK": 692.677,
    "boilingPointK": 1180.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "atomicMass": 69.723,
    "atomicMassDisplay": "69.723",
    "group": 13,
    "period": 4,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Ar] 3d10 4s2 4p",
    "electronegativity": 1.81,
    "atomicRadiusPm": 130,
    "electronAffinityEv": 0.43,
    "densityGPerCm3": 5.91,
    "abundanceCrustMgPerKg": 19,
    "discoveryYear": 1875,
    "radioactive": false,
    "oxidationStates": [
      -5,
      -4,
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.999302,
    "meltingPointK": 302.9146,
    "boilingPointK": 2502.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "atomicMass": 72.63,
    "atomicMassDisplay": "72.63",
    "group": 14,
    "period": 4,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[Ar] 3d10 4s2 4p2",
    "electronegativity": 2.01,
    "atomicRadiusPm": 125,
    "electronAffinityEv": 1.232712,
    "densityGPerCm3": 5.3234,
    "abundanceCrustMgPerKg": 1.5,
    "discoveryYear": 1886,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      -4,
      2,
      4
    ],
    "firstIonizationEnergyEv": 7.899435,
    "meltingPointK": 1211.4,
    "boilingPointK": 3106.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 33,
    "symbol": "As",
    "name": "Arsenic",
    "atomicMass": 74.921595,
    "atomicMassDisplay": "74.921595",
    "group": 15,
    "period": 4,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[Ar] 3d10 4s2 4p3",
    "electronegativity": 2.18,
    "atomicRadiusPm": 115,
    "electronAffinityEv": 0.804,
    "densityGPerCm3": 5.75,
    "abundanceCrustMgPerKg": 1.8,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      -3,
      3,
      5
    ],
    "firstIonizationEnergyEv": 9.78855,
    "meltingPointK": 1090.15,
    "boilingPointK": 889.15,
    "phaseNote": "gray sublimation point"
  },
  {
    "atomicNumber": 34,
    "symbol": "Se",
    "name": "Selenium",
    "atomicMass": 78.971,
    "atomicMassDisplay": "78.971",
    "group": 16,
    "period": 4,
    "block": "p",
    "seriesId": 1,
    "electronConfiguration": "[Ar] 3d10 4s2 4p4",
    "electronegativity": 2.55,
    "atomicRadiusPm": 115,
    "electronAffinityEv": 2.02067,
    "densityGPerCm3": 4.809,
    "abundanceCrustMgPerKg": 0.05,
    "discoveryYear": 1818,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "firstIonizationEnergyEv": 9.752368,
    "meltingPointK": 493.95,
    "boilingPointK": 958.15,
    "phaseNote": "gray"
  },
  {
    "atomicNumber": 35,
    "symbol": "Br",
    "name": "Bromine",
    "atomicMass": 79.904,
    "atomicMassDisplay": "79.904",
    "group": 17,
    "period": 4,
    "block": "p",
    "seriesId": 6,
    "electronConfiguration": "[Ar] 3d10 4s2 4p5",
    "electronegativity": 2.96,
    "atomicRadiusPm": 115,
    "electronAffinityEv": 3.363588,
    "densityGPerCm3": 3.1028,
    "abundanceCrustMgPerKg": 2.4,
    "discoveryYear": 1826,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1,
      2,
      3,
      4,
      5,
      7
    ],
    "mainOxidationStates": [
      -1,
      1,
      3,
      5
    ],
    "firstIonizationEnergyEv": 11.81381,
    "meltingPointK": 265.95,
    "boilingPointK": 331.95,
    "phaseNote": null
  },
  {
    "atomicNumber": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "atomicMass": 83.798,
    "atomicMassDisplay": "83.798",
    "group": 18,
    "period": 4,
    "block": "p",
    "seriesId": 2,
    "electronConfiguration": "[Ar] 3d10 4s2 4p6",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 0.003425,
    "abundanceCrustMgPerKg": 0.0001,
    "discoveryYear": 1898,
    "radioactive": false,
    "oxidationStates": [
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 13.999605,
    "meltingPointK": 115.78,
    "boilingPointK": 119.735,
    "phaseNote": null
  },
  {
    "atomicNumber": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "atomicMass": 85.4678,
    "atomicMassDisplay": "85.4678",
    "group": 1,
    "period": 5,
    "block": "s",
    "seriesId": 3,
    "electronConfiguration": "[Kr] 5s",
    "electronegativity": 0.82,
    "atomicRadiusPm": 235,
    "electronAffinityEv": 0.48592,
    "densityGPerCm3": 1.53,
    "abundanceCrustMgPerKg": 90,
    "discoveryYear": 1861,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 4.177128,
    "meltingPointK": 312.45,
    "boilingPointK": 961.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "atomicMass": 87.62,
    "atomicMassDisplay": "87.62",
    "group": 2,
    "period": 5,
    "block": "s",
    "seriesId": 4,
    "electronConfiguration": "[Kr] 5s2",
    "electronegativity": 0.95,
    "atomicRadiusPm": 200,
    "electronAffinityEv": 0.048,
    "densityGPerCm3": 2.64,
    "abundanceCrustMgPerKg": 370,
    "discoveryYear": 1790,
    "radioactive": false,
    "oxidationStates": [
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 5.694867,
    "meltingPointK": 1050.15,
    "boilingPointK": 1650.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "atomicMass": 88.90584,
    "atomicMassDisplay": "88.90584",
    "group": 3,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d 5s2",
    "electronegativity": 1.22,
    "atomicRadiusPm": 180,
    "electronAffinityEv": 0.307,
    "densityGPerCm3": 4.47,
    "abundanceCrustMgPerKg": 33,
    "discoveryYear": 1789,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.21726,
    "meltingPointK": 1795.15,
    "boilingPointK": 3618.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "atomicMass": 91.224,
    "atomicMassDisplay": "91.224",
    "group": 4,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d2 5s2",
    "electronegativity": 1.33,
    "atomicRadiusPm": 155,
    "electronAffinityEv": 0.426,
    "densityGPerCm3": 6.52,
    "abundanceCrustMgPerKg": 165,
    "discoveryYear": 1789,
    "radioactive": false,
    "oxidationStates": [
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 6.634126,
    "meltingPointK": 2127.15,
    "boilingPointK": 4679.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "atomicMass": 92.90637,
    "atomicMassDisplay": "92.90637",
    "group": 5,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d4 5s",
    "electronegativity": 1.6,
    "atomicRadiusPm": 145,
    "electronAffinityEv": 0.917406,
    "densityGPerCm3": 8.57,
    "abundanceCrustMgPerKg": 20,
    "discoveryYear": 1801,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      5
    ],
    "firstIonizationEnergyEv": 6.75885,
    "meltingPointK": 2750.15,
    "boilingPointK": 5014.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "atomicMass": 95.95,
    "atomicMassDisplay": "95.95",
    "group": 6,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d5 5s",
    "electronegativity": 2.16,
    "atomicRadiusPm": 145,
    "electronAffinityEv": 0.748,
    "densityGPerCm3": 10.2,
    "abundanceCrustMgPerKg": 1.2,
    "discoveryYear": 1778,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      4,
      6
    ],
    "firstIonizationEnergyEv": 7.09243,
    "meltingPointK": 2895.15,
    "boilingPointK": 4912.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "atomicMass": 97.90721,
    "atomicMassDisplay": "97.90721",
    "group": 7,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d5 5s2",
    "electronegativity": 2.1,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 0.55,
    "densityGPerCm3": 11,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1937,
    "radioactive": true,
    "oxidationStates": [
      -3,
      -1,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      4,
      7
    ],
    "firstIonizationEnergyEv": 7.11938,
    "meltingPointK": 2430.15,
    "boilingPointK": 4535.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "atomicMass": 101.07,
    "atomicMassDisplay": "101.07",
    "group": 8,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d7 5s",
    "electronegativity": 2.2,
    "atomicRadiusPm": 130,
    "electronAffinityEv": 1.05,
    "densityGPerCm3": 12.1,
    "abundanceCrustMgPerKg": 0.001,
    "discoveryYear": 1844,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "mainOxidationStates": [
      3,
      4
    ],
    "firstIonizationEnergyEv": 7.3605,
    "meltingPointK": 2606.15,
    "boilingPointK": 4420.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "atomicMass": 102.9055,
    "atomicMassDisplay": "102.9055",
    "group": 9,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d8 5s",
    "electronegativity": 2.28,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 1.137,
    "densityGPerCm3": 12.4,
    "abundanceCrustMgPerKg": 0.001,
    "discoveryYear": 1803,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 7.4589,
    "meltingPointK": 2236.15,
    "boilingPointK": 3968.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "atomicMass": 106.42,
    "atomicMassDisplay": "106.42",
    "group": 10,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d10",
    "electronegativity": 2.2,
    "atomicRadiusPm": 140,
    "electronAffinityEv": 0.562,
    "densityGPerCm3": 12,
    "abundanceCrustMgPerKg": 0.015,
    "discoveryYear": 1803,
    "radioactive": false,
    "oxidationStates": [
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      2,
      4
    ],
    "firstIonizationEnergyEv": 8.336839,
    "meltingPointK": 1827.95,
    "boilingPointK": 3236.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 47,
    "symbol": "Ag",
    "name": "Silver",
    "atomicMass": 107.8682,
    "atomicMassDisplay": "107.8682",
    "group": 11,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d10 5s",
    "electronegativity": 1.93,
    "atomicRadiusPm": 160,
    "electronAffinityEv": 1.302,
    "densityGPerCm3": 10.5,
    "abundanceCrustMgPerKg": 0.075,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 7.576234,
    "meltingPointK": 1234.93,
    "boilingPointK": 2435.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "atomicMass": 112.414,
    "atomicMassDisplay": "112.414",
    "group": 12,
    "period": 5,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Kr] 4d10 5s2",
    "electronegativity": 1.69,
    "atomicRadiusPm": 155,
    "electronAffinityEv": null,
    "densityGPerCm3": 8.69,
    "abundanceCrustMgPerKg": 0.15,
    "discoveryYear": 1817,
    "radioactive": false,
    "oxidationStates": [
      -2,
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 8.99382,
    "meltingPointK": 594.219,
    "boilingPointK": 1040.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 49,
    "symbol": "In",
    "name": "Indium",
    "atomicMass": 114.818,
    "atomicMassDisplay": "114.818",
    "group": 13,
    "period": 5,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Kr] 4d10 5s2 5p",
    "electronegativity": 1.78,
    "atomicRadiusPm": 155,
    "electronAffinityEv": 0.3,
    "densityGPerCm3": 7.31,
    "abundanceCrustMgPerKg": 0.25,
    "discoveryYear": 1863,
    "radioactive": false,
    "oxidationStates": [
      -5,
      -2,
      -1,
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.786356,
    "meltingPointK": 429.7485,
    "boilingPointK": 2300.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 50,
    "symbol": "Sn",
    "name": "Tin",
    "atomicMass": 118.71,
    "atomicMassDisplay": "118.71",
    "group": 14,
    "period": 5,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Kr] 4d10 5s2 5p2",
    "electronegativity": 1.96,
    "atomicRadiusPm": 145,
    "electronAffinityEv": 1.112067,
    "densityGPerCm3": 7.287,
    "abundanceCrustMgPerKg": 2.3,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      -4,
      2,
      4
    ],
    "firstIonizationEnergyEv": 7.343918,
    "meltingPointK": 505.078,
    "boilingPointK": 2859.15,
    "phaseNote": "white"
  },
  {
    "atomicNumber": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "atomicMass": 121.76,
    "atomicMassDisplay": "121.76",
    "group": 15,
    "period": 5,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[Kr] 4d10 5s2 5p3",
    "electronegativity": 2.05,
    "atomicRadiusPm": 145,
    "electronAffinityEv": 1.046,
    "densityGPerCm3": 6.68,
    "abundanceCrustMgPerKg": 0.2,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      -3,
      3,
      5
    ],
    "firstIonizationEnergyEv": 8.608389,
    "meltingPointK": 903.778,
    "boilingPointK": 1860.15,
    "phaseNote": "gray"
  },
  {
    "atomicNumber": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "atomicMass": 127.6,
    "atomicMassDisplay": "127.6",
    "group": 16,
    "period": 5,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[Kr] 4d10 5s2 5p4",
    "electronegativity": 2.1,
    "atomicRadiusPm": 140,
    "electronAffinityEv": 1.970876,
    "densityGPerCm3": 6.232,
    "abundanceCrustMgPerKg": 0.001,
    "discoveryYear": 1782,
    "radioactive": false,
    "oxidationStates": [
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "firstIonizationEnergyEv": 9.009808,
    "meltingPointK": 722.66,
    "boilingPointK": 1261.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 53,
    "symbol": "I",
    "name": "Iodine",
    "atomicMass": 126.90447,
    "atomicMassDisplay": "126.90447",
    "group": 17,
    "period": 5,
    "block": "p",
    "seriesId": 6,
    "electronConfiguration": "[Kr] 4d10 5s2 5p5",
    "electronegativity": 2.66,
    "atomicRadiusPm": 140,
    "electronAffinityEv": 3.059037,
    "densityGPerCm3": 4.933,
    "abundanceCrustMgPerKg": 0.45,
    "discoveryYear": 1811,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      -1,
      1,
      3,
      5,
      7
    ],
    "firstIonizationEnergyEv": 10.451236,
    "meltingPointK": 386.85,
    "boilingPointK": 457.55,
    "phaseNote": null
  },
  {
    "atomicNumber": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "atomicMass": 131.293,
    "atomicMassDisplay": "131.293",
    "group": 18,
    "period": 5,
    "block": "p",
    "seriesId": 2,
    "electronConfiguration": "[Kr] 4d10 5s2 5p6",
    "electronegativity": 2.6,
    "atomicRadiusPm": null,
    "electronAffinityEv": -0.056,
    "densityGPerCm3": 0.005366,
    "abundanceCrustMgPerKg": 0.00003,
    "discoveryYear": 1898,
    "radioactive": false,
    "oxidationStates": [
      2,
      4,
      6,
      8
    ],
    "mainOxidationStates": [
      2,
      4,
      6
    ],
    "firstIonizationEnergyEv": 12.129844,
    "meltingPointK": 161.4,
    "boilingPointK": 165.051,
    "phaseNote": null
  },
  {
    "atomicNumber": 55,
    "symbol": "Cs",
    "name": "Cesium",
    "atomicMass": 132.905452,
    "atomicMassDisplay": "132.90545196",
    "group": 1,
    "period": 6,
    "block": "s",
    "seriesId": 3,
    "electronConfiguration": "[Xe] 6s",
    "electronegativity": 0.79,
    "atomicRadiusPm": 260,
    "electronAffinityEv": 0.471626,
    "densityGPerCm3": 1.873,
    "abundanceCrustMgPerKg": 3,
    "discoveryYear": 1860,
    "radioactive": false,
    "oxidationStates": [
      -1,
      1
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 3.893906,
    "meltingPointK": 301.65,
    "boilingPointK": 944.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 56,
    "symbol": "Ba",
    "name": "Barium",
    "atomicMass": 137.327,
    "atomicMassDisplay": "137.327",
    "group": 2,
    "period": 6,
    "block": "s",
    "seriesId": 4,
    "electronConfiguration": "[Xe] 6s2",
    "electronegativity": 0.89,
    "atomicRadiusPm": 215,
    "electronAffinityEv": 0.14462,
    "densityGPerCm3": 3.62,
    "abundanceCrustMgPerKg": 425,
    "discoveryYear": 1808,
    "radioactive": false,
    "oxidationStates": [
      1,
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 5.211665,
    "meltingPointK": 1000.15,
    "boilingPointK": 2118.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "atomicMass": 138.90547,
    "atomicMassDisplay": "138.90547",
    "group": 3,
    "period": 6,
    "block": "d",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 5d 6s2",
    "electronegativity": 1.1,
    "atomicRadiusPm": 195,
    "electronAffinityEv": 0.47,
    "densityGPerCm3": 6.15,
    "abundanceCrustMgPerKg": 39,
    "discoveryYear": 1839,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.5769,
    "meltingPointK": 1193.15,
    "boilingPointK": 3737.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "atomicMass": 140.116,
    "atomicMassDisplay": "140.116",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f 5d 6s2",
    "electronegativity": 1.12,
    "atomicRadiusPm": 185,
    "electronAffinityEv": 0.65,
    "densityGPerCm3": 6.77,
    "abundanceCrustMgPerKg": 66.5,
    "discoveryYear": 1803,
    "radioactive": false,
    "oxidationStates": [
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      3,
      4
    ],
    "firstIonizationEnergyEv": 5.5386,
    "meltingPointK": 1072.15,
    "boilingPointK": 3716.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "atomicMass": 140.90766,
    "atomicMassDisplay": "140.90766",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f3 6s2",
    "electronegativity": 1.13,
    "atomicRadiusPm": 185,
    "electronAffinityEv": 0.962,
    "densityGPerCm3": 6.773,
    "abundanceCrustMgPerKg": 9.2,
    "discoveryYear": 1885,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.4702,
    "meltingPointK": 1204.15,
    "boilingPointK": 3793.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "atomicMass": 144.242,
    "atomicMassDisplay": "144.242",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f4 6s2",
    "electronegativity": 1.14,
    "atomicRadiusPm": 185,
    "electronAffinityEv": 1.916,
    "densityGPerCm3": 7.01,
    "abundanceCrustMgPerKg": 41.5,
    "discoveryYear": 1925,
    "radioactive": false,
    "oxidationStates": [
      0,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.525,
    "meltingPointK": 1289.15,
    "boilingPointK": 3347.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "atomicMass": 144.91276,
    "atomicMassDisplay": "144.91276",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f5 6s2",
    "electronegativity": null,
    "atomicRadiusPm": 185,
    "electronAffinityEv": null,
    "densityGPerCm3": 7.26,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1945,
    "radioactive": true,
    "oxidationStates": [
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.58187,
    "meltingPointK": 1315.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "atomicMass": 150.36,
    "atomicMassDisplay": "150.36",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f6 6s2",
    "electronegativity": 1.17,
    "atomicRadiusPm": 185,
    "electronAffinityEv": null,
    "densityGPerCm3": 7.52,
    "abundanceCrustMgPerKg": 7.05,
    "discoveryYear": 1879,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.643722,
    "meltingPointK": 1345.15,
    "boilingPointK": 2067.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 63,
    "symbol": "Eu",
    "name": "Europium",
    "atomicMass": 151.964,
    "atomicMassDisplay": "151.964",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f7 6s2",
    "electronegativity": null,
    "atomicRadiusPm": 185,
    "electronAffinityEv": 0.864,
    "densityGPerCm3": 5.24,
    "abundanceCrustMgPerKg": 2,
    "discoveryYear": 1901,
    "radioactive": false,
    "oxidationStates": [
      0,
      2,
      3
    ],
    "mainOxidationStates": [
      2,
      3
    ],
    "firstIonizationEnergyEv": 5.670385,
    "meltingPointK": 1095.15,
    "boilingPointK": 1802.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "atomicMass": 157.25,
    "atomicMassDisplay": "157.25",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f7 5d 6s2",
    "electronegativity": 1.2,
    "atomicRadiusPm": 180,
    "electronAffinityEv": null,
    "densityGPerCm3": 7.9,
    "abundanceCrustMgPerKg": 6.2,
    "discoveryYear": 1880,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.1498,
    "meltingPointK": 1586.15,
    "boilingPointK": 3546.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "atomicMass": 158.92535,
    "atomicMassDisplay": "158.92535",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f9 6s2",
    "electronegativity": null,
    "atomicRadiusPm": 175,
    "electronAffinityEv": 1.165,
    "densityGPerCm3": 8.23,
    "abundanceCrustMgPerKg": 1.2,
    "discoveryYear": 1843,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.8638,
    "meltingPointK": 1632.15,
    "boilingPointK": 3503.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "atomicMass": 162.5,
    "atomicMassDisplay": "162.5",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f10 6s2",
    "electronegativity": 1.22,
    "atomicRadiusPm": 175,
    "electronAffinityEv": 0.352,
    "densityGPerCm3": 8.55,
    "abundanceCrustMgPerKg": 5.2,
    "discoveryYear": 1886,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.939061,
    "meltingPointK": 1685.15,
    "boilingPointK": 2840.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "atomicMass": 164.93033,
    "atomicMassDisplay": "164.93033",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f11 6s2",
    "electronegativity": 1.23,
    "atomicRadiusPm": 175,
    "electronAffinityEv": null,
    "densityGPerCm3": 8.8,
    "abundanceCrustMgPerKg": 1.3,
    "discoveryYear": 1878,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.0215,
    "meltingPointK": 1745.15,
    "boilingPointK": 2973.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 68,
    "symbol": "Er",
    "name": "Erbium",
    "atomicMass": 167.259,
    "atomicMassDisplay": "167.259",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f12 6s2",
    "electronegativity": 1.24,
    "atomicRadiusPm": 175,
    "electronAffinityEv": null,
    "densityGPerCm3": 9.07,
    "abundanceCrustMgPerKg": 3.5,
    "discoveryYear": 1843,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.1077,
    "meltingPointK": 1802.15,
    "boilingPointK": 3141.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "atomicMass": 168.93422,
    "atomicMassDisplay": "168.93422",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f13 6s2",
    "electronegativity": 1.25,
    "atomicRadiusPm": 175,
    "electronAffinityEv": 1.029,
    "densityGPerCm3": 9.321,
    "abundanceCrustMgPerKg": 0.52,
    "discoveryYear": 1879,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.184402,
    "meltingPointK": 1818.15,
    "boilingPointK": 2223.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "atomicMass": 173.045,
    "atomicMassDisplay": "173.045",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 9,
    "electronConfiguration": "[Xe] 4f14 6s2",
    "electronegativity": null,
    "atomicRadiusPm": 175,
    "electronAffinityEv": -0.02,
    "densityGPerCm3": 6.9,
    "abundanceCrustMgPerKg": 3.2,
    "discoveryYear": 1878,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.25416,
    "meltingPointK": 1097.15,
    "boilingPointK": 1469.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "atomicMass": 174.9668,
    "atomicMassDisplay": "174.9668",
    "group": 3,
    "period": 6,
    "block": "f",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d 6s2",
    "electronegativity": 1,
    "atomicRadiusPm": 175,
    "electronAffinityEv": 0.34,
    "densityGPerCm3": 9.84,
    "abundanceCrustMgPerKg": 0.8,
    "discoveryYear": 1907,
    "radioactive": false,
    "oxidationStates": [
      0,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.425871,
    "meltingPointK": 1936.15,
    "boilingPointK": 3675.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "atomicMass": 178.49,
    "atomicMassDisplay": "178.49",
    "group": 4,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d2 6s2",
    "electronegativity": 1.3,
    "atomicRadiusPm": 155,
    "electronAffinityEv": 0.014,
    "densityGPerCm3": 13.3,
    "abundanceCrustMgPerKg": 3,
    "discoveryYear": 1923,
    "radioactive": false,
    "oxidationStates": [
      -2,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 6.82507,
    "meltingPointK": 2506.15,
    "boilingPointK": 4873.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "atomicMass": 180.94788,
    "atomicMassDisplay": "180.94788",
    "group": 5,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d3 6s2",
    "electronegativity": 1.5,
    "atomicRadiusPm": 145,
    "electronAffinityEv": 0.322,
    "densityGPerCm3": 16.4,
    "abundanceCrustMgPerKg": 2,
    "discoveryYear": 1802,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      5
    ],
    "firstIonizationEnergyEv": 7.549571,
    "meltingPointK": 3290.15,
    "boilingPointK": 5728.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 74,
    "symbol": "W",
    "name": "Tungsten",
    "atomicMass": 183.84,
    "atomicMassDisplay": "183.84",
    "group": 6,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d4 6s2",
    "electronegativity": 1.7,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 0.81626,
    "densityGPerCm3": 19.3,
    "abundanceCrustMgPerKg": 1.25,
    "discoveryYear": 1783,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      4,
      6
    ],
    "firstIonizationEnergyEv": 7.86403,
    "meltingPointK": 3687.15,
    "boilingPointK": 5828.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "atomicMass": 186.207,
    "atomicMassDisplay": "186.207",
    "group": 7,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d5 6s2",
    "electronegativity": 1.9,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 0.15,
    "densityGPerCm3": 20.8,
    "abundanceCrustMgPerKg": 0.0007,
    "discoveryYear": 1925,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 7.83352,
    "meltingPointK": 3458.15,
    "boilingPointK": 5863.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 76,
    "symbol": "Os",
    "name": "Osmium",
    "atomicMass": 190.23,
    "atomicMassDisplay": "190.23",
    "group": 8,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d6 6s2",
    "electronegativity": 2.2,
    "atomicRadiusPm": 130,
    "electronAffinityEv": 1.1,
    "densityGPerCm3": 22.5872,
    "abundanceCrustMgPerKg": 0.0015,
    "discoveryYear": 1804,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 8.43823,
    "meltingPointK": 3306.15,
    "boilingPointK": 5281.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "atomicMass": 192.217,
    "atomicMassDisplay": "192.217",
    "group": 9,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d7 6s2",
    "electronegativity": 2.2,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 1.5638,
    "densityGPerCm3": 22.5622,
    "abundanceCrustMgPerKg": 0.001,
    "discoveryYear": 1804,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "mainOxidationStates": [
      3,
      4
    ],
    "firstIonizationEnergyEv": 8.96702,
    "meltingPointK": 2719.15,
    "boilingPointK": 4701.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "atomicMass": 195.084,
    "atomicMassDisplay": "195.084",
    "group": 10,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d9 6s",
    "electronegativity": 2.2,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 2.128,
    "densityGPerCm3": 21.5,
    "abundanceCrustMgPerKg": 0.005,
    "discoveryYear": 1735,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      2,
      4
    ],
    "firstIonizationEnergyEv": 8.95883,
    "meltingPointK": 2041.35,
    "boilingPointK": 4098.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 79,
    "symbol": "Au",
    "name": "Gold",
    "atomicMass": 196.966569,
    "atomicMassDisplay": "196.966569",
    "group": 11,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d10 6s",
    "electronegativity": 2.4,
    "atomicRadiusPm": 135,
    "electronAffinityEv": 2.30863,
    "densityGPerCm3": 19.3,
    "abundanceCrustMgPerKg": 0.004,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      5
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 9.225554,
    "meltingPointK": 1337.33,
    "boilingPointK": 3109.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "atomicMass": 200.592,
    "atomicMassDisplay": "200.592",
    "group": 12,
    "period": 6,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2",
    "electronegativity": 1.9,
    "atomicRadiusPm": 150,
    "electronAffinityEv": null,
    "densityGPerCm3": 13.5336,
    "abundanceCrustMgPerKg": 0.085,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -2,
      1,
      2
    ],
    "mainOxidationStates": [
      1,
      2
    ],
    "firstIonizationEnergyEv": 10.437504,
    "meltingPointK": 234.321,
    "boilingPointK": 629.769,
    "phaseNote": null
  },
  {
    "atomicNumber": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "atomicMass": 204.38,
    "atomicMassDisplay": "204.38",
    "group": 13,
    "period": 6,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p",
    "electronegativity": 1.8,
    "atomicRadiusPm": 190,
    "electronAffinityEv": 0.377,
    "densityGPerCm3": 11.8,
    "abundanceCrustMgPerKg": 0.85,
    "discoveryYear": 1861,
    "radioactive": false,
    "oxidationStates": [
      -5,
      -2,
      -1,
      1,
      2,
      3
    ],
    "mainOxidationStates": [
      1,
      3
    ],
    "firstIonizationEnergyEv": 6.108287,
    "meltingPointK": 577.15,
    "boilingPointK": 1746.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 82,
    "symbol": "Pb",
    "name": "Lead",
    "atomicMass": 207.2,
    "atomicMassDisplay": "207.2",
    "group": 14,
    "period": 6,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
    "electronegativity": 1.8,
    "atomicRadiusPm": 180,
    "electronAffinityEv": 0.356743,
    "densityGPerCm3": 11.3,
    "abundanceCrustMgPerKg": 14,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -4,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      2,
      4
    ],
    "firstIonizationEnergyEv": 7.41668,
    "meltingPointK": 600.612,
    "boilingPointK": 2022.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "atomicMass": 208.9804,
    "atomicMassDisplay": "208.9804",
    "group": 15,
    "period": 6,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
    "electronegativity": 1.9,
    "atomicRadiusPm": 160,
    "electronAffinityEv": 0.942362,
    "densityGPerCm3": 9.79,
    "abundanceCrustMgPerKg": 0.0085,
    "discoveryYear": null,
    "radioactive": false,
    "oxidationStates": [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 7.285516,
    "meltingPointK": 544.552,
    "boilingPointK": 1837.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 84,
    "symbol": "Po",
    "name": "Polonium",
    "atomicMass": 209,
    "atomicMassDisplay": "209",
    "group": 16,
    "period": 6,
    "block": "p",
    "seriesId": 5,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
    "electronegativity": 2,
    "atomicRadiusPm": 190,
    "electronAffinityEv": 1.9,
    "densityGPerCm3": 9.2,
    "abundanceCrustMgPerKg": 0,
    "discoveryYear": 1898,
    "radioactive": true,
    "oxidationStates": [
      -2,
      2,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      -2,
      2,
      4
    ],
    "firstIonizationEnergyEv": 8.41807,
    "meltingPointK": 527.15,
    "boilingPointK": 1235.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 85,
    "symbol": "At",
    "name": "Astatine",
    "atomicMass": 210,
    "atomicMassDisplay": "210",
    "group": 17,
    "period": 6,
    "block": "p",
    "seriesId": 6,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
    "electronegativity": 2.2,
    "atomicRadiusPm": null,
    "electronAffinityEv": 2.8,
    "densityGPerCm3": 7,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1940,
    "radioactive": true,
    "oxidationStates": [
      -1,
      1,
      3,
      5,
      7
    ],
    "mainOxidationStates": [
      -1,
      1
    ],
    "firstIonizationEnergyEv": 9.31751,
    "meltingPointK": 575.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 86,
    "symbol": "Rn",
    "name": "Radon",
    "atomicMass": 222,
    "atomicMassDisplay": "222",
    "group": 18,
    "period": 6,
    "block": "p",
    "seriesId": 2,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 0.009074,
    "abundanceCrustMgPerKg": 0,
    "discoveryYear": 1898,
    "radioactive": true,
    "oxidationStates": [
      2,
      6
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 10.7485,
    "meltingPointK": 202.15,
    "boilingPointK": 211.45,
    "phaseNote": null
  },
  {
    "atomicNumber": 87,
    "symbol": "Fr",
    "name": "Francium",
    "atomicMass": 223,
    "atomicMassDisplay": "223",
    "group": 1,
    "period": 7,
    "block": "s",
    "seriesId": 3,
    "electronConfiguration": "[Rn] 7s",
    "electronegativity": 0.7,
    "atomicRadiusPm": null,
    "electronAffinityEv": 0.486,
    "densityGPerCm3": 1.87,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1939,
    "radioactive": true,
    "oxidationStates": [
      1
    ],
    "mainOxidationStates": [
      1
    ],
    "firstIonizationEnergyEv": 4.072741,
    "meltingPointK": 294.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 88,
    "symbol": "Ra",
    "name": "Radium",
    "atomicMass": 226,
    "atomicMassDisplay": "226",
    "group": 2,
    "period": 7,
    "block": "s",
    "seriesId": 4,
    "electronConfiguration": "[Rn] 7s2",
    "electronegativity": 0.9,
    "atomicRadiusPm": 215,
    "electronAffinityEv": 0.1,
    "densityGPerCm3": 5,
    "abundanceCrustMgPerKg": 0.000001,
    "discoveryYear": 1898,
    "radioactive": true,
    "oxidationStates": [
      2
    ],
    "mainOxidationStates": [
      2
    ],
    "firstIonizationEnergyEv": 5.278424,
    "meltingPointK": 969.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "atomicMass": 227,
    "atomicMassDisplay": "227",
    "group": 3,
    "period": 7,
    "block": "d",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 6d 7s2",
    "electronegativity": 1.1,
    "atomicRadiusPm": 195,
    "electronAffinityEv": 0.35,
    "densityGPerCm3": 10,
    "abundanceCrustMgPerKg": 0,
    "discoveryYear": 1899,
    "radioactive": true,
    "oxidationStates": [
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.380235,
    "meltingPointK": 1323.15,
    "boilingPointK": 3473.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 90,
    "symbol": "Th",
    "name": "Thorium",
    "atomicMass": 232.0377,
    "atomicMassDisplay": "232.0377",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 6d2 7s2",
    "electronegativity": 1.3,
    "atomicRadiusPm": 180,
    "electronAffinityEv": null,
    "densityGPerCm3": 11.7,
    "abundanceCrustMgPerKg": 9.6,
    "discoveryYear": 1828,
    "radioactive": true,
    "oxidationStates": [
      -1,
      1,
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 6.3067,
    "meltingPointK": 2023.15,
    "boilingPointK": 5058.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "atomicMass": 231.03588,
    "atomicMassDisplay": "231.03588",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f2 6d 7s2",
    "electronegativity": 1.5,
    "atomicRadiusPm": 180,
    "electronAffinityEv": null,
    "densityGPerCm3": 15.4,
    "abundanceCrustMgPerKg": 0.000001,
    "discoveryYear": 1917,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      5
    ],
    "firstIonizationEnergyEv": 5.89,
    "meltingPointK": 1845.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 92,
    "symbol": "U",
    "name": "Uranium",
    "atomicMass": 238.02891,
    "atomicMassDisplay": "238.02891",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f3 6d 7s2",
    "electronegativity": 1.7,
    "atomicRadiusPm": 175,
    "electronAffinityEv": null,
    "densityGPerCm3": 19.1,
    "abundanceCrustMgPerKg": 2.7,
    "discoveryYear": 1789,
    "radioactive": true,
    "oxidationStates": [
      -1,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      6
    ],
    "firstIonizationEnergyEv": 6.19405,
    "meltingPointK": 1408.15,
    "boilingPointK": 4404.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "atomicMass": 237,
    "atomicMassDisplay": "237",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f4 6d 7s2",
    "electronegativity": 1.3,
    "atomicRadiusPm": 175,
    "electronAffinityEv": null,
    "densityGPerCm3": 20.2,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1940,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      5
    ],
    "firstIonizationEnergyEv": 6.26554,
    "meltingPointK": 917.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "atomicMass": 244,
    "atomicMassDisplay": "244",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f6 7s2",
    "electronegativity": 1.3,
    "atomicRadiusPm": 175,
    "electronAffinityEv": null,
    "densityGPerCm3": 19.7,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1940,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 6.02576,
    "meltingPointK": 913.15,
    "boilingPointK": 3501.15,
    "phaseNote": null
  },
  {
    "atomicNumber": 95,
    "symbol": "Am",
    "name": "Americium",
    "atomicMass": 243,
    "atomicMassDisplay": "243",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f7 7s2",
    "electronegativity": null,
    "atomicRadiusPm": 175,
    "electronAffinityEv": null,
    "densityGPerCm3": 12,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1945,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.97381,
    "meltingPointK": 1449.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 96,
    "symbol": "Cm",
    "name": "Curium",
    "atomicMass": 247,
    "atomicMassDisplay": "247",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f7 6d 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 13.51,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1944,
    "radioactive": true,
    "oxidationStates": [
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 5.992241,
    "meltingPointK": 1618.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "atomicMass": 247,
    "atomicMassDisplay": "247",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f9 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 14.78,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1949,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.19785,
    "meltingPointK": 1259.15,
    "boilingPointK": null,
    "phaseNote": "β form"
  },
  {
    "atomicNumber": 98,
    "symbol": "Cf",
    "name": "Californium",
    "atomicMass": 251,
    "atomicMassDisplay": "251",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f10 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 15.1,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1950,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4,
      5
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.281878,
    "meltingPointK": 1173.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "atomicMass": 252,
    "atomicMassDisplay": "252",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f11 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 8.84,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1952,
    "radioactive": true,
    "oxidationStates": [
      2,
      3,
      4
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.3684,
    "meltingPointK": 1133.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "atomicMass": 257,
    "atomicMassDisplay": "257",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f12 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 9.7,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1953,
    "radioactive": true,
    "oxidationStates": [
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.5,
    "meltingPointK": 1800.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "atomicMass": 258,
    "atomicMassDisplay": "258",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f13 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 10.3,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1955,
    "radioactive": true,
    "oxidationStates": [
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.58,
    "meltingPointK": 1100.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 102,
    "symbol": "No",
    "name": "Nobelium",
    "atomicMass": 259,
    "atomicMassDisplay": "259",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 10,
    "electronConfiguration": "[Rn] 5f14 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 9.9,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1957,
    "radioactive": true,
    "oxidationStates": [
      2,
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 6.62621,
    "meltingPointK": 1100.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "atomicMass": 262,
    "atomicMassDisplay": "262",
    "group": 3,
    "period": 7,
    "block": "f",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 7s2 7p1",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 15.6,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1961,
    "radioactive": true,
    "oxidationStates": [
      3
    ],
    "mainOxidationStates": [
      3
    ],
    "firstIonizationEnergyEv": 4.96,
    "meltingPointK": 1900.15,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "atomicMass": 267,
    "atomicMassDisplay": "267",
    "group": 4,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d2 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 23.3,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1969,
    "radioactive": true,
    "oxidationStates": [
      3,
      4
    ],
    "mainOxidationStates": [
      4
    ],
    "firstIonizationEnergyEv": 6.02,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "atomicMass": 268,
    "atomicMassDisplay": "268",
    "group": 5,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d3 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 29.3,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1970,
    "radioactive": true,
    "oxidationStates": [
      3,
      4,
      5
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 6.8,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "atomicMass": 271,
    "atomicMassDisplay": "271",
    "group": 6,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d4 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 35,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1974,
    "radioactive": true,
    "oxidationStates": [
      3,
      4,
      5,
      6
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 7.8,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "atomicMass": 274,
    "atomicMassDisplay": "274",
    "group": 7,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d5 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 37.1,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1976,
    "radioactive": true,
    "oxidationStates": [
      3,
      4,
      5,
      7
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 7.7,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "atomicMass": 269,
    "atomicMassDisplay": "269",
    "group": 8,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d6 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 40.7,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1984,
    "radioactive": true,
    "oxidationStates": [
      3,
      4,
      6,
      8
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": 7.6,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "atomicMass": 276,
    "atomicMassDisplay": "276",
    "group": 9,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d7 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 37.4,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1982,
    "radioactive": true,
    "oxidationStates": [
      1,
      3,
      6
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "atomicMass": 281,
    "atomicMassDisplay": "281",
    "group": 10,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d9 7s1",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 34.8,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1994,
    "radioactive": true,
    "oxidationStates": [
      2,
      4,
      6
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "atomicMass": 281,
    "atomicMassDisplay": "281",
    "group": 11,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d10 7s1",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 28.7,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1994,
    "radioactive": true,
    "oxidationStates": [
      -1,
      3,
      5
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "atomicMass": 285,
    "atomicMassDisplay": "285",
    "group": 12,
    "period": 7,
    "block": "d",
    "seriesId": 8,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 14,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1996,
    "radioactive": true,
    "oxidationStates": [
      2,
      4
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "atomicMass": 286,
    "atomicMassDisplay": "286",
    "group": 13,
    "period": 7,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 16,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 2015,
    "radioactive": true,
    "oxidationStates": [],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "atomicMass": 289,
    "atomicMassDisplay": "289",
    "group": 14,
    "period": 7,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 9.928,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 1998,
    "radioactive": true,
    "oxidationStates": [],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "atomicMass": 288,
    "atomicMassDisplay": "288",
    "group": 15,
    "period": 7,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 13.5,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 2003,
    "radioactive": true,
    "oxidationStates": [],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "atomicMass": 293,
    "atomicMassDisplay": "293",
    "group": 16,
    "period": 7,
    "block": "p",
    "seriesId": 7,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 12.9,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 2000,
    "radioactive": true,
    "oxidationStates": [
      -2,
      4
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "atomicMass": 294,
    "atomicMassDisplay": "294",
    "group": 17,
    "period": 7,
    "block": "p",
    "seriesId": 6,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": null,
    "densityGPerCm3": 7.2,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 2010,
    "radioactive": true,
    "oxidationStates": [
      -1,
      5
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  },
  {
    "atomicNumber": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "atomicMass": 294,
    "atomicMassDisplay": "294",
    "group": 18,
    "period": 7,
    "block": "p",
    "seriesId": 2,
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
    "electronegativity": null,
    "atomicRadiusPm": null,
    "electronAffinityEv": 0.056,
    "densityGPerCm3": 7,
    "abundanceCrustMgPerKg": null,
    "discoveryYear": 2002,
    "radioactive": true,
    "oxidationStates": [
      -1,
      1,
      2,
      4,
      6
    ],
    "mainOxidationStates": [],
    "firstIonizationEnergyEv": null,
    "meltingPointK": null,
    "boilingPointK": null,
    "phaseNote": null
  }
] as const satisfies readonly RawPeriodicElementRecord[];
