import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
export async function runAssetCases({sql,concurrentSql,roleSql,as,users}) {
  const id=randomUUID(),hash='a'.repeat(64),path=`${users.a}/${id}.pdf`;
  const reserve=(assetId=id,size=100)=>`select to_jsonb(public.reserve_user_asset('${assetId}','Example.pdf','application/pdf',${size},'${hash}'));`;
  const complete=`select public.complete_user_asset('${id}','${users.a}','${hash}',100,'application/pdf');`;
  assert.throws(()=>as(null,reserve(),'anon'),/permission denied/);
  assert.equal(JSON.parse(as(users.a,reserve())).status,'pending');
  assert.equal(JSON.parse(as(users.a,reserve())).id,id);
  assert.throws(()=>as(users.b,reserve()),/ASSET_NOT_FOUND/);
  assert.equal(as(users.b,`select count(*) from public.user_assets where id='${id}';`),'0');
  for(const actor of [users.a,users.creator,users.admin])assert.throws(()=>as(actor,complete),/permission denied/);
  assert.throws(()=>as(null,complete,'service_role'),/ASSET_UPLOAD_INCOMPLETE/);
  assert.throws(()=>as(users.a,`insert into storage.objects(bucket_id,name) values('private-assets','${users.a}/unreserved.pdf');`),/row-level security/);
  assert.throws(()=>as(users.b,`insert into storage.objects(bucket_id,name) values('private-assets','${path}');`),/row-level security/);
  as(users.a,`insert into storage.objects(bucket_id,name) values('private-assets','${path}');`);
  assert.equal(as(users.a,`select count(*) from storage.objects where bucket_id='private-assets';`),'1');
  assert.equal(as(users.b,`select count(*) from storage.objects where bucket_id='private-assets';`),'0');
  assert.equal(as(null,`select count(*) from storage.objects where bucket_id='private-assets';`,'anon'),'0');
  assert.equal(as(users.b,`with removed as(delete from storage.objects where bucket_id='private-assets' returning id) select count(*) from removed;`),'0');
  assert.throws(()=>as(null,`select public.complete_user_asset('${id}','${users.a}','${hash}',99,'application/pdf');`,'service_role'),/ASSET_VERIFICATION_FAILED/);
  as(null,complete,'service_role');as(null,complete,'service_role');
  assert.equal(as(users.a,`select status from public.user_assets where id='${id}';`),'ready');
  as(users.a,`select public.mark_user_asset_deleting('${id}');`);
  assert.throws(()=>as(null,`select public.finish_user_asset_deletion('${id}','${users.a}');`,'service_role'),/ASSET_DELETE_INCOMPLETE/);
  as(null,`delete from storage.objects where bucket_id='private-assets' and name='${path}';select public.finish_user_asset_deletion('${id}','${users.a}');`,'service_role');
  assert.equal(sql(`select count(*) from public.user_assets where id='${id}';`),'0');
  const stagedId=randomUUID(),batchId=randomUUID();
  const staged=JSON.parse(as(users.a,`select to_jsonb(public.reserve_user_asset('${stagedId}','Imported.pdf','application/pdf',100,'${hash}','${batchId}'));`));
  assert.equal(staged.import_batch_id,batchId);
  assert.throws(()=>as(users.a,reserve(stagedId)),/ASSET_RESERVATION_CONFLICT/);
  as(users.a,`insert into storage.objects(bucket_id,name) values('private-assets','${staged.storage_path}');`);
  as(null,`select public.complete_user_asset('${stagedId}','${users.a}','${hash}',100,'application/pdf');`,'service_role');
  assert.equal(as(users.a,`select status from public.user_assets where id='${stagedId}';`),'staged');
  assert.equal(as(users.a,`select count(*) from storage.objects where name='${staged.storage_path}';`),'0');
  assert.throws(()=>as(users.a,`update public.user_assets set status='ready' where id='${stagedId}';`),/permission denied/);
  assert.throws(()=>as(users.creator,"insert into storage.objects(bucket_id,name) values('tutorial-videos','forbidden.mp4');"),/row-level security/);
  as(users.admin,"insert into storage.objects(bucket_id,name) values('tutorial-videos','operator.mp4');delete from storage.objects where bucket_id='tutorial-videos' and name='operator.mp4';");
  const competing=await Promise.all(Array.from({length:12},()=>concurrentSql(roleSql('authenticated',users.b,reserve(randomUUID(),52428800)))));
  assert.equal(competing.filter(result=>result.status===0).length,10);
  assert(competing.filter(result=>result.status!==0).every(result=>result.stderr.includes('ASSET_STORAGE_LIMIT')));
  assert.equal(sql(`select sum(size_bytes) from public.user_assets where owner_id='${users.b}';`),'524288000');
  console.log('PASS private Storage SQL ownership, reserved-path-only upload, service-only verified completion, deletion fencing and concurrent500MiB reservation quota (Storage HTTP not simulated)');
}
